### ISSUE TITLE
Linking data set metadata with WMTS services

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-geoportal#1]
Dear colleagues,
I am unable to link datasets with WMTS services. The content of dataset metadata, services metadata and service capabilities seems ok, but no link is established.
Resource linkages checker tool reports as shown in the pictures below.
![Przechwytywanie](https://user-images.githubusercontent.com/25637709/101368289-40a23c00-38a7-11eb-9351-7f6a89eca38d.PNG)
![Przechwytywanie1](https://user-images.githubusercontent.com/25637709/101368441-72b39e00-38a7-11eb-85db-5bfc939cea35.PNG)

Please find below examples of investigated metadata and service for GN theme.
- dataset metadata http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full&ID=576c3269-2ba4-49af-bc97-8abf932bba32
- services metadata http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full&ID=fd62b472-b3c5-4403-ad29-9d39e6f42510
- service URI http://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/G2_INSPIRE_GN?REQUEST=GetCapabilities&SERVICE=WMTS
Please investigate and let me know what should be corrected in our linking configuration.

Best regards,
Marcin Grudzień

**Comment by df-git** [comment]
Dear Marcin,
Thank you for your message.
Unfortunately we are currently very busy with many requests in preparation of the Monitoring deadline of next week.
We cannot promise to help you before the deadline, so any intervention on your side would for sure be useful.

We suggest to check the document (https://inspire-geoportal.ec.europa.eu/files/INSPIRE_Geoportal_process_for_data-service_linking_v1.0.pdf) available in the Linkage checker page in order to understand how to correctly implement linkages.
In addition, you can also review the Technical Guidance for View services (https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-view-services-1).

Best regards.

**Comment by dartasensi** [comment]
Dear Marcin,

could you please check if the issue you mentioned is still valid? As announced at the last MIG-T meeting, we intend to offer support on Geoportal code only for critical bugs.

Kind regards,
Davide

**Comment by marty1357** [comment]
The issue is still valid.

**Comment by dartasensi** [comment]
Thank you for your assessment. I will now proceed to check if this linkage issue involves a potential bug in the Geoportal.
I will let you know as soon as I found something.

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources. 
However, we have taken note of the potential issue in the current Geoportal and will do our best for addressing it in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
