### ISSUE TITLE
RO: New CSW for INSPIRE Geoportal Harvest console

### ISSUE THREAD

**Issue by SimonaBunea** [INSPIRE-MIF/helpdesk-geoportal#10]
Dear Helpdesk Geoportal,

We have a new CSW for Romania.
The new URL is https://geoportal.gov.ro/metadata_manager_v2/csw?service=CSW&Request=GetCapabilities
This CSW only provides access to INSPIRE data sets, data series and services. Hence, it is no more needed to apply any filter to filter out other non-INSPIRE data sets, series and services.
This CSW provide metadata TG2.0, so if it is possible to test this URL in the Harvest console and after to replace the actual CSW with this one.

Best regards,
Simona Bunea

**Comment by df-git** [comment]
Dear Simona,
Thank you for your message.
We tried to load the new endpoint specified, but unfortunately we have an error.
It seems that the service is responding in 2 different ways when it is called with or without the "version" parameter.
The INSPIRE Extended Capabilities is missing when called with the "version" parameter.

Furthermore, I tried to validate the new endpoint with the INSPIRE Reference Validatror, and  the test ends with errors (the initialize phase fails).
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID5f1112c7-0f79-43c9-bf51-2cc21de2fac4.html

I also validated the old endpoint and the initialize phase is successful (Extended Capabilities found):
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID0f6f8a8c-13ab-4db7-9563-f1e3c7b9bd33.html

Can you please check your new endpoint?
Best regards

**Comment by SimonaBunea** [comment]
Thank you!
We notice too what you observed, so will try to fix it and come back to you with an announcement.
Best regards,
Simona Bunea

**Comment by MarcoMinghini** [comment]
Dear @SimonaBunea,
the harvests for the 2020 Monitoring and Reporting started this morning and have all been scheduled to happen within the end of the week (Friday at the latest), so it is of primary importance that your endpoint is ready as soon as possible to be considered in the Monitoring and Reporting process.
Best regards.

**Comment by SimonaBunea** [comment]
Dear @MarcoMinghini ,

Thank you! 
Sorry for the delay, we had some technical problems with the infrastructure, but in the end we succeeded.
We validated with INSPIRE validator and everything seems ok : https://inspire.ec.europa.eu/validator/v2/TestRuns/EID886c1a82-3d4c-4890-ad6b-ec49c2ced333.html 
Please, could you try a harvest test for the new endpoint?

Thank you in advance,
Simona Bunea

**Comment by df-git** [comment]
Dear @SimonaBunea,
We ran your new endpoint in our test environment and it is now successfully ending.
It will be used for the Monitoring and Reporting 2020 activity.

Best regards,
Daniele on behalf of the INSPIRE Support team

**Comment by SimonaBunea** [comment]
Dear Daniele and Marco,

Good news!
Thank you a lot!

Best regards,
Simona Bunea
