### ISSUE TITLE
Problem with resource linkages checker tool

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#100]
Trying to use resource linkages checker tool https://inspire-geoportal.ec.europa.eu/linkagechecker.html  there is no any results, it seems that this tools don`t work at all. All the time is received and nothing happens -> 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/56715045/160621341-123dc9bf-4b75-4111-94ae-253428f33792.png">

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

Therefore, open issues affecting the current INSPIRE Linkage Checker (being part of the infrastructure tools associated to the current INSPIRE Geoportal backend) will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
