### ISSUE TITLE
Service metadata not available on Inspire portal

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#101]
We see the problem, that many of services from our metadata catalogue are not available on Inspire portal. 

For example -> https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-10108b88-d195-11e5-91ce-52540023a883_20220330-093802%2Fservices%2F1%2FPullResults%2F401-425%2Fdatasets%2F1&expandedSection=metadata

Data metadata are available on Inspire Geoportal ->  https://geometadati.viss.gov.lv/geoportal/rest/document?id=%7B33F9A1CB-6520-4953-8794-88BCB8D637B5%7D

View service metadata are available on Inspire Geoportal -> https://geometadati.viss.gov.lv/geoportal/rest/document?id=%7BACF4EB05-4A9E-431F-A22E-63E9D38C5554%7D 

Download service metadata are NOT available in Inspire Geoportal -> https://geometadati.viss.gov.lv/geoportal/rest/document?id=%7BE7CD2078-0767-4686-B169-EDE511C23998%7D 

Linkage checker shows, that with service and metadata linkage everything is OK -> https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-8e52005c-b000-11ec-aaad-0050563f01ec_20220330-100817/ 

<img width="434" alt="image" src="https://user-images.githubusercontent.com/56715045/160787064-3640b0e1-5464-46aa-ac55-4350bf510905.png">

**Comment by jescriu** [comment]
Dear @vicehovskis,
Thank you for your patience.

As mentioned in https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/102#, a new harvest of the Latvian discovery service endpoint was executed on 16th May, and the results are pending to be published from your side.
Please, have a look and check if this dataset is now appropriately recognise as downloadable, as you expected.

Thank you.
