### ISSUE TITLE
Geoportal harvest: Downloadable Data Sets amount very low

### ISSUE THREAD

**Issue by agesild** [INSPIRE-MIF/helpdesk-geoportal#102]
Hello,
- Last 4 Estonian metadata harvesting attempts results since 31.03 show very low amount of downloadable data sets. Only 5 datasets are marked as downloadable, Last normal harvest was 47!! 
- Linkage checker control results does not match harvesting result.

- Example of metadata complect that is green in linkage checker but does not have a download service by harvest:

Datased metadata: https://metadata.geoportaal.ee/geonetwork/srv/est/xml.metadata.get?uuid=stat_rahvastikutihedus
WMS metadata: https://metadata.geoportaal.ee/geonetwork/srv/est/xml.metadata.get?uuid=b980cdc2-9791-4ab6-aaf2-bf4d73cb4f16
WFS metadata: https://metadata.geoportaal.ee/geonetwork/srv/est/xml.metadata.get?uuid=935e7890-f673-43b8-ad58-22f5b941f63b

![harvestRaport-04-04-2022](https://user-images.githubusercontent.com/16571419/161502457-8875ecc3-827f-434c-938f-89d6a44d5814.JPG)

**Comment by ffarr2019** [comment]
We (Malta) have the same issues 

![image](https://user-images.githubusercontent.com/32981299/162440930-882f2e30-1068-4e10-9e37-38d4add5157c.png)

**Comment by vicehovskis** [comment]
Latvia has the same issue, but there is no response to the tickets.

**Comment by laers** [comment]
Denmark has the same issue.

**Comment by jrc-inspire** [comment]
Dear colleagues,
As mentioned in other issue threads regarding this problem, our INSPIRE Geoportal IT Team is still investigating the possible cause of the reported drop in the number of downloadable datasets for several endpoints. At the moment, without any results.
Since the code of the Geoportal has not been changed from the past M&R2021 round, we are focusing our analysis in other potential causes which might be preventing the obtention of the proper results. This includes the possibility that the services being checked could be denying the service to INSPIRE Geoportal requests, considering them as an DoS Attack

**Comment by jescriu** [comment]
Dear all,

Our INSPIRE Geoportal IT team made (quite recently) some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries through the harvest console.

@agesild - A new harvest of the Estonian discovery service endpoint was executed on 4th May, providing much better results particularly in terms of downloadable datasets:
![image](https://user-images.githubusercontent.com/22743378/168662118-a86fe12c-78fe-4219-820d-79783225cdd7.png)
We were willing to contact you to ask about the new results, but I can see that the results are now published in the INSPIRE Geoportal. I hope this means that you are satisfied with the results. Please, feel free to provide any additional feedback.

@vicehovskis - Regarding Latvia, a new harvest of the discovery service endpoint was executed on 16th May, also providing much better results, and again particularly in terms of downloadable datasets. Still pending to be published from your side. Please, have a look and provide feedback if necessary.

@ffarr2019 - The same in case of Malta. Last harvest executed on 4th May. Much better results compared to your post on 8th April. Similar results than those latest published (few decrease in terms of downloadable and viewable). Still pending to be published from your side. Please, have a look and provide feedback if necessary.

@laers - We will investigate your case more deeply. The issues in your case seem different. Please open a new issue in the Helpdesk providing few examples of datasets that were downloadable / viewable in the previously published harvest that now are not recognised as such.

Thank you
