### ISSUE TITLE
Assistance on new harvesting result

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-geoportal#106]
We have ran a new harvesting of the Greek metadata catalog. 
We could use some assistance on the results regarding the following 2 resources that seem to be problematic.
- http://geoportal.ypen.gr/geonetwork/srv/api/records/96e94573-281c-452b-b27a-f4428bac8147/formatters/xml
- http://geoportal.ypen.gr/geonetwork/srv/api/records/011f6169-91b0-44bc-866a-6b5e0d7b68f0/formatters/xml

After the harvesting result, we used the Linklage Checker tool for more information.
The problem reported is that the Download link has not been determined.
The tool proposes to check the resources with the validator. The validation was succesful. 

Could you please assist us on identifying the problem?

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
