### ISSUE TITLE
AT: Harvesting result not being published

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#107]
Hi,
I did a Harvesting for our AT Endpoint. The harvesting did complete, but the Publish operation seems to be stuck since 2 hours. 
Can you have a look into it?

![image](https://user-images.githubusercontent.com/45065613/169257592-99718b2d-d8a0-4065-8c5b-eb8a432be239.png)

**Comment by jescriu** [comment]
Dear @manilly,
Thank you for warning us. Out IT Geoportal team will have a look and let you know as soon as possible.
All the best.

**Comment by manilly** [comment]
Latest publish worked as expected
