### ISSUE TITLE
Geoportal harvest console - access Forbidden 

### ISSUE THREAD

**Issue by martin-saliba** [INSPIRE-MIF/helpdesk-geoportal#11]
Please note that when accessing the geoportal harvest console I have a forbidden message. This also applies to other users. 

- [ ] when accessing the geoportal harvest console the message "Forbidden You don't have permission to access /harvestconsole/"  is displayed in the browser.
- [ ]Chrome Version 87.0.4280.88
- [ ] a screenshot illustrating the problem - attached
- [ ] the URL of the page - https://inspire-geoportal.ec.europa.eu/harvestconsole/

Thank you 
Martin Saliba
Malta INSPIRE Directive National Contact 

![Harvest console forbidden image](https://user-images.githubusercontent.com/76993075/103620761-5d787080-4f34-11eb-9fbc-6c7c5f930386.png)

**Comment by df-git** [comment]
Dear @martin-saliba ,
Thank you for your message.
The INSPIRE Geoportal Harvest Console has been disabled to perform the Monitoring and Reporting 2020 activities.
It will be enabled once the activity will be completed (it may take 1 or 2 weeks more).

Best regards,
Daniele on behalf of the INSPIRE Support team
