### ISSUE TITLE
new harvesting hasn't been completed since May 31st

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-geoportal#110]
The harvesting we requested on May 31st has not been completed yet.
![image](https://user-images.githubusercontent.com/55238073/172151968-f565d544-4c3f-42b0-9483-f0b55dcd639f.png)
I guess there is nothing we can do from our side.
Could you please stop this in order for us to request a new one?

Thanks in advance.

Elena

**Comment by jescriu** [comment]
Dear @grigoriouelena,
We will have a look as soon as possible and let you know.
The harvest should be stuck.
All the best.

**Comment by jescriu** [comment]
Dear @grigoriouelena,
Our INSPIRE Geoportal IT team restarted your harvest and successfully finished.
Please, revise the results through the harvest console. 
All the best.
