### ISSUE TITLE
Linkage Checker claims a missing resource locator (URL) of the Data Set from the Download service but the metadata is tested valid by the Reference validator and the link can be seen in the Geoportal

### ISSUE THREAD

**Issue by PeKoNW** [INSPIRE-MIF/helpdesk-geoportal#111]
The Linkage Checker claims a missing resource locator (URL) of the Data Set from the Download service when checking the dataset "INSPIRE NW Verwaltungseinheiten ALKIS" (d98a75f3-547b-4ebd-9d15-e24e4d27a6a4) and its coupled services WMS (bb507dab-926a-4db3-b06a-eb1a9885a6ac) and WFS (e53e2a4b-9760-4f59-a8d8-cb5794c556bd).
Checking the metadata itself with the Reference validator gives no errors. The presentation in the Geoportal including the view and download options is o.k. as well.

**Comment by oberseri** [comment]
The same problem for many Austrian Datasets (e.g. 004eb63f-4562-420f-84e4-bfbcffdde32d or 3c3803b3-1b53-4fb5-9595-9217b9891862); dataset metadata are valid, datasets are downloadable in the geoportal, BUT are marked as "not downloadable" in the geoportal overview list (no icon) and in the linkage checker report.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
