### ISSUE TITLE
LT: Harvesting problem

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk-geoportal#114]
Dear Geoportal Helpdesk, 

we wanted to harvest Lithuania's metadata into the INSPIRE Geoportal. The problem is that, after we run  "Schedule a new harvest" we don't get the "check and publish" option, only the "Schedule a new harvest" option appears again. Could you please assist us in identifying the problem?

![1](https://user-images.githubusercontent.com/79690428/181503727-898e3f68-a97d-47fe-88ae-0eebf4510a7f.JPG)

**Comment by jescriu** [comment]
Dear @JulianaKar,
Thanks for letting us know.
This morning there was an issue with the harvest console and we run out of resources. Maybe this is the reason for this behaviour.
We will let you know when the console is running properly again.

**Comment by jescriu** [comment]
Dear @JulianaKar,
For some reason your previous harvest failed, but the error was present in the Harvest Console user interface only for a while - Yesterday we had to re-start the system and, as a result, the error notification disappeared from the interface.
Today we launched ourselves a new harvest of your endpoint and it was successful. 
Please check and publish the results at your earliest convenience.
Regards.

**Comment by JulianaKar** [comment]
Thank you, @jescriu , for your help. 
Unfortunately, I still have challenges with harvesting. When I looked at the report of the last pre-publish harvest ( Fri Jul 29 2022 12:32:02 GMT), I saw a decrease in the as-is metadata download services, but from our side, no changes were made to that metadata. I decided to initiate a new harvest, hoping that the new one will show better results.
After that,  I am repeatedly getting the harvest error. Could you please have a look at what might be wrong with it?
![2](https://user-images.githubusercontent.com/79690428/182108452-97f6b721-9efe-4d35-9137-96d948e8dccb.JPG)
