### ISSUE TITLE
Downloadable WCS (Web Coverage Service) on geoportal

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-geoportal#12]
We have a dataset on the geoportal (https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-f0c91711-ece0-11e8-a08e-52540023a883_20201211-170302%2Fservices%2F1%2FPullResults%2F341-360%2Fdatasets%2F7&expandedSection=metadata) which contains a link to a WCS service

The metadataset of the data (https://metadata.vlaanderen.be/srv/api/records/9c5383b3-b925-4dae-9b85-104fa0b703b4/formatters/xml), 
metadata of the service (https://metadata.vlaanderen.be/metadatacenter/srv/dut/csw?request=GetRecordById&service=CSW&constraintLanguage=CQL_TEXT&version=2.0.2&resultType=results&ElementSetName=full&typenames=csw:Record&id=fdefde20-c974-68a3-a1b0-48d8-fe42-7535-e62b1876&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd)
 and the service itself
https://inspire.informatievlaanderen.be/overdrachtdiensten/el-dtm/wcs?service=WCS&version=2.0.1&request=GetCapabilities
seem to be valid using the ETF validator.

So I am wondering why this dataset is not visible on the geoportal as downloadable. I was also wondering if there is a full example available on the geoportal with a downloadable WCS service.

![image](https://user-images.githubusercontent.com/13509656/104349534-5688c980-5503-11eb-967c-e1b890774137.png)

**Comment by bcosyn** [comment]
For your interest. WCS service is an arcgis 10.5 WCS service and it delivers strictly image/tiff as format for version 2.0.1. More recent testing on our new 10.7.1 and  10.8.1 env do not show any change in the format. This format delivered by ESRI arcgis server is an XML based response with a blob.

**Comment by dartasensi** [comment]
Dear @bcosyn 

thank you for the question. Unfortunately, at the moment the Geoportal doesn't offer full support for Download services implemented as WCS (similar situation with SOS services).
I would inform you that this issue is known and it will be included in the backlog list of the upcoming evolution of the Geoportal software.

Regards,
Davide

**Comment by bcosyn** [comment]
Any global idea on the time frame for this?

**Comment by MartinTuchyna** [comment]
Dear all, 
any update on the possible Geoportal support for WCS?
Thanks, Martin

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
Therefore, we will consider your request in the future in the context of the redesigned INSPIRE Geoportal based on GeoNetwork.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Your request will be potentially considered in the evolution of the revamped GeoNetwork-based INSPIRE Geoportal.

Excuses for any inconvenience caused.
