### ISSUE TITLE
AT: datasets not viewable

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/helpdesk-geoportal#123]
At the last harvesting(s) serveral datasets were marked as not viewable, although they were before and nothing has changed in the meantime.
Validation and linkage checker show positive results ... - any idea how this "unstable" results occur?
Examples are DS 86548E64-99A6-4D9C-9555-396C02D9B42D, 92DB7B6A-2ACE-4823-B993-374280D2EF6E, 074C57F2-25CB-4A21-8264-377C999843F7 (all of them provided via VS 9684B7C3-69A4-48FA-9BB5-9AE9210C9D4B) or fbd0d3da-e025-4728-8fd5-22ad5f530511, 915d3e29-5b63-4e2a-a6ce-b82628a41522, c115a631-b828-43ee-a959-68e9c4b1c80b

Thanks and best regards
Erik

**Comment by jescriu** [comment]
Dear @oberseri,
As you know, JRC is prioritising the work on the new INSPIRE Geoportal, which will be the system used in the next INSPIRE M&R. For this reason, resolving the issues affecting indicators obtained through the use of the current Geoportal are not being prioritised at this moment.

We suggest you to start practising the new GeoNetwork backend, even not being officially launched yet.

Thank you for your patience.

**Comment by oberseri** [comment]
OK, thanks Jordi!

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - at its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
