### ISSUE TITLE
Link checker does not respect all media-types

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-geoportal#130]
The inspire link checker does not respect all media-types for download files advertised in ATOM download services:

media-types that should be valid according to the [TG for download services](https://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_v3.1.pdf) : see paragraph 5.2.5 are not seen as valid media types in the linkage checker:
- application/x-gmz https://inspire.ec.europa.eu/media-types/application/x-gmz
- application/geopackage+sqlite3 https://inspire.ec.europa.eu/media-types/application/geopackage+sqlite3

![image](https://user-images.githubusercontent.com/22592588/206196350-7663631d-a4f6-4084-b7ca-05b89d19a940.png)

Example 1. ATOM with content application/x-gmz:
dataset metadata: https://nationaalgeoregister.nl/geonetwork/srv/api/records/b4ae622c-6201-49d8-bd2e-f7fce9206a1e/formatters/xml
view service metadata: https://nationaalgeoregister.nl/geonetwork/srv/api/records/5be14ec9-9bb3-4395-a061-e7e78d04a527/formatters/xml
download service metadata: https://nationaalgeoregister.nl/geonetwork/srv/api/records/bb85e473-c04a-42a6-9fdc-f0bb0239327e/formatters/xml

The link checker validation report reports:
![image](https://user-images.githubusercontent.com/22592588/206197198-fa6a531d-c937-42cd-9588-71a759ee039d.png)

Example 2. ATOM with content application/geopackage+sqlite3
dataset metadata: https://nationaalgeoregister.nl/geonetwork/srv/api/records/fcefa13c-44e2-4953-b6d6-1ddceebc57fc/formatters/xml
view service metadata: https://www.nationaalgeoregister.nl/geonetwork/srv/api/records/3e6e285e-f0f0-4bb8-b14f-a9d1b9ea62a7/formatters/xml
download service metadata: https://www.nationaalgeoregister.nl/geonetwork/srv/api/records/b8300fd4-3224-4b44-ae92-3eb82da0bb85/formatters/xml

The link checker validation report reports:
![image](https://user-images.githubusercontent.com/22592588/206198862-dc77e165-f020-4c6b-a842-217f5466694b.png)

These errors in the link checker could possible be the reason for missing download properties in the thematic viewer as reported in https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/129

**Comment by jrc-inspire** [comment]
Dear @mwjsanders,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - at its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
