### ISSUE TITLE
BE : Impossible to harvest

### ISSUE THREAD

**Issue by vbombaerts** [INSPIRE-MIF/helpdesk-geoportal#131]
We want to launch a harvest and link checking process on the BE-WALLONIE harvester. It is impossible to get the result of the harvesting process. Harvester stays in the state "Determining work".
@jescriu When will the harvesting console work again ? We are one week from the monitoring deadline and we are not able to harvest and check the links.

**Comment by vbombaerts** [comment]
Seems to be OK now

**Comment by jescriu** [comment]
Dear @vbombaerts,
Yesterday we noticed some harvesters stuck. 
This morning the services were rebooted.
Hope it works again without relevant issues.
