### ISSUE TITLE
Revamped Geoportal - Missed datasets when published (BE-WALLONIE)

### ISSUE THREAD

**Issue by dbu-spw** [INSPIRE-MIF/helpdesk-geoportal#132]
Hi INSPIRE Geoportal team,

We have harvested our catalogue (BE-WALLONIE end-point) with the revamped INSPIRE Geoportal but we have noticed that when we push the harvested metadata to publish them on the Geoportal, many of them are missed in the INSPIRE Thematic Data viewer (on the revamped geoportal).

e.g. no problem was reported by the harvester for our PS datasets, the number of retrieved metadata records is ok, unfortunately no PS datasets from the BE-WALLONIE are listed in the INSPIRE Thematic Data https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/catalog.search#/overview?view=themeOverview&theme=ps

All is ok with the classical INSPIRE Geoportal. 

Thanks for your help

Dominique Buffet (BE-WALLONIE)

**Comment by jrc-inspire** [comment]
Dear @dbu-spw,

As explained in the [73 INSPIRE MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/73rd+MIG-T+meeting+2023-02-17) the results obtained through harvesting using the [revamped INSPIRE Geoportal GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork) (system used for the Monitoring and Reporting 2022) are still not available under the [INSPIRE Geoportal domain](https://inspire-geoportal.ec.europa.eu/), only through the own GeoNetwork console.

When the rollout of the revamped INSPIRE Geoportal is taking place, which will hopefully happen by the end of September or beginning of October 2023, the situation will be normalised and the results will become available through the INSPIRE Geoportal domain.

Excuses for any inconveniences caused (and for the delay in replying).
