### ISSUE TITLE
HU- Access to geonetwork

### ISSUE THREAD

**Issue by palyatamas** [INSPIRE-MIF/helpdesk-geoportal#135]
I can not reach the Geonetwork admin_hungary interface. (In December it was success.) I was trying with the original password.
What could be the problem?

**Comment by jescriu** [comment]
Dear @palyatamas,

There is no problem at all. The MS/countries administration users are temporarily disabled, while the calculation of the Monitoring and Reporting indicators for 2022 is taking place.

The GeoNetwork harvesting console will remain closed until we present the indicators results in the 73 INSPIRE MIG-T Meeting, as communicated through the MIG-T mailing list in December.
