### ISSUE TITLE
No Download/View services found for dataset 

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-geoportal#136]
Dear all,

We have noticed, that our view and download services for administrative units theme ([INSPIRE BB Verwaltungseinheiten ALKIS](https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-4fed3eb0-06fa-11ea-8480-525400695e9c_20221103-110203%2Fservices%2F1%2FPullResults%2F11281-11300%2Fdatasets%2F19&expandedSection=metadata)) cannot be retrieved in the EU-Geoportal:

![grafik](https://user-images.githubusercontent.com/8046960/216649264-fe08dbab-bddf-44e6-9477-04fdbe4230b3.png)

The Capabilities of the Services are:
WFS:		https://inspire.brandenburg.de/services/au_alkis_wfs?request=GetCapabilities&service=WFS
WMS:		https://inspire.brandenburg.de/services/au_alkis_wms?request=GetCapabilities&service=WMS

We have used the Linkage checker with the corresponding metadata-URLs:
Dataset:		https://geoportal.brandenburg.de/gs-json/xml?fileid=0cbc19b7-169c-467a-828d-380bc4793e50 
WFS:		https://geoportal.brandenburg.de/gs-json/xml?fileid=3437cec4-957e-4563-9b56-9822f3cbecbe
WMS:		https://geoportal.brandenburg.de/gs-json/xml?fileid=083cfd6a-1de5-457c-8c9d-b268af5d747b

and have received the following report: 
![grafik](https://user-images.githubusercontent.com/8046960/216650122-e83eb6a1-c597-4a49-8663-80adb515f744.png)

In order to clarify the reason for this problem we have validated the metadata with the [INSPIRE reference validator](https://inspire.ec.europa.eu/validator/test-selection/index.html) and all 3 metadata-URLs have passed the Tests. Here the reports: [Test run on 16 23 - 03.02.2023  INSPIRE metadata.zip](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/10580606/Test.run.on.16.23.-.03.02.2023.INSPIRE.metadata.zip)

Could you please clarify where the issue for this Linkage problem between Dataset and Download/View-Services is?

Kind regards

**Comment by Dnoack49** [comment]
Could you also please let us know what the harvest time intervals there are this year?

**Comment by jrc-inspire** [comment]
Dear @Dnoack49,

As reported in the [75 MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/75th+MIG-T+meeting+2023-07-07), the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
