### ISSUE TITLE
Error in publishing the harvest results

### ISSUE THREAD

**Issue by LauraBolocan** [INSPIRE-MIF/helpdesk-geoportal#138]
Hello,

We are trying to publish the results of our last harvest and we are facing an issue

![image](https://user-images.githubusercontent.com/117445628/222456068-fb809482-ce87-4283-a990-58131dd3ab93.png)

The "Proceed" button is inactive.
Please help us fix this issue.

Thank you in advance,
Laura Bolocan, Romania

**Comment by jrc-inspire** [comment]
Dear @LauraBolocan,

As reported in the [75 MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/75th+MIG-T+meeting+2023-07-07), the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
