### ISSUE TITLE
Back-up and pop-up tab confirming you want to delete the harvester configuration

### ISSUE THREAD

**Issue by LeireLeoz** [INSPIRE-MIF/helpdesk-geoportal#139]
We would like to know if there is any option to recover the state of the GeoNetwork Geoportal, prior to a date or if we would have to create a new harvester and perform the process from scratch. If possible, we think it would be really useful to have a back-up.

We have identified that when clicking on the "Delete" button in the "Update harvester IE" tab does not leave a pop-up tab confirming you want to delete it. We wondered if it would be possible to add a warning of the delete action in order to avoid deleting it by accident.

Many thanks in advance

![image](https://user-images.githubusercontent.com/114164641/224678843-a0631b93-2c8e-4ec9-b39d-0c34cf0e7011.png)

**Comment by jescriu** [comment]
Dear @LeireLeoz,

We totally understand your proposal. Please, propose this improvement through the public GeoNetwork open source repository.

Regarding backups, once the Revamped INSPIRE Geoportal is rolled out (expected at the end of September or beginning of October 2023), a backup strategy will be put in place in the cloud server. However, restoring previous backups would led to the related previous status for all endpoints. Therefore, not helping in the case you spotted.
