### ISSUE TITLE
Can`t access Harvest console

### ISSUE THREAD

**Issue by tvp-vk** [INSPIRE-MIF/helpdesk-geoportal#14]
Hello,

I can`t access Harvest console -> https://inspire-geoportal.ec.europa.eu/harvestconsole/ 

"Forbidden
You don't have permission to access /harvestconsole/ on this server."

There is made some changes and I can access only from define IP addresses? Or there is a new harvest console link?

**Comment by df-git** [comment]
Dear @tvp-vk 
Thank you for your message.
The INSPIRE Geoportal Harvest Console has been disabled to perform the Monitoring and Reporting 2020 activities.
It will be enabled once the activity will be completed (before the end of this).

Best regards,
Daniele on behalf of the INSPIRE Support team
