### ISSUE TITLE
GeoNetwork Harvesting -> Push metadata not working

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#142]
Hi,
I tried to push our recent harvested metadata in JRC GeoNetwork Geoportal backend, but it didn't work. 
The loading wheel was spinning some time and after finishing, nothing happened (no new metadata available). Also the last run successful date didn't change.

![image](https://user-images.githubusercontent.com/45065613/236137643-2885c407-5074-47ff-bd75-b9a757d220c6.png)

Is the GeoNetwork backend supposed to push the metadata only to internal GeoNetwork Geoportal (https://jrc-geoportal-internal.geocat.live/) or also to the "old" public Geoportal frontend (https://inspire-geoportal.ec.europa.eu/)?

**Comment by jrc-inspire** [comment]
Dear @manilly,

As explained in the [73 INSPIRE MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/73rd+MIG-T+meeting+2023-02-17) the results obtained through harvesting using the [revamped INSPIRE Geoportal GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork) (system used for the Monitoring and Reporting 2022) are still not available under the [INSPIRE Geoportal domain](https://inspire-geoportal.ec.europa.eu/), only through the own GeoNetwork console. 

This is why you cannot see any results when pressing the 'Publish' button. At the moment, you can only browse your harvested metadata records through the GeoNetwork console user interface (currently only accessible through authentication). 

When the rollout of the revamped INSPIRE Geoportal is taking place, which will hopefully happen by the end of September or beginning of October 2023, the situation will be normalised and the results will become available through the INSPIRE Geoportal domain.

Excuses for any inconveniences caused (and for the delay in replying).
