### ISSUE TITLE
Incorrect / missing linking to WMS Metadata

### ISSUE THREAD

**Issue by BLEfachzentrum** [INSPIRE-MIF/helpdesk-geoportal#146]
Hello,
for the Dataset "Weinrebe in Deutschland 2010 INSPIRE" (https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-4fed3eb0-06fa-11ea-8480-525400695e9c_20221103-110203%2Fservices%2F1%2FPullResults%2F28181-28200%2Fdatasets%2F9&expandedSection=metadata) the View Options are shown, but the WMS-Metadata are not reachable. 
A few days ago the Button "Show Service Metadata" gave us the **WFS**-Metadata, today the fields are empty. 
Thanks in advance.

![Screenshot 2023-05-26 INSPIRE Geoportal Weinrebe View Options](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/108931776/849748a9-648c-4f0d-8abf-51681028f2bc)

![Screenshot 2023-05-26 INSPIRE Geoportal Weinrebe WMS-Metadaten](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/108931776/9f07ead2-8e11-45df-9896-d6d80880a7c5)

**Comment by jrc-inspire** [comment]
Dear @BLEfachzentrum,

As reported in the [75 MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/75th+MIG-T+meeting+2023-07-07), the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
