### ISSUE TITLE
SK CSW harvest to the new EC GP harvester

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#149]
Dear EC Geoportal team.

Thanks for your advice with the update of the new CSW endpoint in the new EC GP harvester. 

Could you please check, why harvest of the new SK CSW (https://rpi.geocloud.gov.sk/csw) seems to be stacked.

We have started the harvest yesterday, (2023-06-21 09:28:40), 

![obrázok](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/6195936/36b498cc-626a-4646-9c84-2ed185af0318)

and another one (probably automatic) was lauched at midnight

![obrázok](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/6195936/ca81a08a-ef7d-4a8b-917a-e22e152ee3e3)

with no results and access to the progress status.

Thanks in advance, 

best regards, 

Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
We will retake the tests of your new endpoint from 21 August, to prevent interferences with the on-going tasks for updating the Revamped INSPIRE Geoportal cloud servers in view of the rollout of the new system, expected at the end of September or beginning of October 2023.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 

Thanks for an update. Just let us know, if any support will be needed.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
We will contact you in case of need.
Thank you.

**Comment by jescriu** [comment]
This issue was already solved during the INSPIRE Monitoring 2023.
