### ISSUE TITLE
DE: unable to publish latest session

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-geoportal#15]
Dear @dartasensi,

At the moment I'm not able to publish our latest harvest results.

- [x] description of the steps to reproduce the issue
1. go to [Harvesting Status](https://inspire-geoportal.ec.europa.eu/harvesting_status.html) and open "[Geoportal harvest console](https://inspire-geoportal.ec.europa.eu/harvestconsole/)"
2. access to the [dashboard ](https://inspire-geoportal.ec.europa.eu/harvestconsole/private.jsp)to manage the service
3. click on the button "Check and publish" > "Publish" > "Proceed"
4. get a mail "[INSPIRE Geoportal - Harvest console] Publishing latest session"
> [INSPIRE Geoportal - Harvest console] Publishing latest session	
We are processing your request.It should be published in few minutes on the INSPIRE Geoportal (http://inspire-geoportal.ec.europa.eu). 
> Details: Session id: INSPIRE-4fed3eb0-06fa-11ea-8480-525400695e9c_20201221-173502

After a couple of minutes I got the "Check and publish" - button on the Dashboard again. 

- [x] browser and version: Firefox Browser 84.0.2 (64-Bit)
- [x] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/29542183/105671845-a85a2800-5ee3-11eb-9613-0c8c84992bdd.png)
![grafik](https://user-images.githubusercontent.com/29542183/105671868-b4de8080-5ee3-11eb-815f-bce3ff4d17b0.png)

- [x] URL of the page: https://inspire-geoportal.ec.europa.eu/harvestconsole/private.jsp?ac=login

Could you please check, if the transfer and publishing of our latest harvest request is not possible due to temporarly low disk space resources on your site?

Thanks in advance and kind regards!

**Comment by dartasensi** [comment]
Dear @alitka 

the Geoportal is still transferring and indexing your data. Unfortunately, after the transfer from the sandbox to the front-end space, it takes time to index all these informations into Solr. I've just checked and it is still running. I will keep an eye on it, and let you know when it is finished.

KR,
Davide on behalf of the JRC INSPIRE Support team

**Comment by alitka** [comment]
Dear @dartasensi , Thanks for your message. I checked the numbers (metadata records) on the Geoportal and I think, that the transfer from the sandbox to the front-end space is finished now (all metadata records of the latest harvest process are available). Kind regards!
