### ISSUE TITLE
Priority Datasets suddenly don't get through the harvest anymore

### ISSUE THREAD

**Issue by PB-GNM** [INSPIRE-MIF/helpdesk-geoportal#151]
Dear INSPIRE-helpdesk,

Since yesterday, our Priority Datasets suddenly don't get through the harvest anymore:
![harvest_resultaten 4 juli 2023](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/80040145/41d0eec5-2b3e-4103-a9ed-574ff04bcc18)

Today, I tried again, but got the same result.

Is there an axplanation for this?

Best regards,
Pieter Bresters,
Geonovum

**Comment by jescriu** [comment]
Dear @PB-GNM,

This could be due to some anomalies derived from the maintenance works recently performed:
https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/150

Out ICT team is investigating the issue.
Keep you posted.

**Comment by trodin** [comment]
We have the same problem. 0 priority datasets- Croatia.

Regards,
Tanja

**Comment by jrc-inspire** [comment]
Dear @PB-GNM and @trodin ,

As reported in the [75 MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/75th+MIG-T+meeting+2023-07-07), the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any issues and improvements on this matter will have to be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
