### ISSUE TITLE
Linkage checker authorisation

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#153]
Whilst trying to access the INSPIRE linkage checker (https://inspire-geoportal.ec.europa.eu/linkagechecker.html), user name and password is requested.

![obrázok](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/6195936/a2dcf48f-4712-4b4d-b264-8103ab4c6311)

What is the reason for this change and where we can get the credentials for an access?

Thanks Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

The [Classic INSPIRE Geoportal console](https://inspire-geoportal.ec.europa.eu/harvestconsole) and its related functionalities were closed on Thursday 20 July, as it was [announced in the INSPIRE Geoportal helpdesk](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/152). The old components have been finally dismissed after recurrently warned during 2022 and 2023 in the helpdesk.

This is part of the process for rolling out the revamped system, that will (hopefully) take place at the end of September or beginning of October. 

From now onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork) and its related functionalities.

Excuses for any inconveniences caused.

**Comment by MartinTuchyna** [comment]
Dear Jordi.
Thank you for the feedback and clarifications.
