### ISSUE TITLE
Linkage checker not available

### ISSUE THREAD

**Issue by marleenvd** [INSPIRE-MIF/helpdesk-geoportal#154]
It seems that the linkage checker is not available anymore (since 20/07).
Is it possible to tell us how we can proceed with all our metadata checking?
Is there an alternative in place ?

**Comment by PB-GNM** [comment]
We noticed the same problem.
Why is there an account needed for the linkchecker?
Pieter Bresters,
Geonovum
Netherlands

**Comment by JohannaOtt** [comment]
@marleenvd @PB-GNM [this issue](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/153) is probably what you are looking for.

**Comment by jescriu** [comment]
Thanks @JohannaOtt for pointing to the appropriate answer to this post, which is indeed the reason for the unavailability of the (old) linkage checker.
