### ISSUE TITLE
Provide a beta environment for harvesting metadata from remote beta environments

### ISSUE THREAD

**Issue by marleenvd** [INSPIRE-MIF/helpdesk-geoportal#155]
It seems more logical to have a beta environment on the level of EU that is communicating with the beta environments from the member states. Is such an environment available or can it be made available ?
At this moment the only way is to go in production with new developments without testing. 
This should be avoided, therefore we suggest to provide a beta environment.

**Comment by jrc-inspire** [comment]
Access to an INSPIRE Geoportal sandbox, being an exact replica of the INSPIRE Geoportal harvesting console, was facilitated to the managers of geospatial catalogues from Member States and EFTA countries after the INSPIRE Conference 2023.
