### ISSUE TITLE
RO harvest issue

### ISSUE THREAD

**Issue by LauraBolocan** [INSPIRE-MIF/helpdesk-geoportal#156]
Dear EC Geoportal team,

We have been trying to harvest our data using the revamped GeoNetwork console (https://jrc-geoportal-internal.geocat.live/geonetwork) since yesterday, but have been unsuccessful. 
On our first attempt 10 hours ago it says that it was succesful but there isn't any log/report for confirmation, and now it just doesn't complete the process .

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/117445628/5c299797-bc8c-497f-a68a-a462afc6ca80)

Could you help us with this issue?

Thank you in advance,

Laura Bolocan,
National Agency for Cadastre and Land Registration, Romania

**Comment by jescriu** [comment]
Dear @LauraBolocan,
I just started a new harvesting process and it gets stuck in the first phase - It is having problems to create the harvesting task.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/aae14653-c692-4916-a9bb-99a836f46bc2)

Few minutes ago I tested the system and successfully harvested one of the endpoints. Please, take first a look at the logs from your server and CSW endpoint. Probably the requests from the Geoportal console are somehow rejected.

**Comment by jescriu** [comment]
Dear @LauraBolocan,
We found that some harvest attempts are getting stuck even without starting the harvesting process.
We requested our contractor (GeoCat) to restart the services and solve this situation.
Will keep you posted.

**Comment by LauraBolocan** [comment]
Dear @jescriu ,

Thank you very much for your response. Please keep me informed when you get a resolution,

Best wishes,
Laura

**Comment by jescriu** [comment]
The issue was resolved as part of the INSPIRE Monitoring 2023.
