### ISSUE TITLE
Inconsistency between Geonetwork harvesting console and INSPIRE Geoportal

### ISSUE THREAD

**Issue by benoitregamey** [INSPIRE-MIF/helpdesk-geoportal#157]
Dear EC Geoportal team,

I am recently in charge of publishing geo(meta)data for Switzerland to INSPIRE geoportal. I set up an harvester in the new [geonetwork harvesting console](https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/catalog.search#/home) that seems to work proprely :

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/61193520/1964641c-facb-447c-baa7-fa0d6571b24e)

But I don't understand why it doesn't match with the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu/overview.html?view=thematicEuOverview&theme=none) ? There, Switzerland has 207 records while 253 have been harvested and the last harvesting dates back to 23.03.2023 while it has been run today (15.08.2023) !

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/61193520/f2cf8857-da40-479c-8fed-0c7e7a765ac2)
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/61193520/f37ea79a-c25e-443d-8d1f-69979cc7ccaa)

Shouldn't be the INSPIRE Geoportal the front end part of the geonetwork harvesting console ? Or is it still not fully in production ?

Thank your help and information !
All the best
Benoit Regamey

**Comment by MatAlps** [comment]
Dear @jrc-inspire ,

Same question here for Luxembourg.
I have harvested, then clicked on the button "push metadata" (as I understood geonetwork harvesting console is NOT INSPIRE geoportal. Metadata need to be pushed from the first to the second)
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/53038426/5a7e7a9e-d93d-43fb-a5f4-48b4ab826bda)

But I don't see the publication date, nor the metadata, being upgraded on https://inspire-geoportal.ec.europa.eu/results.html?country=lu&view=details&theme=none.

Currently we plan to use this to investigate linkage checking issue, as the functionality won't be delivered in the harvest console for this R&M as I understood.

Thx for your help.

**Comment by jescriu** [comment]
Dear @benoitregamey and @MatAlps,

As explained in the [73 INSPIRE MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/73rd+MIG-T+meeting+2023-02-17) - and subsequent MIG-T Meetings - the results obtained through harvesting using the [revamped INSPIRE Geoportal GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork) (system used for the Monitoring and Reporting 2022) are still not available under the [INSPIRE Geoportal domain](https://inspire-geoportal.ec.europa.eu/), only through the own GeoNetwork console.

When the rollout of the revamped INSPIRE Geoportal is taking place, which will hopefully happen by the beginning of October 2023, the situation will be normalised and the results will become available through the INSPIRE Geoportal domain.

We will keep you posted on the progress.

Excuses for any inconveniences caused (and for the delay in replying).

**Comment by trodin** [comment]
Hello,

Any news on this issue? Now we are in the middle of October?

Regards,
Tanja
