### ISSUE TITLE
FI: harvesting

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#158]
Hi, 

We've been trying to harvest the Finnish CSW service https://www.paikkatietohakemisto.fi/geonetwork/srv/fin/csw this morning, approximately between 9-10 AM CET. The harvest attempts were not successful. We tried to drop error management test, but it didn't help. We also checked the logs of our service, but got no help from there. The harvesting attempts just stop without any information on why. Could you check the log files on your side they give any clues on why metadata isn't rethrieved?

Thanks in advance.

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
As notified to RO [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/156#issuecomment-1715498292), we are aware of this issue and asked GeoCat for action.
Will keep you posted.

**Comment by hallinpihlatie** [comment]
Thanks @jescriu

**Comment by hallinpihlatie** [comment]
Dear @jescriu, I'd like to use the INSPRIE geoportal sandbox. How do I get access to it?

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
I sent you the the link to the sandbox by email.
Proceed to close this issue, which was already resolved.
