### ISSUE TITLE
INSPIRE Contact list

### ISSUE THREAD

**Issue by justinelliotmeyers** [INSPIRE-MIF/helpdesk-geoportal#161]
is there a contact list anywhere for individual countries/ themes?
Germany - addresses
Germany - buildings
etc

For all countries and all themes?
Thanks
Justin

**Comment by jescriu** [comment]
Dear @justinelliotmeyers,
You should use the INSPIRE themes browsing, where you can select any theme of your interest and afterwards select any of the countries: 
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datathemes
