### ISSUE TITLE
Inspire geoprotal sandbox

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#163]
Hello,

Now we are testing out new Geoportal version - is there any possibility to get access to Inspire Geoportal sandbox, where we can test harvest from out Geoportal to Inspire Geoportal?

**Comment by jescriu** [comment]
Dear @vicehovskis,
As announced two weeks ago in the discussion https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/160, the GeoNetwork harvesting console and the MS / Countries users have been disabled to perform the necessary security assessment as part of the INSPIRE Geoportal rollout.

Please let me know your country and I will contact you once the console is accessible again, to perform the tests.

**Comment by vicehovskis** [comment]
@jescriu  Latvia 

Is there a sandbox (test) available, where we can test harvesting process? Is there any Geoportal test/sandbox?

**Comment by jescriu** [comment]
Apologies. Not at the moment.
However, our ICT team is working to provide a clone of the GeoNetwork console to at least consult the latest results during this transition period (including security assessment + time necesarry for the rollout), in which the original GeoNeowork harvesting console cannot be accessed.
I will keep you posted on this possibility.

**Comment by vicehovskis** [comment]
Hello, are there any updates about harvest console new version and sandbox enviroment for harvest testing? We have new solution and we need to test if harvesting will work correctly with new endpoints.

**Comment by jescriu** [comment]
Dear @vicehovskis,
You should have received an email with the details to access the sandbox console.
Please send me an email I will provide you with the details to access it, and the result obtained until the date in production.

**Comment by jescriu** [comment]
Thank you @vicehovskis.
Email received. I just send you the information.
