### ISSUE TITLE
How to push new metadata to Inspire geoprotal 

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#164]
Where we can find any insrtuctions for the new harvest console? We can`t push our metadata now.

**Comment by MarcoMinghini** [comment]
Dear @vicehovskis, 
as communicated two weeks ago in the discussion [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/160), the GeoNetwork harvesting console and the MS / countries users have been disabled to perform the necessary security assessment as part of the INSPIRE Geoportal rollout.  

To receive automated notifications about similar announcements in the future, we suggest you to watch the repository: you can do that using the button Watch located in the upper right part of the repository.
