### ISSUE TITLE
Geonetwork harvesting console disabled in view of the INSPIRE Geoportal rollout

### ISSUE THREAD

**Issue by jescriu** [INSPIRE-MIF/helpdesk-geoportal#165]
Dear Community,

As anticipated on 23 October in [this discussion thread](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/160), the GeoNetwork harvesting console and the MS / countries users have been disabled to perform the necessary security assessment as part of the INSPIRE Geoportal rollout.

Please, to receive automated notifications about similar announcements in the future, we suggest you to watch the repository: you can do that using the button Watch located in the upper right part of the repository.

**Comment by jescriu** [comment]
Dear users,
As [announced here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/167) we are approaching the final phase of the rollout of the revamped GeoNetwork-based INSPIRE Geoportal in the next days.
Some days of malfunctioning of the Geoportal, or even temporal availability of the site, might be expected.
Thank you your patience.

**Comment by jrc-inspire** [comment]
The revamped INSPIRE Geoportal was successfully launched on 24 November 2023, based on GeoNetwork Open Source version 4.2.6
