### ISSUE TITLE
LPIS map on geoportal

### ISSUE THREAD

**Issue by MatAlps** [INSPIRE-MIF/helpdesk-geoportal#168]
Dear helpdesk,

We noticed the absence of Luxembourg on the following map : https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=lpis

Although we do have the data : https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/cf117899-09ec-4d0e-b25e-5558a9bb05f9

What are the criteria used to select the metadata feeding the LPIS page of the geoportal?
I suspect we are missing one tag or something?

Thx for your help!

**Comment by MatAlps** [comment]
Sorry to come back to you so soon, we need to give a feedback about this situation on the 6th of December, if you have the chance to have a look at it and come back to us by then it would great!!

Thx in advance,

Mathieu

**Comment by MatAlps** [comment]
@MarcoMinghini 

Thx for the first inputs during the MIG-T.
Please find here extra information from our side:

LU : LPIS 2021 (https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/62bfac97-f98d-48cf-811d-508173460338) has the following keyword in MD:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/53038426/3b28fa56-7f50-4343-8972-a76273725c12)
It does not show on the EU geoportal.

BE (showing on EU geoportal) : https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/1aecd74a-e1a7-498c-b749-f0a256ba2834
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/53038426/c9aabb20-1abf-49af-92cf-46b7d2120b8c)

**Comment by MatAlps** [comment]
Hello, do you have an update regarding this?
Thx!

**Comment by jescriu** [comment]
Dear @MatAlps,
We are in the process of resolving an issue in the process of publication of the harvesting results in the INSPIRE Geoportal, which might be also interfering in the current figures of HVDs filtering (including IACS data).
Once totally resolved the former issue, we will analyse if the IACS data filtering is correctly functioning (or not).
Thank you for your patience.

**Comment by jescriu** [comment]
Dear @MatAlps,

The HVDs viewer only filters metadata that is following the '[Technical guidelines on IACS spatial data sharing. Part 1 - Data discovery](https://publications.jrc.ec.europa.eu/repository/handle/JRC121450)' - Could you confirm that the tagging procedure used for the two metadata records reported above is conformant to this TG? 

You can also test your IACS metadata resources with the ad-hoc test which is available in the INSPIRE Reference Validator, as illustrated in the image below.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/b205a6c1-9ba6-46e2-90aa-d6f90c28b480)

There is also an example available [here](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/IACS_dataset_metadata_2.0_example.xml).

Let me know if this helps. We are still investigating the publication issue described in my previous post.

**Comment by antjacques** [comment]
Hello,

We have fixed our metadata records (Luxembourg) that weren't matching IACS technical guidelines. They are now passing the conformance class 2c validation.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/154505292/ef4bac8c-ca9e-4ea9-9e0c-80aa5c05ffaa)

Now, how can we check if everything works fine on [Geoportal](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=lpis)? We cannot push harvesting results anymore so is there a way for us (or you) to verify that it is fixed visually? Or do we have to wait final monitoring & reporting?

Many thanks

**Comment by antjacques** [comment]
Dear helpdesk,

Do you have any news on this matter?
We saw that some countries (such as Slovakia) now appear on the LPIS map but still not Luxembourg even if our data is now conform. 

Thanks

**Comment by jescriu** [comment]
Dear @MatAlps and @antjacques,

Four weeks ago a new contract was signed with Geocat for covering specific needs and improvements in the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu/).

As part of this new collaboration with GeoCat, we are investigating the reason why some IACS datasets are not properly referenced in the High-Value Datasets viewer.

The issue seems to be in the query against the ElasticSearch index that the INSPIRE Geoportal user interface currently implements. A fix for this issue should be soon available.

**Comment by jescriu** [comment]
This issue will be solved as part of #172.
Please, refer to that issue for further follow-up.
