### ISSUE TITLE
Harvesting error

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-geoportal#17]
Dear @dartasensi,

At the moment I'm not able to harvest the Dutch endpoint.
The steps;
1. In the harvesting dashboard schedule a new harvest
2. email received [INSPIRE Geoportal - Harvest console] New session request accepted
3. within a few minutes an error message appear in the harvesting dashboard, see prinstcreen

![image](https://user-images.githubusercontent.com/10847083/106754548-650f6000-662d-11eb-9d97-3c61aadf9805.png)

Can you provide more information on what is causing the harvesting error?

Thanks in advance and kind regards!

**Comment by idevisser** [comment]
Dear @dartasensi,

After reasearch on our site we have some more additional info;
Since we hardly see any traffic on the inspire endpoint, we have a suspicion that the harvest is not reaching the server.
This could have to do with the certificate, the Dutch root certificate was updated at the end of last year, due to a security problem, this certificate has also been rolled out on the NGR server. Java processes that access an url with that certificate sometimes crash because java does not trust the certificate, in that case the JRC administrator has to install the certificate manually on the server)

Can you check of this is the issue?

Thanks in advance!

**Comment by dartasensi** [comment]
Dear @idevisser,

I'm checking again, and it seems that the registered NL endpoint (the same URL used for the MR2020 reporting) is not reachable at all.
Could you please verify the status of the service? Otherwise, could you please share (or send with an email to our support) the new updated URL (and relative OGC filter, if still needed)?
I will then update the endpoint configuration and start some test harvest with the HarvestConsole.

Thanks, 
Davide

**Comment by idevisser** [comment]
Dear @dartasensi,

There have been some adjustments on our side, cousing the harvesting problem. Can you please change the NL endpoint in 
https://www.nationaalgeoregister.nl/geonetwork/srv/dut/csw-inspire
 
Thanks Ine

**Comment by dartasensi** [comment]
Dear @idevisser 

the change has been applied. I assume the previous OGC Filter remains still valid and applicable. (I can post it here if you need)
I've just started a new harvest on your behalf to monitor the progress.

KR,
Davide

**Comment by dartasensi** [comment]
Dear @idevisser 

the harvest is available in the HarvestConsole. It completed successfully, and it seems fine on our side.
If you agree, we can close this issue.

Regards,
Davide

**Comment by idevisser** [comment]
Dear @dartasensi,

The harvest results are what we expected, thank you, I will close this issue.

Best regards Ine
