### ISSUE TITLE
Issue with harvesting bilingual dataset metadata

### ISSUE THREAD

**Issue by matejsot** [INSPIRE-MIF/helpdesk-geoportal#171]
After reviewing the results of the harvesting process, where the results for Slovenia are not satisfactory, we have identified that the issue lies in bilingual metadata (Slovenian and English), where the metadata is transferred but no title is written for them (see the picture below). To confirm that this is the problem, we changed one of the metadata to monolingual and reran the harvest, thus confirming that indeed this is the issue, as the metadata appeared after the change. The problem only occurs with datasets metadata, while metadata for services is transferred successfully (including bilingual ones).

Screenshot is attached.
![harvesting issue](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/60505136/30085f7e-8a04-4adf-a6ce-5d264d99cd0a)

Please provide assistance on how to proceed, and let us know if you can help us resolve this issue.

Best regards.
Matej Sotlar
Slovenia

**Comment by jescriu** [comment]
Dear @matejsot,
This is not an INSPIRE-related issue, but a known indexing issue in GeoNetwork for which fixes were already provided in due time by such commnunity:
https://sourceforge.net/p/geonetwork/mailman/message/35920768/

Please ask your contractor to amend the problem on your side. Obviously the harvesting console cannot work with metadata having indexing issues.
