### ISSUE TITLE
IACS/GSAA metadatapost validates correctly, but is not shown in the Geoportal overview

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-geoportal#172]
The following metadatapost from the Swedish Board of Agriculture is tagged as IACS/GSAA but it does not appear so in the Geoportal nor it is shown in the map overview as GSAA. The post passes validation correctly (validator version 2023.3).  Why?

See below for details. 

Thanks in advance

Hernán

Link to metadatapost as stored in the Geoportal catalogue:

[https://inspire-geoportal.ec.europa.eu/srv/eng/csw?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&id=e317c48b-2a5e-4590-a2d5-c79900541d13](https://inspire-geoportal.ec.europa.eu/srv/eng/csw?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&id=e317c48b-2a5e-4590-a2d5-c79900541d13)

Screendump of the IACS/GSAA map view, showing no post belonging to Sweden (there should be two):

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/51515911/d0031cfb-f2af-4751-afa9-e2bde93b0176)
[https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=gsaa](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=gsaa)

Screendump of the validator results of the same post as linked above:

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/51515911/2513b23b-c80f-44fa-a9ca-752b409fbeee)

**Comment by jescriu** [comment]
Dear @dhdeangelis,
We are in the process of resolving an issue in the process of publication of the harvesting results in the INSPIRE Geoportal, which might be also interfering in the current figures of HVDs filtering (including IACS data).
Once totally resolved the former issue, we will analyse if the IACS data filtering is correctly functioning (or not).
Thank you for your patience.

**Comment by jescriu** [comment]
Dear @dhdeangelis,

The HVDs viewer only filters metadata that is following the '[Technical guidelines on IACS spatial data sharing. Part 1 - Data discovery](https://publications.jrc.ec.europa.eu/repository/handle/JRC121450)' - Could you confirm that the tagging procedure used for the two metadata records reported above is conformant to this TG? 

You can also test your IACS metadata resources with the ad-hoc test which is available in the INSPIRE Reference Validator, as illustrated in the image below.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/b205a6c1-9ba6-46e2-90aa-d6f90c28b480)

There is also an example available [here](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/IACS_dataset_metadata_2.0_example.xml).

Let me know if this helps. We are still investigating a publication issue in the INSPIRE Geoportal, which might be interfering as well.

**Comment by dhdeangelis** [comment]
@jescriu as far as we understand, the Swedish implementation is conformant with the IACS TG. The metadata in question also passes the test for Conformance Class 2c, as shown in my original post above.

**Comment by jescriu** [comment]
OK, @dhdeangelis. Thank you for the confirmation.
It could be related to GeoNetwork reindexing issues. We are investigating it. 
Keep you posted.

**Comment by dhdeangelis** [comment]
Any news on this issue?

**Comment by jescriu** [comment]
Dear @dhdeangelis,
The records is correctly available in the Geoportal frontend:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/8ce9226a-232b-44fb-b000-bb2c9e9c8903)

I guess the reason for not getting it in the HVD IACS viewer is related to an unexpected encoding of the necessary keywords.
I will check as soon as I have a chance.

**Comment by dhdeangelis** [comment]
Thank you @jescriu , also grateful for any feedback you could provide on what that unexpected encoding may be so we can correct it.

**Comment by dhdeangelis** [comment]
We have been thinking about this issue.  @jescriu we wonder if the "unexpected encoding " you mention could be related to our use of Swedish words instead of English ones as values in the text:

`<gmd:keyword>
	<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/IACSData/gsaa">GEOSPATIALA STÖDSYSTEMET</gmx:Anchor>
</gmd:keyword>`

`<gmd:keyword>
	<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/IACSData/iacs">IAKS</gmx:Anchor>
</gmd:keyword>`

Is it necessary för Geoportal that these words are in English? Shouldn't the use of the right entry in the registry via the xlink:href attribute in the Anchor be sufficient, as it is for the validator?

Thanks in advance!

**Comment by jescriu** [comment]
Dear @dhdeangelis,

First of all, apologies for the delay. I have been checking this issue a couple of times, but never had time enough to arrive to a conclusion.

Good thinking about the IACS codelist. It could be the case. This is something we can test in the Geoportal. 

Unfortunately now the INSPIRE Registry is re-caching contents and I cannot check what is the status of the IACS metadata codelist in Swedish.

Let's test it next week.

**Comment by antjacques** [comment]
Hello, 

This issue might be linked to the one Luxembourg is experiencing: https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/168 

Our data (GSAA and LPIS) are fully conformant as well, it looks like they are harvested correctly:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/154505292/a681c8c9-9b2c-4608-ae55-942a98a0c822)

However we do not appear on the map, just like Sweden. 
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/154505292/410b912f-9851-4f72-9019-be4491aa5965)

Notice that we encode the keywords in English... Some cross check on the metadata records of Sweden and Luxembourg might help to identify the blocker?

**Comment by jescriu** [comment]
For sure @antjacques

**Comment by dhdeangelis** [comment]
I have now manually checked our metadata and see that the links to the Inspire registry that we use are defined in Swedish and also active:

IAKS
http://inspire.ec.europa.eu/metadata-codelist/IACSData/iacs

GEOSPATIALA STÖDSYSTEMET
http://inspire.ec.europa.eu/metadata-codelist/IACSData/gsaa

We do not see any obvious errors in our metadata. We are therefore inclined to believe that there may be some limitation in the Inspire Geoportal in this regard. In any case we will of course be happy to know about any potential issue you may find in our metadata that we can address.

**Comment by jescriu** [comment]
Dear @dhdeangelis and @antjacques,

Four weeks ago a new contract was signed with Geocat for covering specific needs and improvements in the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu/).

As part of this new collaboration with GeoCat, we are investigating the reason why some IACS datasets are not properly referenced in the High-Value Datasets viewer.

The issue seems to be in the query against the ElasticSearch index that the INSPIRE Geoportal user interface currently implements. A fix for this issue should be soon available.

**Comment by dhdeangelis** [comment]
Thank you for the update, @jescriu . We are looking forward to a solution for this. Please contact us in case you discover issues that must be solved on our side.

**Comment by geoportallux** [comment]
Hi, unfortunately Luxembourg is still missing on this listing: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=lpis

Have you found an explanation in the meantime and could you please tell us what to do?

**Comment by jescriu** [comment]
Dear @geoportallux, @dhdeangelis, 

We need to test and push to the INSPIRE Geoportal frontend server a modification of the queries getting the indicators for LPIS and GSAA datasets from the GeoNetwork Elastic Search, which should resolve the issue. 

On the last weeks we have prioritised the work for resolving the following issues: 

1. Publication of harvesting results in the frontend, which I am expecting that will be resolved this week - See #190;
2. Indexation of INSPIRE themes - See #170.

Starting today, I will test these IACS data related HVD queries, and will plan the update of the Geoportal user interface (UI) including also other necessary changes to the UIwhich are in the pipeline.

Apologies for the delay.

**Comment by jescriu** [comment]
Dear @geoportallux, @dhdeangelis,

Our ICT team will start implementing and testing the necesesary fixes in a INS-GPT frontend staging instance next week.

I will keep you posted on progress, especially when the fixes become available in production.

**Comment by antjacques** [comment]
Hello @jescriu 

Didn't you already implement a fix? We noticed on 22nd July that Luxembourg was appearing on LPIS and GSAA maps so we thought it was your doing.

![image](https://github.com/user-attachments/assets/da353aa6-a841-4ffd-a11a-727ee8894261)

**Comment by jescriu** [comment]
Dear @antjacques, 
Indeed we implemented in July a fix of the GeoNetwork indexing files (See https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/170#issuecomment-2213269594), which was affecting the indicators for INSPIRE themes and probably also affecting the appearance of LPIS and GSAA for your endpoint.
The new fix on LPIS and GSAA should not affect your current results, but only improve the agricultural data indicators for some Member States / EFTA countries that are currently providing such kind of datasets.

**Comment by jescriu** [comment]
Dear @dhdeangelis, @geoportallux, @antjacques,

The fixes for Agricultural High-Value Dataset views (LPIS and GSAA) are already available in the INSPIRE Geoportal frontend:
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=lpis
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=gsaa
The corresponding indicators slightly improved for your respective conuntries.

Please, verify that the fixes satisfy your expectations and re-open this issue in case of further concerns.
