### ISSUE TITLE
Access to the INSPIRE monitoring indicators overview and MS details

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#174]
Dear INSPIRE team,

where we could find the results from the past INSPIRE monitoring indicators overviews across the Europe previously available on this urls (e.g. for 2022) @ https://inspire-geoportal.ec.europa.eu/mr2022.html 
![obrázok](https://github.com/INSPIRE-MIF/helpdesk/assets/6195936/c3d77219-2349-494c-bb92-a9565a61c473)

Hyperlinks are redirected back to the landing page of [New INSPIRE knowledge base](https://knowledge-base.inspire.ec.europa.eu/index_en)

Similarly we can not anymore access the Country overviews, (e.g. for SK from 2019) @ https://inspire-geoportal.ec.europa.eu/mr2019_details.html?country=sk

![obrázok](https://github.com/INSPIRE-MIF/helpdesk/assets/6195936/2c9e0a86-b8e0-416b-9fba-7d0191fe7a0e)

Is there an chance to make these back available?

This information, (despite the changes in methodologies in past) is important in order to document maturation of the infrastructures across the time.

We have spotted this new place for INSPIRE monitoring https://inspire-mif.github.io/INSPIRE-in-your-Country/ but this information is missing.

Thanks, Martin

**Comment by MarcoMinghini** [comment]
Dear @MartinTuchyna, 
thanks for flagging this issue. Some pages published in the previous Geoportal server became not available after the rollout of the new Geoportal. We plan to make all the M&R pages for the past years back online (including the main page and all the country-specific pages), I will keep you informed as soon as this happens. 
Kind regards.

**Comment by MartinTuchyna** [comment]
Dear @MarcoMinghini 

Great, thanks in advance for further updates.

**Comment by jescriu** [comment]
@MartinTuchyna - While we are working to restore the Monitoring & Reporting pages from previous years, you can temporarily access the results from 2022 using this link:
https://inspire-geoportal.ec.europa.eu/catalog/views/inspireportal/monitoringreporting/site/mr2022.html

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

The publication of the INSPIRE Monitoring results for previous years (back from 2022) got a lower priority with respect other INSPIRE Geoportal-related tasks.

I will check tomorrow the status of this task with our ICT team and let you know.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

The results are published again online:
https://inspire-geoportal.ec.europa.eu/mr/mr2023.html
https://inspire-geoportal.ec.europa.eu/mr/mr2022.html
https://inspire-geoportal.ec.europa.eu/mr/mr2021.html 
https://inspire-geoportal.ec.europa.eu/mr/mr2020.html
https://inspire-geoportal.ec.europa.eu/mr/mr2019.html
