### ISSUE TITLE
Criterium for GSAA and LPIS INSPIRE EC Geoportal HVD filter

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#175]
Dear INSPIRE team,

in connection to the filterring of the Metadata records for the Agricultural parcels sub categories:

- GSSA: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=gsaa
- LPIS: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=IACSOverview&iacs=lpis 

what is the criterium, metadata are selected here?

Thanks, Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

The tagging procedure for the different types of IACS data is described in the '[Technical guidelines on IACS spatial data sharing. Part 1 - Data discovery](https://publications.jrc.ec.europa.eu/repository/handle/JRC121450)'.

For testing the corresponding metadata there is an ad-hoc test available in the INSPIRE Reference Validator, as illustrated in the image below.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/6a5bb11f-628f-44fd-b53e-5fdb74f93e14)

There is also an example available [here](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/IACS_dataset_metadata_2.0_example.xml).

Hope this helps.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 

thank you for the info. We will check it in order to see, how and where to improve metadata for relevant datasets to be properly filtered on EC INSPIR Geoportal.
