### ISSUE TITLE
Login using ECAS

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-geoportal#176]
Hi,

ECAS is used by many EC applications to identify and authenticate users.

I suggest to implement it in the GeoPortal harvesting console instead of the username/password that is currently used. 

It would ease the access to those that already have an ECAS account and increase the security using the Multi-FactorAuthentication (MFA) that ECAS supports.

**Comment by jescriu** [comment]
Dear @fdumortier,

The implementation of EU-Login (formerly know as ECAS) is planned and in the pipeline of INSPIRE Geoportal implementations foreseen for the coming months. Ww will keep the community posted on this matter.

Thank you for your suggeestion and kind contribution.
