### ISSUE TITLE
Sandbox interface : how to list datasets/series unavailable through view and/or download services ?

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-geoportal#177]
Good evening, I haven't worked out how to use the sandbox to obtain a list of datasets or series that are not accessible via a viewing and/or downloading service. Intuitively, I thought that the button shown in the attached screenshot should have had this effect, but it also displays all the services beside data that are not downloadable, and not just the latter.
![inspire-geoportal](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/28805451/909920eb-71b1-4ac5-9ce6-bdbcc217e4bb)

**Comment by jescriu** [comment]
Dear @fdumortier 

Meanwhile it is clarified the link-cheking approach in GeoNetwork, you can use the accessibility tools that JRC provided and used for the calculation of the related indicators in the 2023 Monitoring process:
https://github.com/INSPIRE-MIF/mr-tools/tree/main/dataset-accessibility/link-checker_script

Please, refer to #128 for following up the same topic.
