### ISSUE TITLE
Wanted: Logo for the INSPIRE Geoportal

### ISSUE THREAD

**Issue by GDIAnja** [INSPIRE-MIF/helpdesk-geoportal#180]
As a regional office for spatial data infrastructure we have a website with a geoportal for Lower Saxony (north-western Germany). Every now an then we would introduce our local data-holding authorities to European data. Many of our local data-holding authorities are curious about when their data will arrive in the INSPIRE portal. Metadata is not the thing most people like very much. But if they have already made the effort to create metadata, then they also want to make sure that Europe takes notice of it. 

This is why we would like to have a hyperlink to INSPIRE Geoportal.  Off course, we can easily do this. But there is a major problem:

The internet is filled with colorful picutuers. Nobody would even notice a simple text-based hyperlink. We need an official logo for INSPIRE geoportal. This would help people to understand, Europe is just around the corner and all the efforts is worth it.

Well, let´s see what happens :-) and thank you for reading, even this is just a matter of design.

**Comment by jescriu** [comment]
Dear @GDIAnja,

Thank you for your proposal.

Unfortunately it is not in hand of the JRC (Technical coordinators of INSPIRE) to design and create a new logo for the INSPIRE Geoportal. 

For this reason we suggest you to reuse the new INSPIRE logo, which I attach to this post in .PNG format. 
![LOGO-WEB](https://github.com/user-attachments/assets/e170dee2-285d-4b91-9688-fc1e7bf1c909)

Hope this helps.
