### ISSUE TITLE
Possibility to transform from ISO19115-3 in harvester

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-geoportal#182]
We want to upgrade Geonetwork and at the same time switch from ISO 19139 to ISO 19115-3 in the CSW endpoint. Will this be a problem in relation to harvesting metadata for INSPIRE Geoportal (Geonetwork)? 

The reason I ask is that I miss the possibility of using Geonetwork's XLST in the configuration of the harvester (in the sandbox instance).

In DK's harvester (OGC CSW 2.0.2 (remote harvester)), you cannot specify that metadata must be transformed from ISO 19115-3. 

However, you can if you use the harvester (OGC CSW 2.0.2):
![billede](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/34093019/537c6b8f-813b-4663-a669-0c279e7a0b66)

 Will it be possible to use this harvester and thus be able to transform metadata from 19115-3? Or do we have to stay with ISO19139 in our national data catalogue? 

Thx,
Lars

**Comment by fxprunayre** [comment]
The INSPIRE Geoportal query your catalogue with a CSW GetRecords operation with an `outputSchema` set to `http://www.isotc211.org/2005/gmd` so your catalogue will do the conversion from ISO19115-3 to ISO19139 when needed and send the response to the Geoportal.

https://metawal.wallonie.be/ contains only ISO19115-3 records and it works fine.

**Comment by laers** [comment]
Thanks Francois! Glad to hear that we can stick with ISO 19115-3.

**Comment by jescriu** [comment]
Thanks @fxprunayre for answering @laers.

@laers  - Feel free to re-open this issues in case of difficulties with this tranformation on the CSW.
