### ISSUE TITLE
To show OGC API Features services

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-geoportal#183]
Dear team,
As the OGC API Features is an endorsed good practice and its implementation seems to be rising, we propose to include it on the INSPIRE Geoportal.
All the INSPIRE datasets of Catalonia are provided through this standard (among others) and a specific metadata for the service is catalogued: https://www.idee.es/csw-codsi-idee/srv/spa/catalog.search#/metadata/inspire-ogc-api-features
Thank you

**Comment by jescriu** [comment]
Dear @danicgc,

Happy to see some progress in Catalunya after a long implementation.

As announced in the [76 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30) a procurement to embed the OGC API Features INSPIRE good practice in GeoNetwork was launched in September 2023, which unfortunately got deserted.

We are currently exploring other options to tackle this implementation in 2024.

Please get in contact with your national representative to follow up on this matter.
