### ISSUE TITLE
Results of Monitoring 2019, 2020 and 2021 not accessible

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/helpdesk-geoportal#187]
Thank you for publishing the results of the INSPIRE Monitoring 2023 at https://inspire-geoportal.ec.europa.eu/catalog/views/inspireportal/monitoringreporting/site/mr2023.html.

The results of the 2022 monitoring can also be found by adapting the URL: https://inspire-geoportal.ec.europa.eu/catalog/views/inspireportal/monitoringreporting/site/mr2022.html.

However, the results from previous years cannot be accessed in this way. Instead, an HTTP status 404 is reported.

Could you please also provide the results from 2019, 2020 and 2021?

**Comment by fabiovinci** [comment]
Dear @hogredan,

I transferred the issue to the Geoportal helpdesk, and the Geoportal team will manage the issue.

**Comment by jescriu** [comment]
Dear @hogredan,
Thanks for your post.
We known about this situation, which derives from the recent launch of the revamped INSPIRE Geoportal.
Our ICT Teams is working to provide an approapriate repository to host the 'static' results not only for 2023 and 2022 but also from previous INSPIRE Monitoring and Reporting processes.
We will update you asap when the solution is ready. Apologies for the temporal inconvenience.

**Comment by fdumortier** [comment]
Dear Jordi,

Currently, URL https://inspire-geoportal.ec.europa.eu/catalog/views/inspireportal/monitoringreporting/site/mr2023.html returns an 404 error code.

Kind regards,

François

**Comment by jescriu** [comment]
Dear @fdumortier,
Thanks for spotting. There was an issue with the server hosting the MR 2023 page.
Our ICT team is working to solve the situation as soon as possible. 
Will keep you posted.

**Comment by jescriu** [comment]
Dear @fdumortier,
The Monitoring and Reporting 2023 page is already available.
Apologies for the temporal unavailability.
