### ISSUE TITLE
Access to Monitoring and Reporting 2023 – Dashboard

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#189]
Dear INSPIRE team,

could you please check the access to the Monitoring and Reporting 2023 – Dashboard via 

https://inspire-geoportal.ec.europa.eu/catalog/views/inspireportal/monitoringreporting/site/mr2023.html

Current response is:

HTTP Status 404 – Not Found

Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.98

Thanks in advance, 

Best regards, 

Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
Please take a look at https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/187#issuecomment-1968526975 
Apologies for the inconvenience.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
The Monitoring and Reporting 2023 page is already available.
Apologies for the temporal unavailability.

**Comment by MartinTuchyna** [comment]
Great, thanks @jescriu
