### ISSUE TITLE
Priority Dataset Viewer: not all legislation shown in the Environmental Domain Water

### ISSUE THREAD

**Issue by wboersma** [INSPIRE-MIF/helpdesk-geoportal#19]
Hello,

In the Geoportal Priority Dataset Viewer, something goes wrong with the viewer of the Environmental Domain Water. Not all datasets can be found in the Environmental Domain Water overview. But the datasets are available if you look through the legislative overview.

Two examples:
- Legislation:  Directive 2007/60/EC (https://inspire-geoportal.ec.europa.eu/results.html?country=nl&view=details&legislation=dir-2007-60&envDomain=none). Only one of the datasets (Overstromingsgevaarkaarten) is shown under the Environmental Domain Water (https://inspire-geoportal.ec.europa.eu/results.html?country=nl&view=details&envDomain=water). The other available dataset (https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-8c93a17a-05f4-11e1-b7de-52540004b857_20210210-104802%2Fservices%2F1%2FPullResults%2F81-100%2Fdatasets%2F5&expandedSection=metadata) isn't shown at the Environmental Domain Water overview.
- The same applies to the Legislation:  Directive 98/83/EC (https://inspire-geoportal.ec.europa.eu/results.html?country=nl&view=details&legislation=dir-1998-83&envDomain=none). A dataset is available here (Kwaliteit van drinkwater in Nederland (2012)), but the dataset is not available in the Environmental Domain Water overview.

Can you check and adjust this. This may also take place with other themes and legislation.

Best regards, Wideke

**Comment by dartasensi** [comment]
Dear Wideke,

you are right. I checked and found the bugs you mentioned, and I'm working on a fix right now.
I will keep you posted.

Kind regards,
Davide

**Comment by dartasensi** [comment]
Dear @wboersma,

apologies for the late reply.
I just want to let you know that, while I was working on this fix, I found other inherited issues that require a further analysis and review of our internal workflow, prior continuing to solve this task.
Therefore, I would put this on-hold while we internally solve and strengthen the current approach.

Thanks for your patience and understanding.

**Comment by wboersma** [comment]
Dear @dartasensi,

Thank you for the feedback. Can you perhaps indicate a time frame when this bug is resolved.

Best regards, Wideke

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
However, we have taken note of the potential issue in the current Geoportal and will do our best for addressing it in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Your request will be potentially considered in the evolution of the revamped GeoNetwork-based INSPIRE Geoportal.

Excuses for any inconvenience caused.
