### ISSUE TITLE
Reference validator is not accessible from the INSPIRE Geoportal home page

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk-geoportal#191]
Dear INSPIRE team,

we noticed that it is not possible to access the Reference validator from the INSPIRE Geoportal home page: 
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/home

Best regards

Juliana

**Comment by fabiovinci** [comment]
Dear @JulianaKar,

thank you for reporting the problem, I will transfer the issue to the Geoportal helpdesk, so that the team can fix it.

**Comment by MarcoMinghini** [comment]
Dear @JulianaKar, thank you for reporting the issue. We will inform you once the link is fixed.

**Comment by MarcoMinghini** [comment]
Dear @JulianaKar, the link has been fixed.
