### ISSUE TITLE
Find your scope app 

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#194]
Dear INSPIRE Team,

could you please make available [Find your scope application](https://wayback.archive-it.org/12090/20230902103304/https://inspire-regadmin.jrc.ec.europa.eu/dataspecification/FindYourScope.action) also via [INSPIRE Knowledge Base](https://knowledge-base.inspire.ec.europa.eu/index_en) website?

Thanks, Martin

**Comment by jescriu** [comment]
Dear Martin,
As stated in [this discussion thread in the INSPIRE helpdesk](https://github.com/INSPIRE-MIF/helpdesk/discussions/190#discussioncomment-8926100) the 'Find your scope' tool was recently decommissioned.
Feel free to contact us by email in case you need more information on this matter.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 

thanks for an update.

That is really pitty, as the application was very usefull and will be missing.

m.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
Feel free to raise your concerns to the INSPIRE Team (via email) and/or in the MIG-T context.
All the best.

**Comment by MarcoMinghini** [comment]
Dear @MartinTuchyna, 
in addition, please consider that:
- the application was based on outdated technology, and 
- it would make little sense to maintain it considering the many changes occurred, and planned to occur, to TGs and schemas

**Comment by MartinTuchyna** [comment]
@jescriu , @MarcoMinghini 

sure, if I am the only one missing this app I do respect it does not make sense to invest in furhter maintenance and development.

Some analysis, can be done on the level of DS or AS gitlab projects, but the decomissioned app provided more user friendly  GUI for interaction with domain experts.
