### ISSUE TITLE
Harvest Austrian CSW

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#197]
Hi,
could you please trigger a Harvesting for the Austrian Endpoint and publish the result?
https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&request=GetCapabilities&version=2.0.2

Thanks,
Manuel

**Comment by jescriu** [comment]
Dear @manilly ,

I successfully harvested the AT endpoint today with the following results:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/152daeea-37a3-405f-9cd7-12d0b74446c7)

The publication of results, from the Internal production harvesting console to the External frontend server, will have to wait until the revision of the server architecture is finishing, as announced in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/download/attachments/127305972/MIG-T78_INSPIRE_Geoportal.pdf?version=1&modificationDate=1715932838836&api=v2).
