### ISSUE TITLE
Question about COMMISSION IMPLEMENTING REGULATION (EU) 2023/138

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#199]
Hello,

Developers have some questions about "COMMISSION IMPLEMENTING REGULATION (EU) 2023/138" 3. article -> 

Whats is the right way for implementing 2. and 3. points?

> 2. Those public sector bodies referred to in paragraph 1 shall set out and publish the terms of use of the API and the
> quality of service criteria on its performance, capacity and availability. The terms of use shall be available in a humanreadable and machine-readable format. Both the terms of use and the quality of service criteria shall be compatible with
> the arrangements for the re-use of high-value datasets laid down in accordance with Article 4.
> 
> 3. API terms of use shall be accompanied by API documentation in a Union or internationally recognised open, humanreadable and machine-readable format.

Is this a part of a metadata? Or what is the right way to provide this information with the service?

**Comment by vicehovskis** [comment]
Any comments about this question?

**Comment by jescriu** [comment]
Dear @vicehovskis,

First of all you have to license your High-Value Datasets (HVDs) according the requirements set in Article 4 of [Commission Implementing Regulation (EU) 2023/138](https://eur-lex.europa.eu/eli/reg_impl/2023/138/oj).

Of course you have to infom the dataset and API terms of use as part of the datasets and service metadata, respectively. This shall be done according the [INSPIRE Metadata Technical Guidelines](https://github.com/INSPIRE-MIF/technical-guidelines/tree/main/metadata/metadata-iso19139). 

However, I strongly suggest you to also share this information as part of API documentation, which you can deliver using Swagger. I leave you here some interesting links to deepen into this matter:
https://swagger.io/resources/articles/documenting-apis-with-swagger/
https://medium.com/swlh/restful-api-documentation-made-easy-with-swagger-and-openapi-6df7f26dcad

**Comment by jescriu** [comment]
After having passed a reasonable period for potential feedback, I proceed to close this is issue.
Feel free to reopen it in case of further questions on this matter.
