### ISSUE TITLE
Linking dataset to WFS service

### ISSUE THREAD

**Issue by pawelsoczewski** [INSPIRE-MIF/helpdesk-geoportal#2]
Dear Geoportal Helpdesk,

I unable to establish link between dataset metadata and its "direct-access" download services - WFS and SOS. The linking between pre-download ATOM and View WMS services works correctly.

The Resource linkages checker tool reports for WFS as shown below:

![Zrzut ekranu 2020-12-9 o 11 00 55](https://user-images.githubusercontent.com/44895671/101619232-49178580-3a13-11eb-82a8-f6056bfa16dd.png)

and INSPIRE Validator as shown below:

![Zrzut ekranu 2020-12-9 o 12 02 47](https://user-images.githubusercontent.com/44895671/101621824-8cbfbe80-3a16-11eb-9819-ae7d60a36e6a.png)

The content of dataset metadata, service metadata and service capabilities seems in accordance with TG metadata 2.0 and Linking guidance. See below:

**Resource identifier in  dataset metadata**
`<gmd:identifier>
<gmd:MD_Identifier>
<gmd:code>
<gco:CharacterString>http://inspire.gios.gov.pl/dataset/PL.ZIPOS.6327/monit-soil-chem</gco:CharacterString>
</gmd:code>
</gmd:MD_Identifier>
</gmd:identifier>`

**Linking to dataset from WFS metadata**
`<srv:operatesOn xlink:href="http://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;id=c146f55e-19cf-4ddb-98d0-85d06d35110c#monit-soil-chem"/>`

**Linking to dataset and metadata from WFS capabilities**
`<inspire_dls:SpatialDataSetIdentifier metadataURL="https://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;id=c146f55e-19cf-4ddb-98d0-85d06d35110c#monit-soil-chem">
					<inspire_common:Code>monit-soil-chem</inspire_common:Code>
					<inspire_common:Namespace>http://inspire.gios.gov.pl/dataset/PL.ZIPOS.6327</inspire_common:Namespace>
				</inspire_dls:SpatialDataSetIdentifier>`

`<FeatureType xmlns:ef="http://inspire.ec.europa.eu/schemas/ef/4.0">
			[...]
			<MetadataURL xlink:href="https://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;id=c146f55e-19cf-4ddb-98d0-85d06d35110c#monit-soil-chem"/>
		</FeatureType>`

**Linking to dataset and metadata from ATOM Feed**
`<inspire_dls:spatial_dataset_identifier_namespace>http://inspire.gios.gov.pl/dataset/PL.ZIPOS.6327</inspire_dls:spatial_dataset_identifier_namespace>
		<inspire_dls:spatial_dataset_identifier_code>monit-soil-chem</inspire_dls:spatial_dataset_identifier_code>
		<link href="https://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&request=GetRecordById&version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=c146f55e-19cf-4ddb-98d0-85d06d35110c#monit-soil-chem" rel="describedby" type="application/xml"/>`

**When I've changed Resource Id encoding in dataset metadata as below:** 
`<gmd:identifier>
						<gmd:RS_Identifier>
							<gmd:code>
								<gco:CharacterString>monit-soil-chem</gco:CharacterString>
							</gmd:code>
							<gmd:codeSpace>
								<gco:CharacterString>http://inspire.gios.gov.pl/dataset/PL.ZIPOS.6327</gco:CharacterString>
							</gmd:codeSpace>
						</gmd:RS_Identifier>
					</gmd:identifier>`

The Inspire Validator test passed but the Resource linkages checker still reports error :/

Here are links to problematic metadata and services:

- **dataset metadata**: http://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=c146f55e-19cf-4ddb-98d0-85d06d35110c

- **WFS metadata**: http://inspire.gios.gov.pl/geonetwork/srv/pol/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=c526d3af-90df-458f-8deb-83ca9ded952c

- **WFS Capabilities**: http://inspire.gios.gov.pl/wss/monit-soil-chem-ef/wfs?REQUEST=GetCapabilities&VERSION=2.0.0&SERVICE=wfs

- **ATOM Srervice**: http://inspire.gios.gov.pl/atom_web/atom/monit_soil_chem/

**Comment by ttsokolowski** [comment]
Dear Geoportal Helpdesk,
Can you please let us know what we should correct in our configurations?

Best regards,
Tomasz Sokolowski
Chief Inspectorate Of Environmental Protection

**Comment by df-git** [comment]
Dear Tomasz,
Thank you for your message.
Unfortunately, currently we do not have the capacity to respond to your question now, given that the agreed period for testing is  passed (https://inspire-geoportal.ec.europa.eu/mr2020_testing.html), and the actual deadline is tomorrow.

We suggest to check the document (https://inspire-geoportal.ec.europa.eu/files/INSPIRE_Geoportal_process_for_data-service_linking_v1.0.pdf) available in the Linkage checker page in order to understand how to correctly implement linkages.

In addition, you can also review the Technical Guidance for Download services (https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services).
 
Best regards,
Daniele on behalf of JRC INSPIRE Support team

**Comment by pawelsoczewski** [comment]
Dear Daniel,

My colleagues and I have spend a lots of time to test of different option of encoding linkages into metadata document and capabilities document. In the end we got success ... dataset is linked to the WFS in INSPIRE Geoportal when **added additional Resource Identifier encoding using RS_Identifier !!!**

**in dataset metadata**
<img width="995" alt="Zrzut ekranu 2020-12-15 o 20 51 28" src="https://user-images.githubusercontent.com/44895671/102265403-5c48ba80-3f17-11eb-8d1c-119b1cdd0552.png">

**in WFS capabilities**
<img width="1326" alt="Zrzut ekranu 2020-12-15 o 21 02 26" src="https://user-images.githubusercontent.com/44895671/102266520-dc235480-3f18-11eb-94c1-d713bdb99d21.png">

When Resource Identifier is encoded in dataset metadata only using MD_Identifier the linkage doesn't work. **Using of RS_Identifier element to encode Resource Identifier is removed by TG MD 2.0**.

The second issue is encoding of Resource Identifier in WFS capabilities. When is lack of _inspire_common:Namespace_ element INSPIRE Validator reports error of missing mandatory namespace of Resource Identifier.

It looks that INSPIRE Geoportal doesn't support correctly encoded linkages of metadata.

**Comment by dartasensi** [comment]
Dear @pawelsoczewski,

as you correctly stated, using RS_Identifier element has been removed with TG MD 2.0, and with the latest MR2020 report we have converged our efforts only toward TG MD v2.0 compliance. I think Geoportal will not extend the support on this RS_Identifier approach.

Kind regards,
Davide
