### ISSUE TITLE
Trigger a new harvesting for Brussels catalog

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-geoportal#200]
Hi,

Could you please trigger a Harvesting for the Brussels Endpoint and publish the result?
https://catalog.datastore.brussels/geonetwork/srv/eng/csw

Thanks,

François Du Mortier

**Comment by jescriu** [comment]
Dear @fdumortier  ,

I successfully harvested the BE-GEOBRU endpoint today with the following results:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/62b21388-aa43-4119-8622-e578ad3c7a6a)

The publication of results, from the Internal production harvesting console to the External frontend server, will have to wait until the revision of the server architecture is finishing, as announced in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/download/attachments/127305972/MIG-T78_INSPIRE_Geoportal.pdf?version=1&modificationDate=1715932838836&api=v2).

**Comment by fdumortier** [comment]
Thanks, Jordi. Where can I drill down into the harvesting results and possible errors?

**Comment by jescriu** [comment]
Dear @fdumortier,
On Monday 17 June we will try to publish the results in the INSPIRE Geoportal frontend using the current server architecture, with the assistance of Geocat. Hopefully we will succeed. Otherwise, we will have to devise changes in the server architecture, which would take more time.
Therefore, I suggest you to wait until next week. Will keep you posted.

**Comment by fdumortier** [comment]
Dear @jescriu,
Any news about my previous request: where can I drill down into the harvesting results and possible errors?
Kind regards

**Comment by jescriu** [comment]
Dear @fdumortier,

The system for the publication of harvesting results in the INSPIRE Geoportal frontend was fixed at the end of last week, and successfully tested last Monday.

I will schedule a new harvest of the BE Brussels endpoint at the beginning of next week, and will publish the results in the frontent, together with all the recent harvest from other MS / EFTA countries enpoints.

Will ping you here when ready.

**Comment by jescriu** [comment]
Dear @fdumortier,
As anticipated in my last post, your endpoint was harvested at the end of July. Also on 3 September and today (10 September), which I published in the INSPIRE Geoportal frontend.
This is the result in the harvsting console:
![image](https://github.com/user-attachments/assets/e5ad48e2-45ab-43e6-a050-94968cd5ffbc)
