### ISSUE TITLE
new harvest

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#201]
Please can you harvest HR endpoint?

Thank you,
Tanja

**Comment by jescriu** [comment]
Dear @trodin,

I just successfully harvested the HR endpoint with the following results:

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/72b4e6c2-0a20-45f7-b797-f4f154359a78)

The publication of results, from the Internal production harvesting console to the External frontend server, will have to wait until the revision of the server architecture is finishing, as announced in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/download/attachments/127305972/MIG-T78_INSPIRE_Geoportal.pdf?version=1&modificationDate=1715932838836&api=v2).
