### ISSUE TITLE
Unclear Assignment of the INSPIRE Theme

### ISSUE THREAD

**Issue by choenn** [INSPIRE-MIF/helpdesk-geoportal#202]
When searching for the text "Beweissicherung" for metadata in Germany, 15 entries for datasets are displayed. However, these 15 entries do not appear if one of the 34 INPSIRE themes has been selected beforehand. This behavior applies to each of the 34 themes that can be preselected in the bar on the left side of the screen.

What is the explanation for this behavior? Don't these datasets belong to any INSPIRE theme?

I use the latest version of Firefox.

[Search Results.pdf](https://github.com/user-attachments/files/16026326/Search.Results.pdf)

**Comment by hogredan** [comment]
I have just randomly checked some of the metadata. The data is not assigned to any INSPIRE theme in the metadata, i.e. the INSPIRE theme is not correctly specified in the metadata.

It should be like this:

```
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>Umweltüberwachung</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme"/>
</gmd:type>
<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>GEMET - INSPIRE themes, version 1.0</gco:CharacterString>
</gmd:title>
<gmd:date>
<gmd:CI_Date>
<gmd:date>
<gco:Date>2008-06-01</gco:Date>
</gmd:date>
<gmd:dateType>
<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
</gmd:dateType>
</gmd:CI_Date>
</gmd:date>
</gmd:CI_Citation>
</gmd:thesaurusName>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

Thus, no thematic assignment is recognised by the INSPIRE Geoportal.

**Comment by choenn** [comment]
@hogredan Thanks a lot. That should explain it.
