### ISSUE TITLE
Ground Water Body Malta View Service

### ISSUE THREAD

**Issue by agiur** [INSPIRE-MIF/helpdesk-geoportal#21]
To whom it may concern,

We have one datasets Ground Water Body Malta with id: 07e86eba-e7b4-4377-b375-d8c6a8440926 which is marking 'No View service found for this dataset', however the view service is working and is currently responding correctly when consumed. Kindly find attached a folder containing 2 images depicting the service consumption from Geonetwork and Geomoose. Your help on this is much appreciated.

Thanks and Regards,
René

[Inspire Issue 2.zip](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/6022518/Inspire.Issue.2.zip)

**Comment by jrc-inspire** [comment]
We have taken note of the potential issue in the current INSPIRE Geoportal, which share certain commonalities with other issues where the nature of INSPIRE services are not properly recognized by the current INSPIRE Geoportal ([#20](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/20), [#22](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/22), [#34](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/34), [#59](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/59), [#21](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/21)) that need to be properly analysed. 
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
We will do our best for addressing the issue in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
