### ISSUE TITLE
AT: Trigger new harvest

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#210]
Hi,
could you please trigger a new harvest for Austrian CSW and Publish the results in Geoportal Frontend?
Thanks,
Manuel

**Comment by jescriu** [comment]
Dear @manilly,
I just triggered the harvesting process for your endpoint but it suddenly stops before finishing with all records.
Could you please check if your server is stable?
Now I will start harvesting DE, which was already scheduled for today. When finished, I will try with your endpoint again.

**Comment by manilly** [comment]
Our endpoint seems to work fine. Could you please try again?

**Comment by jescriu** [comment]
Will do. DE also had the same issue after having harvested 3K records.
Our ICT team is checking the production console.

**Comment by jescriu** [comment]
Dear @manilly,
We analised the logs for AT and DE harvests launch yesterday and the issue seems to be caused by errors in the GetRecord function returning fewer records than actually requested (20 at a time, as configures in the harvester).  
This may be due to incorrect indexing of some records.
We did some harvest to other endpoints and completed correctly.
Could you please run a reindexation in your catalogue (AT) and let us know when finished?
We are doing the same in the production harvesting console.

**Comment by manilly** [comment]
Dear @jescriu, I just did a reindexing. Could you try again?
We currently have 1682 metadata entries.

**Comment by manilly** [comment]
<img width="974" alt="image" src="https://github.com/user-attachments/assets/2bb26705-45f7-4b7e-abf1-954cb20864a9">

**Comment by manilly** [comment]
I just tried a Harvest in Sandbox - only 1643 instead of 1682 metadata were harvested. There are datasets, services and series missing. I'll try to figure out which are missing

**Comment by jescriu** [comment]
Please, take care that all records are correctly reindexed. Sometimes it happens that a records is not accessible (e.g. the XML view is blank) due to an invalid XML structure. Worth to check with e.g. Notepad++
Obviously, these records are neither accessible through the CSW.

**Comment by manilly** [comment]
e.g. this one wasn't harvested in sandbox: https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=f2e11a84-cdc7-4cfa-b048-da3675d58704
I can't find any difference to a similar metadata record which was successfully harvested (https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=3ebf4590-e670-448c-ac38-5a04c7d96307)

**Comment by jescriu** [comment]
Thanks for the example. We will take a look if needed.
Let us finish the reindexation also on our side. It takes long (~ 341700 metadata records).

**Comment by jescriu** [comment]
Dear @manilly - After the reindexation, we got the same harvesting error after a while.
Any results on the checks on your side?

**Comment by manilly** [comment]
I tried an external harvesting in an blank GeoCat GN instance (3.12.13) and sucessfully got 1678 records.
<img width="1860" alt="image" src="https://github.com/user-attachments/assets/c15739e6-2263-40b4-a017-9a1293bcd0ad">

**Comment by jescriu** [comment]
We will try to figure out what is happening.

**Comment by jescriu** [comment]
Dear @manilly ,
In the last weeks I tried to repeat the harvesting, getting the same error - I reported it to GeoCat to try to identify the problem. 

At first sight, we spotted that your catalogue offers also several ['Feature catalogues'](http://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/eng/catalog.search#/search?facet.q=type%2FfeatureCatalog), which in principle are not suited to respond to CSW request in ISO-19139 format. 

An idea would be to test harvesting using a filter to avoid these specific records.
Currently, your harvester does not have any IGC filter applied.

**Comment by bgis-app** [comment]
Dear @jescriu,
that's correct - we offer also FeatureCatalogues. Yes, please try a Harvest to exclude these FCs.
Thanks, Manuel

**Comment by manilly** [comment]
Dear @jescriu,
that's correct - we offer also FeatureCatalogues. Yes, please try a Harvest to exclude these FCs.
Thanks, Manuel

**Comment by jescriu** [comment]
Dear @manilly ,
GeoCat confirmed this should be the issue - See below:

> POST [https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw](https://urldefense.com/v3/__https:/geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vZmMRQ_L$)
> 
> <csw:GetRecords xmlns:csw="[http://www.opengis.net/cat/csw/2.0.2](https://urldefense.com/v3/__http:/www.opengis.net/cat/csw/2.0.2__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6veGxRqOS$)"
>     xmlns:gmd="[http://www.isotc211.org/2005/gmd](https://urldefense.com/v3/__http:/www.isotc211.org/2005/gmd__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vetQUnqC$)" xmlns:ogc="[http://www.opengis.net/ogc](https://urldefense.com/v3/__http:/www.opengis.net/ogc__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vb7pLWrs$)"
>     service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml"
>     startPosition="581" maxRecords="20" outputSchema="[http://www.isotc211.org/2005/gmd](https://urldefense.com/v3/__http:/www.isotc211.org/2005/gmd__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vetQUnqC$)">
>     <csw:Query typeNames="csw:Record">
>         <csw:ElementSetName>full</csw:ElementSetName>
>         <ogc:SortBy>
>             <ogc:SortProperty>
>                 <ogc:PropertyName>Identifier</ogc:PropertyName>
>                 <ogc:SortOrder>DESC</ogc:SortOrder>
>             </ogc:SortProperty>
>         </ogc:SortBy>
>     </csw:Query>
> </csw:GetRecords>
> 
> 
> The XML contains this
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <csw:GetRecordsResponse xmlns:csw="[http://www.opengis.net/cat/csw/2.0.2](https://urldefense.com/v3/__http:/www.opengis.net/cat/csw/2.0.2__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6veGxRqOS$)" xmlns:xsi="[http://www.w3.org/2001/XMLSchema-instance](https://urldefense.com/v3/__http:/www.w3.org/2001/XMLSchema-instance__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vWzk9cP5$)" xsi:schemaLocation="[http://www.opengis.net/cat/csw/2.0.2](https://urldefense.com/v3/__http:/www.opengis.net/cat/csw/2.0.2__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6veGxRqOS$) [http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd](https://urldefense.com/v3/__http:/schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd__;!!DOxrgLBm!FCuiYDBDygytB50qFDyjn-EE0gF0agrxC6RgEYQq4d-Qxs3lNMYav76C2tbVjbLDqhEoOLfs2p7vSCV1ekW6vTa-P1Hb$)">
>     <csw:SearchStatus timestamp="2024-10-08T16:42:09" />
>     <csw:SearchResults numberOfRecordsMatched="1679" numberOfRecordsReturned="20" elementSet="full" nextRecord="601">
>     ...
> 
>         
> 
> The problem is that AT have ISO 19110 metadata published in the CSW endpoint for INSPIRE and GeoNetwork ca not convert it to ISO 19139, i.e. it does not return it. The harvester is doing some checks to verify that the number of results in the page matches numberOfRecordsReturned.

Therefore, we kindly request you to inform as about an appropiate keyword to filter your INSPIRE records (datasets, dataset series and services), or provide us with the OGC filter to be used to harvest only the appropiate resources.

**Comment by manilly** [comment]
Dear Jordi,
I have excluded the Feature Catalogues from our CSW. Could you try again?
Thanks, Manuel

**Comment by jescriu** [comment]
Dear @manilly,
It worked - This are the results of the harvest, which have been already published in the Geoportal frontend.
![image](https://github.com/user-attachments/assets/8c397ac1-4e41-4abf-9fe0-7c5de7afcedf)

Could you please describe how you excluded the Feature Catalogues from your CSW? - This could also happen with other endpoint, whi can leverage on this leasson learnt.

**Comment by jescriu** [comment]
GeoCat also provided a filter as an alternative solution - If you are using GeoNetwork 3.X, it should work as well:

> <csw:GetRecords xmlns:csw="[http://www.opengis.net/cat/csw/2.0.2](https://urldefense.com/v3/__http:/www.opengis.net/cat/csw/2.0.2__;!!DOxrgLBm!HkfbKj52gIgtwBHDkbuWMCCowCuiG9eeGaYPARBuWvZl7KLYbpDg8M3Pu4b9uLEopeMjfEnbojIcARneFy8WaHV1A9yd$)"
>                 service="CSW" version="2.0.2">
>   <csw:Query typeNames="csw:Record">
>     <csw:Constraint version="1.1.0">
>       <Filter xmlns="[http://www.opengis.net/ogc](https://urldefense.com/v3/__http:/www.opengis.net/ogc__;!!DOxrgLBm!HkfbKj52gIgtwBHDkbuWMCCowCuiG9eeGaYPARBuWvZl7KLYbpDg8M3Pu4b9uLEopeMjfEnbojIcARneFy8WaOKwE9Vv$)">
>         <PropertyIsLike wildCard="%" singleChar="_" escapeChar="\">
>           <PropertyName>_schema</PropertyName>
>           <Literal>iso19139%</Literal>
>         </PropertyIsLike>
>       </Filter>
>     </csw:Constraint>
>   </csw:Query>
> </csw:GetRecords> 

In terms of the GeoNetwork console UI:

![image](https://github.com/user-attachments/assets/ca052472-c976-431c-8640-eeb27b2141e6)

**Comment by manilly** [comment]
Dear @jescriu This is the exact filter i used when harvesting our internal metadata to the csw endpoint (see screenshot from GN 3.12.x). Bute this works for us only, cause we have a seperate instance of GN only for our CSW. As we like to merge our public search frontend and our CSW instance in future and need the feature catalogues in our search frontend, would it be possible to try this filter on your side instead of ours?

I removed the filter on our side (so the feature catalogues are in the csw again). Could you try a harvest with the scheme filter?

<img width="882" alt="image" src="https://github.com/user-attachments/assets/a37a1056-0478-447d-ac24-42a3584be0d6">

**Comment by jescriu** [comment]
Dear @manilly ,
It worked. Problem solved.

**Comment by manilly** [comment]
Perfect, thank you.
