### ISSUE TITLE
Metadata XML download

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk-geoportal#212]
Dear INSPIRE Geoportal team, 

We have noticed a problem in Lithuanian metadata.
All links to download Lithuanian metadata in xml format do not work in INSPIRE Geoportal. Could you please comment on what this could be related?
![1](https://github.com/user-attachments/assets/3f257515-6ccb-4822-95f1-2ed62d113176)

![2](https://github.com/user-attachments/assets/4c8b1a25-9299-42cc-ba34-5e5d6bd32426)

We have also noticed, that when we open and view some metadata in the INSPIRE Geoportal, the displayed information lags behind, until we click the refresh button several times. 

Best regards,

Juliana

**Comment by jescriu** [comment]
Dear @JulianaKar,
Could you please ass here the fileIdentifier with the metadfata you provided as example?

**Comment by JulianaKar** [comment]
Yes, of course, for example, Dataset for Cadastral parcels Theme: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=lt&view=themeOverview&theme=none&resourceId=05505413-1916-47cd-911d-42852b09b1c6.
However, the same problem occurs in all Lithuanian metadata as far as I've tested, and the same problem occurs in some Austrian and Greek metadata.

**Comment by jescriu** [comment]
Dear @JulianaKar,
I reindexed again your metadata records in the production harvesting console and re-publish the data from your endpoint.
As a result, the XML file is already accessible.

**Comment by JulianaKar** [comment]
Thank you very much, Jordi.

**Comment by jescriu** [comment]
To you.
