### ISSUE TITLE
Harvest request FI

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#214]
Hello

Could you start a harvest for Finland, please?

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
I havested your endpoint earlier today (while doing some tests).
I just published the results in the frontend.
![image](https://github.com/user-attachments/assets/ac84cfff-ef02-4ea6-a372-f958d4cf21e1)
