### ISSUE TITLE
new harvest for Croatia

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#216]
Hello,

can you please provide new harvest for HR on the frontend?
Thank you,
Tanja

**Comment by jescriu** [comment]
Dear @trodin,

The HR discovery endpoint was just harvested today with the following results, which were already published in the INSPIRE Geoportal frontend,

![image](https://github.com/user-attachments/assets/66f523dc-d3c7-4070-94fb-84a91d80f57d)

https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/overview?view=thematicOverview&theme=none

**Comment by trodin** [comment]
Hello,
thank you.
Something is not similar as on the sandox:

![image](https://github.com/user-attachments/assets/26b96d8a-5c13-41fc-916b-d8da28eca63f)

We have 4 datasets fro this ATOM visible as download on the sandbox but not in frontend:
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/eng/catalog.search#/metadata/0404b10d-36fb-4658-95df-dbe28394f963

And this one:
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/eng/catalog.search#/metadata/89c554d1-3f12-4302-9d57-3969d84059b8
It has error in Layer links but it is visible as viewable on geoportal frontend. How come?
Thanks,
Tanja

**Comment by jescriu** [comment]
Dear @trodin,
Thanks for reporting these strange cases.

Some differences between the production and the sandbox console might be expectable due to the different status of the infrastructure at execution run-time.

However, I will report these cases to GeoCat, since they are doing tests with your endpoint (HR) for enhancing the Link-Checker.

**Comment by trodin** [comment]
Ok, great. Thanks!

Regards,
Tanja

**Comment by trodin** [comment]
Hello, 

can I have new harvest please?

Regards,
Tanja

**Comment by jescriu** [comment]
Dear @trodin ,
Just harvested and published the results in the frontend.
![image](https://github.com/user-attachments/assets/4714c736-64b6-4c15-a020-ee7f51de7f20)

**Comment by trodin** [comment]
Hello,

we still have different results:
![image](https://github.com/user-attachments/assets/239fa4f0-2b4c-4881-b696-fea65b5ce2ed)

and on the test;
![image](https://github.com/user-attachments/assets/4dfd0022-857c-4ddf-9fc7-49d307d280a0)
 Can you check?

Thanks,
Tanja

**Comment by trodin** [comment]
Hello,

can I have a new harvest please?
Thank you,
Tanja
