### ISSUE TITLE
INSPIRE metadata missing in the Geoportal, FI

### ISSUE THREAD

**Issue by hhorppila-ux** [INSPIRE-MIF/helpdesk-geoportal#218]
We are missing a few of our INSPIRE metadata in the Geoportal. They pass metadata validation and the reference to INSPIRE themes seem to be correctly expressed. We also tested harvesting in the Sandbox environment and they did not emerge there either. Could you please investigate reason for this.

Examples below:

[Tulvariskialueet](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/%7BAF913A8D-484D-4313-ABD4-AE65A46A391E%7D/formatters/xml?approved=true)

[Tulvavaaravyöhykkeet](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/%7BD8975CE2-CD68-4A0A-A628-D061BFAD9F2B%7D/formatters/xml?approved=true)

[Puhdistamolietteen maanviljelykäyttöpaikat EU:n puhdistamolietedirektiivin mukaiseen raportointiin](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/%7B5F78786F-E693-4DC2-B8D5-FDD3C8255C4D%7D/formatters/xml?approved=true)

**Comment by jescriu** [comment]
Dear @hhorppila-ux ,
I reindexed again your metadata records in the production harvesting console and re-publish the data from your endpoint.
As a result, the above-mentioned XML files are already accessible.
