### ISSUE TITLE
Partly wrong metadata is being harvested to the INSPIRE Geoportal (FI)

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#219]
Hi,

We seem to be lacking a lot of INSPIRE metadata for Finland in the INSPIRE Geoportal. On the other side, we find that INSPIRE metadata that shouldn't be there is now showing up.

An example of an INSPIRE [metadata](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/%7BE15CD0B3-3934-4ABC-BF23-A8C622FA6A57%7D/formatters/xml?approved=true) that should be included in our harvesting result, but its missing.

An example of a non-Inspire [metadata](https://inspire-geoportal.ec.europa.eu/srv/api/records/1589897/formatters/xml?approved=true) included in the INSPIRE Geoportal

This metadata should be filtered out due to this keyword:
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>**Ei-Inspire**</gco:CharacterString>
</gmd:keyword>
</gmd:MD_Keywords

The INSPIRE theme is expressed in the same way in both and we've used the same filter parameters for years. 

Any clue what the problem could be? 

If not, we could test making a virtual CSW or a ready filtered sub-portal where only INSPIRE metadata is included for you to use if its easier for your GN-version to congest?

**Comment by jescriu** [comment]
Dear @hallinpihlatie,

Last successful harvest of your endpoint (https://dev.paikkatietohakemisto.fi/geonetwork/srv/fin/csw?service=CSW&request=GetCapabilities) was obtained on 18 September 2024. 

I tried to run a new harvest, but got an error - Did you implemented any changes in the discovery endpoint recently?

On the other hand, could you please verify if the following filter, currently defined for your endpoint, is OK?
![image](https://github.com/user-attachments/assets/5c48967e-ecd9-4ad2-8088-b0ebafd839d0)

**Comment by hallinpihlatie** [comment]
Dear @jescriu 

Thanks. Now I know why there is a discrepancy. The URL that you are using is pointing to our development environment. The endpoint to our production instance is
https://[paikkatietohakemisto.fi/geonetwork/srv/fin/csw?service=CSW&request=GetCapabilities](https://paikkatietohakemisto.fi/geonetwork/srv/fin/csw?service=CSW&request=GetCapabilities)
Could you please try harvesting again using that?

Yes, the filters defined are correct.

**Comment by jescriu** [comment]
Thank you @hallinpihlatie,
Our ICT team will update the configuration and will repeat the harvest attempt.

**Comment by hallinpihlatie** [comment]
Thanks @jescriu. There was a typo in my previous reply. Please include www (instead of dev)
https://www.paikkatietohakemisto.fi/geonetwork/srv/en/csw?service=CSW&request=GetCapabilities

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
We just successfully harvest your endpoint (with updated URL configuration) with the following results, which are already published in the frontend.

![image](https://github.com/user-attachments/assets/cd5bead8-40bb-433a-b79b-6897381c3c03)
