### ISSUE TITLE
EMFF 8.3.1 Monitoring Sites Download Service

### ISSUE THREAD

**Issue by agiur** [INSPIRE-MIF/helpdesk-geoportal#22]
To whom it may concern,

We have a dataset EMFF 8.3.1 Monitoring Sites with id: a31f18aa-7cc8-4a8f-971d-fe8c439709f7 that upon harvest is marking a missing download link. However, when accessed through the Inspire geoportal the resource has a download link which is actually downloading the dataset. Kindly find attached a folder containing some snippets which may help with the issue.

Thanks and Regards,
René
[Inspire Issue 3.zip](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/6022795/Inspire.Issue.3.zip)

**Comment by jrc-inspire** [comment]
We have taken note of the potential issue in the current INSPIRE Geoportal, which share certain commonalities with other issues where the nature of INSPIRE services are not properly recognized by the current INSPIRE Geoportal ([#20](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/20), [#22](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/22), [#34](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/34), [#59](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/59), [#21](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/21)) that need to be properly analysed.
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
We will do our best for addressing the issue in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
