### ISSUE TITLE
Harvested metadata doesn't match with the source version (FI)

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#220]
We were informed that there is old contact information in NLS-FI's metadata on the INSPIRE Geoportal. I looked into it and found discrepancies between metadata in our national portal and in the INSPIRE geoportal. For example:

[Metadata](https://www.[paikkatietohakemisto.fi/geonetwork/srv/api/records/ffd96434-d508-42db-a6af-bde8cc7db250/formatters/xml?approved=true) in our national geoportal

Corresponding [metadata](https://inspire-geoportal.ec.europa.eu/srv/api/records/ffd96434-d508-42db-a6af-bde8cc7db250/formatters/xml) in the INSPIRE geoportal

If you look closer the dateStamp of the one in our national portal is 2024-05-16T13:34:51, while it is 2023-11-22T14:29:52 in the Geoportal one, explaining why the contact information and other updates done this year cannot be found.

Our endpoint was harvested a few weeks ago, see issue #214 

It also seems as these metadata has gone missing again, see issue #218. Could it be becouse we did some reindexing on our side?

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
This is a strange behaviour, which could be due to reindexation issues.
Did you implemented any changes in the fileIdentifiers for these metadata records?
I suggest to repeat the harvest for FI, and removing the previous metadata records in the frontend before publishing the new results.

**Comment by hallinpihlatie** [comment]
Dear @jescriu 
I fixed the links to the metadata. They have the same uuid:s.
Yes, lets see if the issues are fixed by a new harvest. Good to know if we should be careful with timing of the indexing, so that it wont affect the results.

**Comment by jescriu** [comment]
As discovered [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/219#issuecoment-2470201101), we updated the configuration with the current URL available in production.
This should have resolved the current issue on metadata version.
All the best.
