### ISSUE TITLE
Harvesting request, Denmark

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-geoportal#221]
Hi Geoportal-team.

I would like to request a harvest from the Danish CSW-endpoint to the INSPIRE Geoportal.

Thanks in advanced.
Lars

**Comment by jescriu** [comment]
Dear @laers,
I harvested your national endpoint today with the following results, which are already published and available in the INSPIRE Geoportal frontend.
![image](https://github.com/user-attachments/assets/11519f00-cae8-458c-8b20-6789cc7e9c1b)
