### ISSUE TITLE
Harvest request from Lithuania

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk-geoportal#222]
Dear Geoportal team,

Could you please harvest Lithuanian metadata from CSW endpoint to the INSPIRE Geoportal.

Thank you,

Juliana

**Comment by jrc-inspire** [comment]
Dear @JulianaKar ,
we harvested your national endpoint today with the following results, which are already published and available in the INSPIRE Geoportal frontend.
![image](https://github.com/user-attachments/assets/ac23bc80-8322-4c57-8916-98c7c0d183a4)
