### ISSUE TITLE
Harvest request for Romania

### ISSUE THREAD

**Issue by LauraBolocan** [INSPIRE-MIF/helpdesk-geoportal#224]
Dear Geoportal team,

I would like to request a harvest metadata from Romania CSW endpoint to the INSPIRE Geoportal.

Thank you very much,

Laura

**Comment by jrc-inspire** [comment]
Dear @LauraBolocan 
We harvested your national endpoint today with the following results, which are already published and available in the INSPIRE Geoportal frontend.
![image](https://github.com/user-attachments/assets/7e5f4c9e-3b38-44ad-8913-b7d294f8b5ff)
