### ISSUE TITLE
Harvest request for AT

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#227]
Dear Geoportal team,

I would like to request a metadata  harvest from the Austrian CSW endpoint to the INSPIRE Geoportal.

Thanks in advance,
Manuel

**Comment by jrc-inspire** [comment]
Dear @manilly ,
We harvested your national endpoint today with the following results, which are already published and available in the INSPIRE Geoportal frontend.
![image](https://github.com/user-attachments/assets/4e2998d0-ea3f-41a9-8f08-d181a29e7fa1)
