### ISSUE TITLE
Harvest Request for MT endpoint

### ISSUE THREAD

**Issue by bensaidn** [INSPIRE-MIF/helpdesk-geoportal#231]
Dear INSPIRE team,

We request a harvest from MT endpoint before December, as we made some changes to the metadata and we'd like to check that everything is working properly.

Thanks in advance,
Nour

**Comment by jrc-inspire** [comment]
Dear @bensaidn,
We harvested your national endpoint today with the following results, which are already published and available in the INSPIRE Geoportal frontend.
![image](https://github.com/user-attachments/assets/57276915-0c1f-4925-b03a-3c057958659f)
