### ISSUE TITLE
Harvest request for LU

### ISSUE THREAD

**Issue by antjacques** [INSPIRE-MIF/helpdesk-geoportal#235]
Dear geoportal team,

We'd like to request a harvest metadata from the Luxembourg CSW endpoint to the INSPIRE Geoportal. 
Notice that we changed our endpoint URL, can you adapt it on your side? It is now https://catalog.inspire.geoportail.lu/geonetwork/inspire/eng/catalog.search#/home (rather than https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/home used before)

**Comment by jescriu** [comment]
Dear @antjacques ,
Yesterday we harvested your endpoint in production with the following results, which were already published in the Geoportal frontend. 
![image](https://github.com/user-attachments/assets/996f105c-1c86-4562-ae16-6056530f7c87)

Based on the second updete of the Lick-Checker, which incorporates the full implementation of the [Data-Service Linking Simplification](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification), that was [recently rolled out](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/236).

**Comment by antjacques** [comment]
Hello @jescriu, thanks for the harvest but I suspect that you forgot to change our endpoint URL as requested in my demand.
Would you mind to restart it with the right enrpoint?

**Comment by jescriu** [comment]
Dear @antjacques,
In fact, I missed your endpoint URL change request.
Apologies. I will reharvest your new endpoint.

**Comment by jescriu** [comment]
Results with the new endpoint. Already poublished in the Geoportal frontend.
![image](https://github.com/user-attachments/assets/f951248e-f9ed-4cea-a0d4-90a166f5212c)

**Comment by antjacques** [comment]
Many thanks @jescriu 
Can you confirm that our new enpoint will actually be the one used for the upcoming monitoring & reporting?

**Comment by jescriu** [comment]
Absolutely yes, @antjacques.
It is already configured it in the production harvest console.
