### ISSUE TITLE
Spatial scope problems

### ISSUE THREAD

**Issue by IvaGasparovic** [INSPIRE-MIF/helpdesk-geoportal#24]
Hi, we are having problems with displaying Spatial scope keywords in the INSPIRE Geoportal. All of the datasets in the Croatian NSDI Geoportal have defined keyword representing the spatial scope, but only 55 are displayed in the INSPIRE Geoportal and 88 keyword are not recognized.
Do you know the reason why this happens? The only significant difference in encoding between these metadata is the element identifier for the SpatialScope dictionary.
[DGU-DGU NIPP-0002_2021 - Prostorni opseg.pdf](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/6035250/DGU-DGU.NIPP-0002_2021.-.Prostorni.opseg.pdf)

**Comment by alitka** [comment]
Dear @IvaGasparovic,
This is an interesting behaviour... In Germany, we use the gmx:Anchor element in some metadata records too, to reference the spatial scope codelist + the related thesaurus and the output in the INSPIRE Geoportal is correct:

![grafik](https://user-images.githubusercontent.com/29542183/114692573-08a97a80-9d19-11eb-92e4-180d2d9a702c.png)
![grafik](https://user-images.githubusercontent.com/29542183/114692709-24ad1c00-9d19-11eb-8d12-787c2ac74ece.png)
![grafik](https://user-images.githubusercontent.com/29542183/114692812-427a8100-9d19-11eb-8f88-d8f30fe2c22d.png)

link to the above metadata record: [INSPIRE Protected Sites ATKIS-DLM250](https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-4fed3eb0-06fa-11ea-8480-525400695e9c_20201221-173502/services/1/PullResults/35681-35700/12.iso19139.xml)

**Comment by alitka** [comment]
Dear @IvaGasparovic,
I assume that the error is related to the codeList URI of the thesaurusName. Your reference end up with ```#```. Using the INSPIRE Validator "Conformance Class 2b: INSPIRE data set and data set series metadata for Monitorung | Monitoring requirements | M.1: Spatial scope keyword" I can confirm this: 
```The metadata record set has 1 record(s) with errors for this assertion.```
```[...]: A keyword defining the spatial scope has a thesaurusName anchor with wrong codelist URI.```
Kind regards.

**Comment by jrc-inspire** [comment]
@IvaGasparovic - Did the suggestion from @alitka help in solving your issue?
If this is the case, we will proceed to close it.

**Comment by IvaGasparovic** [comment]
The problem was solved some time ago, so please close the issue.
