### ISSUE TITLE
INSPIRE Geoportal harvest issue - MT

### ISSUE THREAD

**Issue by martin-saliba** [INSPIRE-MIF/helpdesk-geoportal#27]
Dear INSPIRE Geoportal helpdesk, 
Please note that Geoportal harvest status  and country console not accessible, https://inspire-geoportal.ec.europa.eu/harvesting_status.html

Your assistance is kindly requested.
Thank you
Martin

**Comment by df-git** [comment]
Dear @martin-saliba ,
Thank you for your feedback.
We are sorry for the inconvenience. We have now fixed the problem and the harvest console is back available.

Kind regards,
Daniele on behalf of JRC INSPIRE Support team
