### ISSUE TITLE
Error message when harvesting metadata

### ISSUE THREAD

**Issue by oreodouble** [INSPIRE-MIF/helpdesk-geoportal#29]
It was not possible to "schedule a new harvest" for the Swiss metadata in the harvest console. After processing, the following error message was reported:
Request for caching of /INSPIRE-7a076b28-098b-11e7-9a72-52540023a883_20201216-164202/services/1 ended with status 500
Microsoft Edge, Version [89.0.774.50]
Screen shot:
![image](https://user-images.githubusercontent.com/35266666/113170733-1eae3a00-9247-11eb-8ea5-4e48fe585608.png)

**Comment by bcosyn** [comment]
Same issue for the Belgian Informatie Vlaanderen node:
![Knipsel](https://user-images.githubusercontent.com/13509656/113280680-e9582980-92e4-11eb-8aa9-421e5ba3b55e.PNG)

**Comment by dartasensi** [comment]
Dear @oreodouble @bcosyn,

thank you for your feedback. We are aware of the issue and we are currently working on it.

Kind regards,
Davide on behalf of JRC INSPIRE Support team

**Comment by dartasensi** [comment]
Dear @oreodouble 

the harvest of the Swiss endpoint completed successfully. Please, review the outcome with the HarvestConsole, and let me know if there are other issues.

@bcosyn I followed the time order of the recently reported harvest errors, so I took the liberty to reschedule your endpoint for a new harvest.

Kind regards,
Davide

**Comment by dartasensi** [comment]
Dear @bcosyn 

the harvest completed successfully.
![image](https://user-images.githubusercontent.com/56717738/113828623-e8ac1100-9784-11eb-9852-8858b445fd8a.png)
Please, check the latest report available from the HarvestConsole (click on the "Check last report").

Reviewing that report, I noticed that it seems to miss ~20 records from the expected (Discovery Service declared) figure.
This usually occurs when the Discovery Service claims a total number but then it is unable to deliver them through the usual series of GetRecords calls.
On our side, we used to mitigate this behaviour by disabling the OGC SortBy filter (that, in turns, it helps reducing the duplicates issue), but I've just checked and it is already disabled on your endpoint.
If your service is based on GeoNetwork, evaluate an upgrade to a version > v3.10.0.
Based on our experience (together with our MT colleagues), it seems it improves the performances and reduces this issue.

Kind regards,
Davide
