### ISSUE TITLE
Harvest Console / Conformity of CSW service 

### ISSUE THREAD

**Issue by stephyritz** [INSPIRE-MIF/helpdesk-geoportal#3]
Hello,

We are using the harvestconsole in order to prepare the 2020 monitioring. After the harvesting we've got these indicators :
 
![image](https://user-images.githubusercontent.com/34446202/101736771-35782780-3ac4-11eb-9ec4-b4419322b3eb.png)

I don't understand why the indicator NSi4.1 related to the conformity of the CSW service is not OK.
What is the test behinf this interface ?

When I use the test "Conformance Class : Discovery Service - CSW Core" from the [validator](https://inspire.ec.europa.eu/validator/#start-tests) the result is correct (passed, manuel cheks required). So I thought that the NSi4.1. should be 100% in the harvestconsole. 

Am I doing something wrong ?

Resources : 
CSW Getcapabilities --> https://geoservices.wallonie.be/metawal/csw-inspire?request=GetCapabilities&service=CSW&acceptVersions=2.0.2&langage=fre
Link to the test report from validator --> https://inspire.ec.europa.eu/validator/v2/TestRuns/EID17825514-c78a-4abc-9f7c-fc6fe0421ccd.html

**Comment by dartasensi** [comment]
Dear @stephyritz,

as stated in [COMMISSION IMPLEMENTING DECISION (EU) 2019/1372](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2019.220.01.0001.01.ENG&toc=OJ:L:2019:220:FULL), under article 7 (a), the NSi4.1 indicator shall represent:

> (a) the number of discovery services which are in conformity with Regulation (EC) No 976/2009 multiplied by a hundred and divided by the total number of discovery services (‘NSi4,1’);

The conformity information about a service shall be expressed in its metadata definition, as per MD TG v2.0.
So if your discovery service has been properly validated and checked, and therefore it is compliant with Regulation n.976/2009, this information should be reflected in its metadata description.
Finally, you should schedule a new harvest, and the indicator will be calculated again on the available informations (ie. if you publish one discovery service in your catalogue and its conformity is true and properly declared, you should expect 100%).

Kind regards,
Davide

**Comment by vbombaerts** [comment]
Dear @dartasensi,

Could you please consider reopening this issue as we have additional information on it.

We checked the declaration of conformity for the discovery service regarding regulation 976/2009 and it was OK.
We validated the metadata against the validator and it was OK.
But still our NSi4.1 was at 0%.

So we went on with the tests and we discovered that the presence of a Temporal Extent in the metadata is causing the conformity to be evaluated at false even if it is declared at true.

Here is the test we made.
We duplicated 3 times the metadata file of the discovery service. So the content is identical for each file, except for the Temporal extent :  
- one file does not have Temporal Extent
- one file has a Temporal Extent within the same `<gmd:extent>` that the Geographic Extent
- one file has a Temporal Extent in a different `<gmd:extent>` that the Geographic Extent.


The result is that we have only 33% conformity. This is only 1 out of 3 files are recognized as conform, whereas the 3 are declared as conform. **The only file to be recognized as conform is the one without Temporal Extent.**

Here is the result of the test :

[Discovery service without Temporal Extent](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=d18f39c6-10f5-48f0-a1c9-0717d4c01ba2) and [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID5cbc4212-6159-4570-bc6a-0678e9ab077a)

[Discovery service with Temporal Extent](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=0e30a861-19a5-4aff-baf5-52859364e28b) and  [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID6920556a-d7e6-406c-b9b4-e5cb2c78e49e)

[Discovery service with Temporal Extent - 2 extents](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=cc19754e-3272-4a26-9895-652878a11abb) and [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID941140c5-5a5a-4c26-9753-cc84cf11daa7)

[Indicators resulting from harvesting these files](https://inspire-geoportal.ec.europa.eu/harvestconsole/monitoring_indicators.jsp?gpResNew=INSPIRE-f5201eb0-2404-11e5-8130-52540004b857_20210712-235802)


![image](https://user-images.githubusercontent.com/6093597/125412035-d0b8de80-e3be-11eb-9ec6-1ca52122aa98.png)

Could you please tale a look at this and tell me why the Temporal Extent in our metadata files causes the conformity to be evaluated as false ?

**Comment by vbombaerts** [comment]
See also #4

**Comment by jescriu** [comment]
Dear @stephyritz and @vbombaerts,

As per the information and the evidences you provided in this GitHub thread, we will need to revisit what seems a common issue in the INSPIRE Geoportal when performing the calculation of the NSi4.1 indicator (to be studied if affecting any other indicators as well), where the TemporalExtent is somehow affecting the parsing of XML metadata files.

Particularly we have validated the different metadata files provided and they are correct, except minor aspects we had to correct in those metadata files which have the Temporal Extent encoded - E.g. See below:

> In:

`<gml:TimePeriod xmlns:gml_1="http://www.opengis.net/gml/3.2.1" gml_1:id="d45092627e301a1050910">`

> We removed the attribute xmlns:gml_1 , and renamed gml_1:id to gml:id

As a result, we are reopening the issue, which was unfortunately overlooked.

**Comment by jrc-inspire** [comment]
We inform you that we are currently working in analyzing and addressing this issue, which has been identified as having a high priority considering its impact, with the aim of solving it in time for the upcoming INSPIRE Monitoring.

We will approach you with more information as soon as possible.

As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.

**Comment by vbombaerts** [comment]
The problem seems to be resolved. Thank you.

**Comment by jescriu** [comment]
Dear @vbombaerts and @stephyritz,
As you noticed, our Geoportal IT team already implemented a solution for this issue. 
Therefore, I proceed to close this issue. Please feel free to comment / open again if needed.
Thank you again for your spotting the problem.
