### ISSUE TITLE
Problem Harvesting AT metadata

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#30]
Hi,
i tried to start a Harvest from Austrian CSW as usual (tried it already 3 times). I'm getting the E-Mail stating "[INSPIRE Geoportal - Harvest console] New session request accepted", but in Harvest console there is no process running
see:
![image](https://user-images.githubusercontent.com/45065613/113260899-18fc3700-92cf-11eb-8c66-9df8bd8cf720.png)

**Comment by marcingrudzien** [comment]
Hi,

I have the same problem in Poland.

Best regards,
Marcin

**Comment by dartasensi** [comment]
Dear @manilly @marcingrudzien,

thank you for your feedback. We are aware of the issue and we are currently working on it.

Kind regards,
Davide on behalf of JRC INSPIRE Support team

**Comment by dartasensi** [comment]
Duplication of #29

**Comment by dartasensi** [comment]
Dear @manilly
the harvest of the AT endpoint completed successfully. Please, review the outcome with the HarvestConsole, and let me know if there are other issues.

Dear @marcingrudzien 
I followed the time order of the recently reported harvest errors, so I took the liberty to reschedule your endpoint for a new harvest.

Kind regards,
Davide

**Comment by dartasensi** [comment]
Dear @marcingrudzien 

I see that the harvest completed successfully, and you already managed to review and publish it.

Kind regards,
Davide
