### ISSUE TITLE
SK: Date of the harvesting for the INSPIRE Monitoring 2020 indicators calculations

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#31]
In most of the MSs [INSPIRE indicators overview](https://inspire-geoportal.ec.europa.eu/mr2020.html), there are mentioned dates arount 16-17 Jan 2021. 
Eg. in [summary for SK](https://inspire-geoportal.ec.europa.eu/mr2020_details.html?country=sk) there is _The date of harvest metadata: Sun, 17 Jan 2021 07:11:23 GMT._

![obrázok](https://user-images.githubusercontent.com/6195936/113639284-16a42f00-9679-11eb-92ff-da292dbb21ff.png)

Is there some motivation for this timeshift from the 15.12.2020, or indicators were actually calculated from the harvesting on these days in January?

Thanks, Martin.

**Comment by dartasensi** [comment]
Dear @MartinTuchyna ,

thank you for reporting this bug.
Indeed it was a visualization error (ie. jumping exactly one month forward) of the "dumpdate" field, and it has been promptly fixed.
For your assurance, you can directly access the original MR2020 source data here:
https://inspire-geoportal.ec.europa.eu/mr2020/resources/geoportal/INSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883.json

Kind regards,
Davide

**Comment by MartinTuchyna** [comment]
Thanks @dartasensi !
