### ISSUE TITLE
Problem Harvest Console metadata NL

### ISSUE THREAD

**Issue by wboersma** [INSPIRE-MIF/helpdesk-geoportal#32]
Hello,

Today I started a harvest. The systems says 'processing' but after 1 minute you get the screen again 'start a harvest'.
 As more MS have also issues since a week, can you please check what the problem is and resolve this issue.

Best regards, Wideke

**Comment by dartasensi** [comment]
Dear @wboersma,

thank you for your feedback. We are aware of the issue and we are currently working on it.

Kind regards,
Davide on behalf of JRC INSPIRE Support team

**Comment by dartasensi** [comment]
Duplication of #29

**Comment by dartasensi** [comment]
Dear @oreodouble
it seems that now the harvest service is fully operational and the harvest of the NL endpoint completed successfully. As I replied to other users with the same recent issues, please, review the outcome with the HarvestConsole, and let me know if there are other issues.

Kind regards,
Davide

**Comment by dartasensi** [comment]
Dear @wboersma 

a quick update: the harvest is still running, even the ETA is ways over its _past due_.
This may happens when some slow service is involved, but let's wait for the completion and I will review it.

Kind regards,
Davide

**Comment by dartasensi** [comment]
Dear @wboersma 

thanks for your patience.
As mentioned in #33 , there was a significant corruption of data that led to several errors.
Now, I scheduled again the harvest of your endpoint. Sorry for the inconvenience.

KR
Davide

**Comment by dartasensi** [comment]
Dear @wboersma 

the harvest has been completed successfully.
Please, review the result in the HarvestConsole and, if everything looks fine, I will then close this issue.

Davide

**Comment by wboersma** [comment]
Dear @dartasensi 

The outcome looks fine, so I publised the results today. I close the issue if the results are publised (pending still).

Best regards,

Wideke

**Comment by wboersma** [comment]
Dear @dartasensi,

The results were still not published this morning (after 4 days). I published them now again, but can you check what goes wrong in the publish process.

Best regards, Wideke

**Comment by dartasensi** [comment]
Dear @wboersma 

Thanks for reporting this issue. I will have a look immediately and let you know.

Davide

**Comment by dartasensi** [comment]
Update: We are experiencing some issues within the connection to our servers.
I will keep you posted.

Davide

**Comment by wboersma** [comment]
I see the harvest is publised now, see https://inspire-geoportal.ec.europa.eu/harvesting_status.html

**Comment by dartasensi** [comment]
Dear @wboersma 

Again, apologies for this inconvenience. Our IT support finally managed to restore the remote connection to our servers yesterday, then I checked and I can confirm that the publishing completed successfully, even if slower than usual.
I would close this issue, but you should be able to still comment if you need further assistance on this.

KR,
Davide
