### ISSUE TITLE
SI: Harvesting problem with download services

### ISSUE THREAD

**Issue by nppozar** [INSPIRE-MIF/helpdesk-geoportal#34]
Dear Geoportal helpdesk team,

We would ask for your help in detecting harvesting problems. In the last harvest of Slovenian metadata, some metadata of download and view services are missing, but we can't find a solution. For download services the linkage checker reports that the download link is missing, everything is fine on the reference validator, and we also have the URL for the dataset defined in the service. All of this metadata has been successfully harvested and we have not made any changes to it since. In view services, we also found some errors in the metadata, which we will eliminate at the source. Please if you can help us figure out what is wrong, at least to download services where we do not detect the error ourselves.

Thank you very much and best regards,

Nina Požar

**Comment by dartasensi** [comment]
Dear @nppozar 

thank you for the feedback. I will review as soon as possibile the status of your endpoint regarding the reported error on missing data, and provide you feedback.
May I ask you some more detailed examples of your discoveries, to narrow down our effort on debugging it? Thanks.

KR,
Davide

**Comment by nppozar** [comment]
Dear @dartasensi,

yes off course. For example: download services for Consolidated Cadastre of Public Infrastructure  (923dfad8-6172-4ffa-be2a-4436e26a8d78) are missing. At the linkage checker I get this report:

![image](https://user-images.githubusercontent.com/45449924/115006347-0d9d3400-9ea9-11eb-80b5-eef117611bd1.png)

I also validated download service metadata for this example : 

and report says everything is ok: 
[ETF Test Report_4519204d-1cca-4809-ba47-6e7568d68ea3.zip](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/6324128/ETF.Test.Report_4519204d-1cca-4809-ba47-6e7568d68ea3.zip)

It's the same with others download services for:

- Consolidated Cadastre of Public Infrastructure (923dfad8-6172-4ffa-be2a-4436e26a8d78)
- Ladn Cadastre (3e0b727e-49d5-4c7f-835b-823c5392a307)
- Building Cadastre (5aa2b97b-2ea3-427f-a9fb-d7827c61c115)
- Register of Spatial Units (25e80f41-8348-4759-bac1-ec56c7223509)
- Register of Geographical Names (0f5fd804-9073-42d9-ad3c-b273f59fc16c)

For missing download service for dataset Mineral deposits and resources (78bfe1b3-8a29-4fd3-aa3a-a7c1d3513868), there are some errors in metadata about Limitation on Public Access and Conditions for Access and Use, but till now we harvested that successfully, despite that error.

For the view services the story is the same as for Mineral deposits, we know we have some errors in metadata but till now we also harvested them successfully. One of missing view services is for example for dataset 1GE GeoZS 1M surface Geologic Unit (04301870-c25b-4941-9f28-6eb799cabb9b).

**Comment by dartasensi** [comment]
Dear @nppozar 

Thank you for the samples. I will use them to check their status on the latest harvest session.
Regarding the potential errors on that harvest, I didn't find anything relevant in the logs.

Davide

**Comment by jrc-inspire** [comment]
We have taken note of the potential issue in the current INSPIRE Geoportal, which share certain commonalities with other issues where the nature of INSPIRE services are not properly recognized by the current INSPIRE Geoportal ([#20](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/20), [#22](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/22), [#34](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/34), [#59](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/59), [#21](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/21)) that need to be properly analysed. 
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
We will do our best for addressing the issue in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
