### ISSUE TITLE
Error in publishing BE harvest results

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-geoportal#35]
We tried to publish the results from te Belgian/Flemish node 'Metadata Vlaanderen CSW (Informatie Vlaanderen)' but received following error/message
![Capture](https://user-images.githubusercontent.com/13509656/116966609-e3bd7d00-acb0-11eb-9937-f2d3301eb505.PNG)

**Comment by dartasensi** [comment]
Dear @bcosyn 

thanks for reporting this.
I checked the latest successful harvest ([April 25th](https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-f0c91711-ece0-11e8-a08e-52540023a883_20210425-120002/services/1/PullResults/)) on disk and everything seems fine. It completed successfully, but I cannot find any trace of a publication request, so it could be a problem of request handling inside HarvestConsole.

Could you please try again so I can trace the eventual error (if it pops up again)? Thanks.

Kind regards,
Davide

**Comment by bcosyn** [comment]
Hi @dartasensi 
Yesterday afternoon (05/05) I noticed that the Flemish results were published. This without any additional action from my side.

**Comment by dartasensi** [comment]
Dear @bcosyn 

This kind of actions are traced when an authorized user publish the selected harvest through HarvestConsole.
On our systems, it now results that:
> approved="true" approvedBy="n0*96z" approvalDate=**"2021-05-05T07:52:20.876Z"**

_(login details obscured on purpose, but you should be able to recognize it)_
Do you recognize at least the timing of that publication request?
Have you probably tried again to publish, after your initial description here in GitHub? (dated May 4th at 8:14 AM+2)

Even if this behavior seems strange, when it places itself after your initial issue and before my analysis and reply, in the middle of this timeline of events, I would rather suggest this explanation.
My conclusion is that the HarvestConsole logged all your request(s) and placed in a queue, while the backend was stuck. So, soon after I restored the backend functionality (temporally before my reply [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/35#issuecomment-832867321), at 20210505 07:16 PM+2) HarvestConsole processed the queue and forward the requests on the backend.

Now, if you evaluate this published harvest as not correct, I can suggest two solution:
- schedule a new harvest and publish it
- ask for rollback (ie. I retrieve and restore a previous harvest)

Would you please provide your opinion? Thanks

Davide

**Comment by bcosyn** [comment]
Hi Davide,

Really sorry for my late answer. Indeed I retried after May 4th and received the same answer. So your idea/explanation seems acceptable to me.
Anyhow finally everything was published. One of the coming days I will run a new harvest.

Regards
Bart

Van: Davide Artasensi ***@***.***>
Verzonden: Friday, 7 May 2021 12:24
Aan: INSPIRE-MIF/helpdesk-geoportal ***@***.***>
CC: Cosyn Bart ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [INSPIRE-MIF/helpdesk-geoportal] Error in publishing BE harvest results (#35)


Dear @bcosyn<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbcosyn&data=04%7C01%7Cbart.cosyn%40vlaanderen.be%7C469c1f6577184e59de6d08d91142387f%7C0c0338a695614ee8b8d64e89cbd520a0%7C0%7C0%7C637559798373823564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TWuo%2FknlT0%2B70Ai08GYulx%2F7Q77xHVKtuXYowECtYzc%3D&reserved=0>

This kind of actions are traced when an authorized user publish the selected harvest through HarvestConsole.
On our systems, it now results that:

approved="true" approvedBy="n0*96z" approvalDate="2021-05-05T07:52:20.876Z"

(login details obscured on purpose, but you should be able to recognize it)
Do you recognize at least the timing of that publication request?
Have you probably tried again to publish, after your initial description here in GitHub? (dated May 4th at 8:14 AM+2)

Even if this behavior seems strange, when it places itself after your initial issue and before my analysis and reply, in the middle of this timeline of events, I would rather suggest this explanation.
My conclusion is that the HarvestConsole logged all your request(s) and placed in a queue, while the backend was stuck. So, soon after I restored the backend functionality (temporally before my reply here<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FINSPIRE-MIF%2Fhelpdesk-geoportal%2Fissues%2F35%23issuecomment-832867321&data=04%7C01%7Cbart.cosyn%40vlaanderen.be%7C469c1f6577184e59de6d08d91142387f%7C0c0338a695614ee8b8d64e89cbd520a0%7C0%7C0%7C637559798373823564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QrT5EtvfhCaZJ6po%2F2XBBbR9yu2rssNMuUHJYILGurY%3D&reserved=0>, at 20210505 07:16 PM+2) HarvestConsole processed the queue and forward the requests on the backend.

Now, if you evaluate this published harvest as not correct, I can suggest two solution:

  *   schedule a new harvest and publish it
  *   ask for rollback (ie. I retrieve and restore a previous harvest)

Would you please provide your opinion? Thanks

Davide

-
