### ISSUE TITLE
Harvesting Process

### ISSUE THREAD

**Issue by agiur** [INSPIRE-MIF/helpdesk-geoportal#36]
We are currently trying to perform a harvest on our end point but it seems that the harvest is not running and it is marking as ready immediately after it is scheduled.
![Harvest-Start](https://user-images.githubusercontent.com/32297502/117106951-0f0f9d00-ad81-11eb-9dd6-8689113269ab.png)
![Harvest-Stop](https://user-images.githubusercontent.com/32297502/117106958-133bba80-ad81-11eb-9e18-6cde1b8bff5e.png)

We are currently doing the usual procedure for a harvest. Kindly find attached the images to help you understand.

Thanks in advance for your help

**Comment by dartasensi** [comment]
Dear @agiur 

thanks for reporting this error.
I will try immediately to schedule a new harvest on your behalf.

**Comment by dartasensi** [comment]
Dear @agiur 

the harvest completed successfully. Please review it and feel free to report any anomalies.
Otherwise, I will close this issue in the next days.

Kind regards,
Davide

**Comment by agiur** [comment]
Dear @dartasensi 
Thank you for your support, you can proceed to close the issue.
Kind Regards,
René
