### ISSUE TITLE
CZ - New harvest not executed

### ISSUE THREAD

**Issue by madlenkk** [INSPIRE-MIF/helpdesk-geoportal#39]
Dear Geoportal team,
I would like to report problem with the harvest console. I tried to run a new harvest of czech catalog few times since yesterday morning, but without success.

I push the button Schedule a new harvest at the Dashboard and then Proceed in Schedule a new harvest dialog. I got the email and the Status at the Dashboard correctly changes to: Scheduled Estimated start time*: N/A
![image](https://user-images.githubusercontent.com/8487830/119951492-4e09ca80-bf9c-11eb-8f65-b897e75cd171.png)

But after few minutes the Dashboard changes to the status it had before I started the harvest
![image](https://user-images.githubusercontent.com/8487830/119951453-42b69f00-bf9c-11eb-860b-ad276db47e87.png)
and it seems the harvest was not executed.

Thanks and regards,
Magdalena

**Comment by alitka** [comment]
Just a comment to the above described circumstances (malfunctions): 
For Germany a harvest process ran from May 27, 2021 to May 29, 2021 and now the publication is running. 
Could it be possible that other processes could not run at this time due to temporarily low disk space resources on the JRC site?

**Comment by dartasensi** [comment]
Dear @madlenkk 

I checked now, and all your harvest requests went into `/errors`.
Then I restarted the web application, and I scheduled a new request on your behalf.
When the Geoportal tries to obtain the first batch with a `GetRecords` request, your service replies:
```xml
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport^M
        xmlns:ows="http://www.opengis.net/ows/1.1" version="1.1.0"^M
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"^M
        xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd"><ows:Exception exceptionCode="InvalidParameterValue" locator="Filter"><ows:ExceptionText>Invalid filter: Array
(
    [0] => Array
        (
            [0] => Array
                (
                    [0] => _FOR_INSPIRE_ = '1'
                    [1] => AND
                    [2] => @hlname = 'http://geoportal.gov.cz/inspire'
                )

        )

)
</ows:ExceptionText></ows:Exception></ows:ExceptionReport>
```

Our current configuration on your endpoint doesn't present any default filter and I checked that the Geoportal doesn't send any ogc filter within the `GetRecords` requests.
Did you recently change something in your catalogue service?

[Here the actual configuration for your endpoint.](https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-16542303-763e-11e4-8b38-52540004b857_20210525-153102/services/1/inspire.geoportal.resource.service.discovery.xml)

[Here my execution, with the `exception` response from your CSW.](https://inspire-geoportal.ec.europa.eu/sandbox/resources/errors/INSPIRE-16542303-763e-11e4-8b38-52540004b857_20210601-160624/services/1/testDiscoverMetadata/downloaded.xml)

I hope this helps.

Davide

**Comment by madlenkk** [comment]
Dear Davide, 

thank you very much for your effort and reply! We fixed our catalogue service according to your recommendations and the harvest was already executed successfully.

Best regards,
Magdalena
