### ISSUE TITLE
Harvest Console / Conformity of spatial data sets

### ISSUE THREAD

**Issue by stephyritz** [INSPIRE-MIF/helpdesk-geoportal#4]
Hello,

I don't understand how the DSi2.2 is caluclated on the harvest console. Is it possible to explain how do you proceed to etsablish if a dataset is conform or not ?
For example, in our case, we've got this result : 
![image](https://user-images.githubusercontent.com/34446202/101738458-76713b80-3ac6-11eb-8309-ca05d84a340b.png)

I'm surprised to discover a result of 0% of dataset conformity because four datasets from the annex 2 are conform. 
I thought the dataset conformity is described in the metadata through the completion of "<gmd:DQ_ConformanceResult>" with the specific technical Guidelines of the theme. This is what we do fot this metadata for example (EL theme) : http://metawal.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=2a8a389c-5450-4edc-80b5-96eca3573307

I would be grateful if you know what is wrong from our side.
Have a nice day.
Stéphane

**Comment by dartasensi** [comment]
Dear @stephyritz 

similarly to the issue #3 , you should check that the conformity about a dataset is properly expressed in its metadata.
As stated in [COMMISSION IMPLEMENTING DECISION (EU) 2019/1372](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2019.220.01.0001.01.ENG&toc=OJ:L:2019:220:FULL), under article 5 (c), the DSi2.2 indicator shall represent:
> (c) the number of spatial data sets corresponding to the themes listed in Annex II to Directive 2007/2/EC which are in conformity with Regulation (EU) No 1089/2010 multiplied by a hundred and divided by the number of spatial data sets corresponding to the themes listed in that Annex (‘DSi2,2’);

Therefore, in order to calculate this indicator, I would expect that, for every relevant dataset:
- the dataset metadata should contain at least one keyword related to the themes listed in Annex II
- the dataset should be conformant with the Reg N. 1089/2010, and this conformity declaration is properly expressed in its metadata

For further informations about dataset conformity, I would suggest to open a question on the ["Community helpdesk for generic INSPIRE related topics"](https://github.com/INSPIRE-MIF/helpdesk).

Kind regards,
Davide

**Comment by vbombaerts** [comment]
Dear @dartasensi,

Could you please consider reopening this issue as we have additional information on it.

We checked the declatation of Annex 2 keywords in the metadata and it was OK.
We checked the declaration of conformity regarding regulation 1089/2010 and it was OK.
We validated the metadata against the validator and it was OK.
But still our DSi2.1 was at 0%.

So we went on with the tests and we discovered that the presence of a Temporal Extent in the metadata is causing the conformity to be evaluated at false even if it is declared at true.

Here is the test we made.
We duplicated 3 times the metadata file of the LPIS 2017 dataset. So the content is identical for each file, except for the Temporal extent :  
- one file does not have Temporal Extent
- one file has a Temporal Extent within the same `<gmd:extent>` that the Geographic Extent
- one file has a Temporal Extent in a different `<gmd:extent>` that the Geographic Extent.


The result is that we have only 2.5% conformity. As we have 41 dataset declared in Annex 2, this means that only 1 is recognized as conform. **The only file to be recognized as conform is the one without Temporal Extent.**

Here is the result of the test :

[LPIS 2017 dataset without Temporal Extent](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=550cd15d-5587-4196-acd0-d6b139f6e325) and  [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID1710c2f3-8ea8-473b-8a1d-727f277eba64)

[LPIS 2017 dataset with Temporal Extent](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=6a823651-a265-4be2-af4e-592e8b30e991) and  [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID6a4ca874-47d5-4b28-bc20-6d806114cdcd)

[LPIS 2017 dataset with Temporal Extent - 2 extents](https://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementsetname=full&id=0c51708c-0d3e-4b95-a052-907ba496ba9b) and  [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID2800af10-0b6a-4b53-b93c-e61199fd800b)

[Indicators resulting from harvesting these files](https://inspire-geoportal.ec.europa.eu/harvestconsole/monitoring_indicators.jsp?gpResNew=INSPIRE-f5201eb0-2404-11e5-8130-52540004b857_20210712-235802)


![image](https://user-images.githubusercontent.com/6093597/125413433-48a806be-ab82-4261-94ad-58809f6dc1b2.png)

Could you please tale a look at this and tell me why the Temporal Extent in our metadata files causes the conformity to be evaluated as false ?

**Comment by vbombaerts** [comment]
See also #3

**Comment by ghost** [comment]
@vbombaerts 

I didn't check your problem but it could be connected to GML Version. INSPIRE Validator accepts 3.2.1 and 3.2 (https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md). In your metadata record you are using 3.2. - `xmlns:gml="http://www.opengis.net/gml/3.2"`

Maybe you could change GML Version encoding in the metadata record to 3.2.1 and check if it makes any difference to the parameter calculation.

**Comment by fxprunayre** [comment]
> INSPIRE Validator accepts 3.2.1 and 3.2

And what about the tools computing indicators ?
Any code or indicator computing rules to share to check this ?

>  In your metadata record you are using 3.2. - xmlns:gml="http://www.opengis.net/gml/3.2"
> Maybe you could change GML Version encoding in the metadata record to 3.2.1

I think http://www.opengis.net/gml/3.2 is 3.2.1. See
* http://schemas.opengis.net/iso/19139/20060504/gco/basicTypes.xsd = xmlns:gml="http://www.opengis.net/gml" = 3.2.0
* http://schemas.opengis.net/iso/19139/20070417/gco/basicTypes.xsd = xmlns:gml="http://www.opengis.net/gml/3.2 = 3.2.1
```xsd
<xs:import namespace="http://www.opengis.net/gml/3.2" 
                  schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
```
and
http://www.opengis.net/gml/3.2 > http://schemas.opengis.net/gml/3.2.1/gml.xsd
which is even 3.2.2.


So not sure downgrading all records to 3.2.0 will help ?

It is really complicated to figure out what is wrong here.

**Comment by ghost** [comment]
@fxprunayre @vbombaerts I hope someone from JRC can answer your questions...

P.S.
In your case I wouldn't downgrade all records before it is clear what is the problem here. My idea was to change only one record and check if indicator changes in order to check if tool for computing monitoring indicators supports only specific GML version(s)... Sorry if I made it more complicated than it was before. :(

**Comment by jescriu** [comment]
Dear @stephyritz and @vbombaerts,

As per the information and the evidences you provided in this GitHub thread, we will need to revisit what seems a common issue in the INSPIRE Geoportal when performing the calculation of the DSi2.2 indicator (to be studied if affecting any other indicators as well), where the TemporalExtent is somehow affecting the parsing of XML metadata files.

Particularly we have validated the different metadata files provided and they are totally correct.

As a result, we are reopening the issue, which was unfortunately overlooked.

**Comment by jrc-inspire** [comment]
We inform you that we are currently working in analyzing and addressing this issue, which has been identified as having a high priority considering its impact, with the aim of solving it in time for the upcoming INSPIRE Monitoring.

We will approach you with more information as soon as possible.

As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.

**Comment by vbombaerts** [comment]
The problem seems to be resolved. Thank you.

**Comment by jescriu** [comment]
Dear @vbombaerts and @stephyritz,
As you noticed, our Geoportal IT team already implemented a solution for this issue. 
Therefore, I proceed to close this issue. Please feel free to comment / open again if needed.
Thank you again for your spotting the problem.
