### ISSUE TITLE
AT: Harvesting in status running since 4 days

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#42]
Hi,
I tried to trigger a harvest last Thursday for the Austrian CSW. The status is till running.
Can you please investigate this?
Thanks, Manuel

**Comment by bcosyn** [comment]
Same status issue for the BE/Flemish node since June 12. 
![image](https://user-images.githubusercontent.com/13509656/122946001-48c05580-d379-11eb-9296-85476e3ca56d.png)

**Comment by dartasensi** [comment]
Dear @bcosyn @manilly 

thanks for reporting this. For (at the moment) unknown reasons (probably a race condition), both of your harvest sessions were completed, they successfully ended the [collect] and [analyse] phases but then failed the upload in the solr engine, resulting in each of them stuck while occupying an entire solr core (leaving only one available for harvest).
Now I restarted the main service, and cleanup the situation on the solr catalog: on your behalf I'm willing to restart the harvest and see how it proceed.

Davide

**Comment by dartasensi** [comment]
Both rescheduled and running:
- **AT** // ETA today at ~16:30 GMT
- **BE Vlaanderen** // ETA June 26th at ~22:42 GMT

**Comment by dartasensi** [comment]
@manilly: your harvest is ready to be review. It seems valid to me, so I will proceed and close this issue.
@bcosyn: since the harvest of your endpoint used to take quite some time to complete, feel free to open a new issue if something's wrong.

KR,
Davide
