### ISSUE TITLE
IT: something wrong with the resources harvested by the national discovery service

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-geoportal#43]
On June, 15 I performed a successful harvesting session from the Italian national discovery service and three days after (June, 18) I published the resources harvested.

Today I am noticing that the Italian discovery service is no longer included in the list in the ['Harvesting Status' page](https://inspire-geoportal.ec.europa.eu/harvesting_status.html) in the INSPIRE geoportal and that the numbers of the [resources currently published](https://inspire-geoportal.ec.europa.eu/results.html?country=it&view=details&theme=none) are not the numbers of the resources harvested and published in the process mentioned above.

The image below shows the numbers of the resources published in the previous harvesting session on April, 21, but that numbers had increased in the latest harvesting session in June.

![immagine](https://user-images.githubusercontent.com/7059416/122953120-c470d100-d37e-11eb-94d0-a3e6036477a7.png)

Please, could you explain me what is the problem?

Thank you very much,
Antonio

**Comment by dartasensi** [comment]
Dear @AntoRot 

I will have a look. Probably the publishing of the harvest didn't complete correctly.

**Comment by AntoRot** [comment]
Thank you @dartasensi!

Please also notice that the numbers of the resources currently published are also different from those shown in the image related to the harvest in April and that in the harvest console the harvest performed on June 15 is listed as the last successful execution.

**Comment by dartasensi** [comment]
Yes, I'm using the results in /sandbox as reference.
Since it is now EOB, don't be scared but I removed the entire IT presence in the Geoportal, in order to restart the automatic publication of the harvest session from /sandbox.
Let's see if this would fix the error you reported.

**Comment by dartasensi** [comment]
It seems solved.
The transfer from /sandbox was completed correctly. The harvest status page is restored and showing the correct date of publication, and now it is currently uploading and publishing all the records in the solr catalog (it will probably take few hours to complete).

**Comment by AntoRot** [comment]
Thank you again @dartasensi!
