### ISSUE TITLE
Add organisation name in table with dataset issues

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-geoportal#44]
Dear,

Monthly we distribute the list of datasets with issues during harvesting among our data providers. To give them more insight into the datasets that are not properly made available, the name of the responsible organization is included in the table of datasets with issues. Then it is immediately clear which organizations have to work to get their implementation in order.
In the monitoring report it is not immediatly clear what dataproviders should do to improve, the information is on memberstate level. Is it possible to present the results of the monitoring additional on organsiation level?

Best regards Ine

**Comment by alitka** [comment]
We would appreciate it if additional information could be added to the list with incorrect records. 
It would be very helpful for us as well to have the organization name listed in the tabled error reports from the harvesting. This also applies to the metadata error tables, which are provided together with the monitoring results in the harvest console.

In addition, we would have further requirements (e.g. regarding the download function for "resources for which linkage issues were found") that were once collected during the testing phase of the harvesting console at the beginning of the new process but not yet followed up further.

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
Therefore, we will consider your enhancement request in the future, in the context of the redesigned INSPIRE Geoportal based on GeoNetwork.
