### ISSUE TITLE
Please publish correct harvesting results for SE

### ISSUE THREAD

**Issue by Privatmijoha** [INSPIRE-MIF/helpdesk-geoportal#46]
SE published June 22 our harvesting executed on June 20, 20:04:02, but now something wrong and old is listed in the portal as result from SE. Please publish our harvesting result from the harvesting executed  2021-06-20 20:04:02. The old and wrong result is not even from our previous harvest - it is something really wrong. SE is not even listed in the harvesting status list any longer!
Se attached the harvesting report from June 20 that we published June 22.
![2021-06-22 08-24-09](https://user-images.githubusercontent.com/79651507/123613098-70913c80-d803-11eb-924e-f5633d9535fd.jpg)

**Comment by dartasensi** [comment]
Dear @Privatmijoha 

I have been forced to delete the data related to the published harvest in order to solve this anomaly. Now it's running the script to publish again the results of the selected harvest (2021-06-20 20:04:02)
I will let you know when the situation is restored.

KR,
Davide

**Comment by dartasensi** [comment]
Dear @Privatmijoha 

the issue seems solved, and the numbers now match.
Please, review it and let me know if problems still remains. Otherwise I'm willing to close this issue.

Regards,
Davide

**Comment by Privatmijoha** [comment]
Looks fine! 
Thank you @dartasensi.

Kind regards,
Mikael
