### ISSUE TITLE
BE-WAL : conformity indicators and temporal extent

### ISSUE THREAD

**Issue by vbombaerts** [INSPIRE-MIF/helpdesk-geoportal#50]
Dear helpdesk, 

We are experiencing problems with the conformity of datasets and services indicators when we declare a Temporal Extent in the metadata.
We explain this in the original tickets #3 and #4. Could you please consider reopening it ? Thank you.

**Comment by dartasensi** [comment]
Dear @vbombaerts 

I need to give it a more accurate look, but I read all your comments and I suppose they're bugs, so I will surely fix them.
In the meantime, I would like to thank you: I really appreciate your efforts in the analysis of this issue.

KR,
Davide

**Comment by vbombaerts** [comment]
@dartasensi Any news regarding the problem ?

**Comment by jescriu** [comment]
Dear @vbombaerts,

We double-checked the metadata files provided in #3 and #4, and they are correct.

As a result we reopened both issues, for which we will provide a fix as soon as possible.
