### ISSUE TITLE
Resource linkages checker tool problem

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-geoportal#52]
Hi,

I am trying to use the Resource linkages checker tool https://inspire-geoportal.ec.europa.eu/linkagechecker.html. I select "INSPIRE metadata XML content" for all 3 metadata types and copy/paste relevant metadata contents, then press the "Check Resources" button. 

Almost immediately after I receive an error **The request had an error! Please try again later or contact the support**

Request sent in the background to https://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/INSPIREResourcesLinkageTester returns error **500**

Tested on Google Chrome 92.0.4515.131 and latest Safari browsers.

Best regards,
Marcin

**Comment by alitka** [comment]
Related to issue #6 - Resource linkages checker tool > 'The system is handling your request. Please wait...'

**Comment by marcingrudzien** [comment]
The problem has been resolved in the meantime. For few days the tool has been working ok.

**Comment by JohannaOtt** [comment]
Happened to me in Firefox today - tried with Chrome afterwards, that worked.

**Comment by jrc-inspire** [comment]
@marcingrudzien - Did the use of the Chrome browser solved this issue, as @JohannaOtt suggested?
If this is the case, we will proceed to close the issue.

**Comment by jrc-inspire** [comment]
We proceed to close this issue.

The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

Therefore, open issues affecting the current INSPIRE Linkage Checker (being part of the infrastructure tools associated to the current INSPIRE Geoportal backend) will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
