### ISSUE TITLE
INSPIRE Discovery CSW 2.0.2 is not INSPIRE compliant

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-geoportal#53]
INSPIRE Discovery Service (https://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGCCSW202?REQUEST=GetCapabilities&SERVICE=CSW&version=2.0.2) is not INSPIRE compliant.
 
- Report from INSPIRE Validator: 
[Report.zip](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/7128104/Report.zip)

- Screenshot: ![image](https://user-images.githubusercontent.com/38787131/132493032-c256c013-094b-4422-9f6c-f9f63345bad0.png)

- GetRecordByID operation:
On top of that GetRecordByID operation can't retrieve any record in the catalogue!

**Comment by jrc-inspire** [comment]
The current INSPIRE Geoportal neither officially offers any CSW service nor APIs to access and use the content in its database.

As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. Offering an INSPIRE compliant INSPIRE Geoportal CSW service will be considered as part of the evolution of this project, which is currently ongoing. Support of new APIs will be also explored in the future taking into account the upcoming trends and standards.

The CSW discovery service you spotted is an early, not finished development which indeed does not support the full set of INSPIRE discovery service requirements and recommendations (e.g. language parameter, OGC filters, etc.), as it would be expectable. Moreover, further development of this feature of the current Geoportal is now dismissed, as explained above.
