### ISSUE TITLE
Availability of the INSPIRE priority datasets list

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#58]
Dear all, 

could it be possible to share the link for the last version of the INSPIRE priority datasets list?

Url, we have been using seems to be not anymore available:
https://ies-svn.jrc.ec.europa.eu/projects/2016-5/wiki/PriorityList 

Thanks, Martin

**Comment by hogredan** [comment]
Dear Martin,

you can find the recent version of the INSPIRE priority data sets list in the new repository of Action 2.1: 
https://github.com/INSPIRE-MIF/need-driven-data-prioritisation/tree/main/documents

**Comment by MartinTuchyna** [comment]
Dear Daniela, 

thanks a lot for the reference.

**Comment by MarcoMinghini** [comment]
Thanks @hogredan for the reply.

All: please note that a dedicated GitHub repository (under this same space) was created to manage the activities of Action 2.1: https://github.com/INSPIRE-MIF/need-driven-data-prioritisation

**Comment by MartinTuchyna** [comment]
Great,
thanks @MarcoMinghini 
Bookmarks and links updated ;o)
