### ISSUE TITLE
Download services not displayed in the INSPIRE geoportal

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-geoportal#59]
We encountered the error reported in the issue #57, e.g. for the dataset with the title "Ciclovia tirrenica".
Also in this case the Resource linkage checker tool returns the same error, i.e.

![immagine](https://user-images.githubusercontent.com/7059416/140419609-0f2fcd50-d59d-48e6-8b75-db26a6771e58.png)

although dataset and services metadata are successfully validated with the INSPIRE Reference validator. The metadata records are the following:

- dataset metadata: https://geodati.gov.it/RNDT/rest/document?id=r_liguri:D.2091:2020-11-06
- view service metadata: https://geodati.gov.it/RNDT/rest/document?id=r_liguri:D.2091.VS:2020-11-06
- download service metadata: https://geodati.gov.it/RNDT/rest/document?id=r_liguri:D.2091.DS:2020-11-06

Could you provide us with the reason and more details about this behaviour and what we can do to solve this issue?

Thank you,
Antonio

**Comment by jrc-inspire** [comment]
We have taken note of the potential issue in the current INSPIRE Geoportal, which share certain commonalities with other issues where the nature of INSPIRE services are not properly recognized by the current INSPIRE Geoportal ([#20](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/20), [#22](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/22), [#34](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/34), [#59](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/59), [#21](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/21)) that need to be properly analysed. 
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
We will do our best for addressing the issue in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the a drop in the number of downloadable datasets in the Geoportal. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) was dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
