### ISSUE TITLE
INSPIRE linkage checker API and its linkage / usage to calculate monitoring indicators

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#62]
Dear EC INSPIRE team,

is there an possibility to access the INSPIRE linkage checker
https://inspire-geoportal.ec.europa.eu/linkagechecker.html
via API? 
If yes is any documentation (e.g. Swagger) available which could be used to test it?

Thank you, 
on behalf of SK INSPIRE team
Martin T.

**Comment by jrc-inspire** [comment]
We regret to inform you that there is no API access available for using the current Linkage checker.
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.
Therefore, we will consider your request in the future in the context of the redesigned INSPIRE Geoportal based on GeoNetwork.

**Comment by MartinTuchyna** [comment]
Does the new Geonetwork based INSPIRE Geoportal offers a public API endpoint which offers capabilities to check the correct linkages among metadata for spatial data set and networks services, in order to verify whether a member state resources are correctly linked, and those links are correctly working to ensure the INSPIRE Geoportal compliance? In other works, we want to use it to provide checks for Slovak data providers which will result in viewable and downloadable datasets from within INSPIRE Geoportal. 

Rationale behind:

We have this sample scenario, where we have got a dataset for Transportation Network in Slovakia:
MD links for resource: [Dataset](https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00003328/SK-SSC-INSPIRE-RoadNetwork) [ViewService](https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00003328/inspire_view_service) [DownloadService](https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00003328/inspire_download_service)

which does not get marked as viewable and downloadable from within INSPIRE Geoportal here: https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102%2Fservices%2F1%2FPullResults%2F1-20%2Fdatasets%2F14&expandedSection=metadata 
 
![obrázok](https://user-images.githubusercontent.com/6195936/215736110-3dda66cc-dcb0-48a6-abb3-adb657222693.png)

whilst results of Linkage checker shows dataset shall be Viewable and Downloadable:
 
![obrázok](https://user-images.githubusercontent.com/6195936/215736214-af8a1482-5877-4d54-8438-9577edeea114.png)

With that we need to understand why, since the provider proved all the linkages are done correctly, however we cannot verify since we do not understand exactly what Linkage Checking technically does at your end.

As national INSPIRE coordinator, we would like to provide them with clear guidance and support, why last check in current Linkage checker indicates 
 
![obrázok](https://user-images.githubusercontent.com/6195936/215736301-3975af11-2506-4cc1-b9a5-6765df1c5c86.png)
as reported in this issue:
https://gitlab.com/mzpsr/podpora-inspire-implement-cie/podpora-povinn-ch-os-b/mdv-sr/ssc/-/issues/1#note_1237453613
