### ISSUE TITLE
Stucked harvest 4 SK CSW @ EC GP Harvester

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#63]
Dear EC INSPIRE team, 

- [ ] a description of the steps to reproduce your issue

could you please check the lastest harvest of SK discovery service?

We have initiated harvest yesterday morning, but there is no progress visible so far.

- [ ] the browser and version used

Firefox 94.0.1 

- [ ] a screenshot illustrating the problem

![obrázok](https://user-images.githubusercontent.com/6195936/140932780-2ef0fd7c-8b8a-4371-bbc4-f311894addaf.png)

- [ ] the URL of the page

https://inspire-geoportal.ec.europa.eu/harvestconsole/private.jsp?ticket=ST-19693471-DeeLHbgYDubVFPZzqLYDAIWXzR1agkmlKCt5i17lcpXG0YCCJKEUNuEuQGzL6zdR42yW4nHOFoDgMQctQzdJMrR-yntOf97TTHq1VtrzozxZOBm-szIffLtDStpY5aLnblWM5BzWzKDyjeUgUF2CKbZy5BZeMhV2neti3XXznkyiO4NjfILloGtTt3hdUO2G1uLE2iS 

- [ ] in case a resource is involved (e.g. specific metadata), provide the related file identifier

N/A

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources. 
Despite the late receipt of this issue, we have taken note of it and will do our best for addressing it in time for the upcoming INSPIRE Monitoring considering its impact.

**Comment by jescriu** [comment]
Dear @MartinTuchyna ,
We restarted the INSPIRE Geoportal services and manually executed the harvesting from the SK endpoint, which seem to be successful.
Please, check and let us know in order to close this issue.

**Comment by jescriu** [comment]
Please see also #60.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 

thank you for the reset and re-harvest of the national SK CSW.

**Comment by jescriu** [comment]
Perfect. I proceed to close this issue.
