### ISSUE TITLE
DK: Linkage checker fails even though metadata validates successfully with INSPIRE validator

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-geoportal#64]
I used the linkage checker for metadata of a dataset and the linkage aspect "A Download link has been determined" failed. In the info box next to it, users are asked to open an issue if the linkage aspect fails but the data successfully validates in the INSPIRE validator. This is the case.
![grafik](https://user-images.githubusercontent.com/34163838/140932946-5312ef65-83b4-4861-8b9b-1a778e67a98b.png)

These are the resources used:
* dataset metadata https://www.geodata-info.dk/srv/api/records/59af29ff-e5a9-4aee-a923-e903faed674f/formatters/xml
* WMS metadata https://www.geodata-info.dk/srv/api/records/62bd0681-f5ae-4d57-a0da-d2be96b1f8a9/formatters/xml
* Atom Feed metadata https://www.geodata-info.dk/srv/api/records/24ca1795-9707-4098-adbb-fe64f2f33405/formatters/xml

These are the test results form the INSPIRE Validator:
* dataset metadata https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDc9e70b16-a6b6-4f32-8096-4dff27e19940
* WMS metadata https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID0e5bb5fb-5a21-41b7-bbdb-15f83010b053
* Atom Feed metadata https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID77a1c9ca-136d-4963-a4a8-47277ebf4d25

Could you please let me know why the test of the linkage checker is failing in this case?

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources. 
Despite the late receipt of this potential issue affecting in the current Geoportal, we have taken note of it and will do our best for addressing it in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jescriu** [comment]
Dear @JohannaOtt and @laers,
As mentioned in #65, we will try to analyse this issue as soon as possible.

**Comment by JohannaOtt** [comment]
The same is true for these resources in case examples help to investigate the issue. I won't attach the validator results again, but they all passed:
* dataset metadata https://haleconnect.com/services/bsp/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a/md/dataset/dataset1
* WMS metadata https://haleconnect.com/services/bsp/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a/md/service/id_wms
* WFS metadata https://haleconnect.com/services/bsp/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a/md/service/id_direct_download

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

Therefore, open issues affecting the current INSPIRE Linkage Checker (being part of the infrastructure tools associated to the current INSPIRE Geoportal backend) will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by JohannaOtt** [comment]
> The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

@jrc-inspire Did the migration already happen or can you provide a timeline on when this will take place?

**Comment by JohannaOtt** [comment]
@jrc-inspire Could you please comment on the current state/timeline here?
