### ISSUE TITLE
PT: Geoportal harvesting problem

### ISSUE THREAD

**Issue by dfurtado-dgt** [INSPIRE-MIF/helpdesk-geoportal#67]
Dear INSPIRE Team,

Could you please check the lastest harvest of Portugal, because the service harvest seems to be stalled.
![PT-HarvestingProblem](https://user-images.githubusercontent.com/76490621/141960046-6129d200-9561-4f6d-9f22-4111bd59f047.png)

Best regards.

**Comment by jescriu** [comment]
Dear @dfurtado-dgt,
We restarted the INSPIRE Geoportal services and manually executed the harvesting from the PT endpoint, which seem to be successful.
Please, check and let us know in order to close this issue.

**Comment by dfurtado-dgt** [comment]
Dear Jordi,

Thanks for your help.
I confirm that the harvesting was successfully performed and everything is working correctly.

Best regards.
Danilo Furtado

**Comment by jescriu** [comment]
Many thanks for the confirmation @dfurtado-dgt - I will share your positive feedback to the rest of the team which is working on it.
I proceed to close this issue.
