### ISSUE TITLE
EC GP visibility of the WXS services availability and linkage check

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#68]
Please replace these lines with a brief summary of your issue and the expected
behaviour.

To help us investigate the issue, you may want to include:

- [ ] a description of the steps to reproduce your issue
Despite the successfull results of the checking the links in Linkage checker after the harvest of the metadata to the EC GP
there are no links for the view and download services.

Resource ID: 

https://data.gov.sk/set/rpi/gmd/42181810/4F19E731C80F0BB2E0530110000AF35A

Title:
INSPIRE PD 8,01 NDS Spravované/obmedzené/regulované zóny a jednotky podávajúce správy (strategické hlukové mapy, zóny hlukového obmedzenia)

- [ ] the browser and version used
Firefox 94.0.1 (64-bit)

- [ ] a screenshot illustrating the problem

![obrázok](https://user-images.githubusercontent.com/6195936/142397621-58aeaf4c-5ac6-4516-92f5-c88cfdada886.png)

![obrázok](https://user-images.githubusercontent.com/6195936/142397698-8f6129fa-f4f2-4c82-a868-5fed92e29678.png)

- [ ] the URL of the page

- [ ] in case a resource is involved (e.g. specific metadata), provide the related file identifier

MD urls used in INSPIRE Linkage checker:

MD DS: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/42181810/4F19E731C80F0BB2E0530110000AF35A
MD WS: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/42181810/CEB58206DCC31BA8E0530110000AF518
MD DS: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/42181810/CEB58206DCC41BA8E0530110000AF518

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of a drop in the number of viewable datasets in the Geoportal. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Excuses for any inconvenience caused.
