### ISSUE TITLE
Download link could not be determined

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-geoportal#69]
Dear all,

we also have a problem with Download Links like other countries and a lot of our WFSs are not recognized by the INSPIRE Geoportal because of this error. Other countries seem to have this problem as well , and it affects everyone’s Monitoring results. 

Can anyone take a look even though we know everyone is in a hurry because of the Monitoring? Attached is a display of harvesting console data which shows that view and download services are available, but the download link isn't.

[INSPIRE Geoportal Harvest console.pdf](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/7586727/INSPIRE.Geoportal.Harvest.console.pdf)
[INSPIRE Geoportal Harvest console_2.pdf](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/7586729/INSPIRE.Geoportal.Harvest.console_2.pdf)

Seems many others have similar or the same problem - also see in issues #22 , #34 , #57 , #64

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of a drop in the number of downloadable datasets in the Geoportal. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jescriu** [comment]
Dear @Ana-SGA,

Thank you for your patience.

Our INSPIRE Geoportal IT team made (quite recently) some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries through the harvest console.

A new harvest of the Croatian discovery service endpoint was executed on 4th May, providing better results - See below:
![image](https://user-images.githubusercontent.com/22743378/168697232-81b3e057-0b7a-4872-9c06-03d013c44f10.png)

These results are still pending to be published from your side. Please, have a look and feel free to provide any additional feedback. I hope you are satisfied with the results.

Please, let me know if the links through the view and download services for the datasets you reported on 23rd Nov 2021 are now available.
All the best.

**Comment by Ana-SGA** [comment]
Dear @jescriu ,

thank you - the results are now much better. Mostly the Download link is now available except for a smaller part of services, eg https://geoportal.kulturnadobra.hr/servisi/grafika/ProtectedSites/wfs?service=WFS&request=GetCapabilities - can you maybe take a look? The Validator says that Stored Query definition isn't correct - could that be the problem for missing the Download link?

Thanks again,
Ana

**Comment by jescriu** [comment]
Dear @Ana-SGA,
Thank you for your positive feedback, with which I will close this issue.
As said in our bilateral meeting today, please feel free to use this channel to ask any remaining questions regarding specific services.
All the best.
