### ISSUE TITLE
Geoportal/Linkage Checker: Problems with linkage recognition

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#7]
During a Harvesting respectivly a linkage check one dataset has problems with its download linkage.
![image](https://user-images.githubusercontent.com/45065613/101891924-fcfb4b00-3ba2-11eb-9b33-69654807289a.png)

When i use the linkage checker, all checks are red despite having an valid etf validation for this metadata.
![image](https://user-images.githubusercontent.com/45065613/101891807-d2a98d80-3ba2-11eb-895b-fb68e6ab5dcd.png)

![image](https://user-images.githubusercontent.com/45065613/101891963-0c7a9400-3ba3-11eb-83c9-05369e889685.png)

dataset-MD: https://geoportal.inspire.gv.at/metadatensuche/srv/api/records/55e494dd-e0af-4806-95d6-86e30dde0504/formatters/xml
View service MD: https://geoportal.inspire.gv.at/metadatensuche/srv/api/records/dcb7c708-98ce-4348-9ec3-59ab0cf7d73d/formatters/xml
Download Service MD: https://geoportal.inspire.gv.at/metadatensuche/srv/api/records/bea12cac-1c68-4e07-9a40-d0e765185a27/formatters/xml

Do you know what is the problem with this linkage?

Thanks, Manuel

**Comment by dartasensi** [comment]
Dear @manilly,

thank you for reporting this bug. I can confirm the issue that affected only the UI rendering of the result data coming from the backend services. I've already updated the javascript code to handle the slightly different response it receives after analysing your fast services.

Best regards,
Davide on behalf of JRC INSPIRE Support team
