### ISSUE TITLE
Harvest console - ATOM Feed Services

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk-geoportal#70]
Dear

I hope you are all right.

I work for Belgian Federal Administration. Several Federal Administrations maintain some INSPIRE ATOM Feed Services. We have all noticed the same problem since our last harvest (it happened yesterday): the INSPIRE ATOMS are correctly read but not further than the second entry tag.

As a result, the datasets referenced in the next entry tags are not correctly taken into account and they are not anymore downloadable through the INSPIRE geoportal. The amount of downloadable datasets has fallen since that last harvest. We tried it again this morning and the problem is still there.

I took some screenshots from the full INSPIRE interoperability report (https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-b285fced-4eb6-11e8-a459-52540023a883_20211125-153202/services/1/PullResults/) of the concerned ATOM Services.

![image](https://user-images.githubusercontent.com/80756452/143571000-6dee840d-b9a3-491f-97f4-7b327992e2bf.png)

![image](https://user-images.githubusercontent.com/80756452/143571023-17a8ff22-46e9-4fdf-b714-257deac31810.png)

![image](https://user-images.githubusercontent.com/80756452/143571038-e42ff7d6-97cd-4aa9-a870-91ed374772ac.png)

As you may see on these three different ATOM, the two first referenced datasets are well read  and accessible but the third onse and the next ones are not taken into account.

I didn't modify anything in my personal ATOM (the first one) and these ATOM files are all created with a stable routine. I think something changed (for a bad) in the way the geoportal harvest, read and take into account the content of the entry tags of the INSPIRE ATOM.

As you may know, the next INSPIRE Reporting is about to begin. Could you check and fix that problem as soon as possible? I think the problem is most critical because of its potential impacts on all the Member States' results.

Regards,

Benoît Fricheteau

Please replace these lines with a brief summary of your issue and the expected
behaviour.

To help us investigate the issue, you may want to include:

- [ ] a description of the steps to reproduce your issue
- [ ] the browser and version used
- [ ] a screenshot illustrating the problem
- [ ] the URL of the page
- [ ] in case a resource is involved (e.g. specific metadata), provide the related file identifier

**Comment by jescriu** [comment]
Dear @bfrichet3,
We took note of this issue and will try to solve it as soon as possible.
It is more than probably correlated with other issues already reported in the repository, in which our IT Geoportal team is already working hard to fix them.
We will keep you posted.

**Comment by bfrichet3** [comment]
Dear Jordi

Thank you very much for you qucik reaction. We appreciate your hard work in order to fix these problems.

Regards and stay safe,

Benoît

**Comment by bfrichet3** [comment]
Dear @jescriu 

In order to be sure, the National Geographic Institute switched two entry tags in its own ATOM Feed (the second one in the previous picture).

![image](https://user-images.githubusercontent.com/80756452/143600394-ef280b7f-621a-48e8-a692-54551021252c.png)


As you may see, only the two first entry tags are really screened by the portal. We can now exclude that comes from a problem within our entry tags because the entry tag of "Road Transport Network" wasn't available as it was at least on third position and it has been avalaible since it is the second entry tag listed in the ATOM Feed. 

Regards

**Comment by bfrichet3** [comment]
Dear @jescriu

It seems that the geoportail correctly reads our ATOM again.

![image](https://user-images.githubusercontent.com/80756452/144901865-aed1d25c-b9cb-4604-ba4e-335bb39522aa.png)


As you may see here, many entry tags are found in that download service. I am still quite surprised you didn't inform us that the problem has been solved. Could you confirm you fix that bug or did something else happen?

Regards,

**Comment by jescriu** [comment]
Dear @bfrichet3,
We have been working in parallel in solving several other issues with similar impact. 
Could you share the uuid of your original metadata?

**Comment by bfrichet3** [comment]
Dear @jescriu,

That's the UUID of the download service metadata: 5cfe8a91-3dc9-4cf6-a40a-6a6d6f3124ab.

I would thank you and all the INSPIRE development team for your commitment in this matter.

Nevertheless, I would put your attention, and put the attention of all the JRC INSPIRE team on these elements:

1) without the old "INSPIRE Full Operating Capability Testing" tool, it would have been very difficult for the federal Belgian team to identify the problem, as the problem came from the way the INSPIRE Infrastructure reads the services. That problem is not findable through the new "Harvest console monitoring tool" as that console shows the issues **from a data sets centric perspective** (see image below).

2) both reports ("INSPIRE Full Operating Capability Testing" and the new one) are only accessible for logged-in people. This is a big concern for me as many other people could faster find and fix their own issues if they had a direct access to these global interoperabilty reports.

That's why I would suggest the INSPIRE JRC team to make the "Harvest console monitoring tool" more use friendly and compiant with TG 2.0 and I would suggest the INSPIRE JRC team to make all these reports accessible for everyone.

Regards

![image](https://user-images.githubusercontent.com/80756452/144996731-81d64bb3-bae3-4df0-afbe-fdeef4e6566a.png)

**Comment by jescriu** [comment]
Thank you for your contribution @bfrichet3,
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. The current Geoportal will be dismissed soon, so your recommendations and proposals for improvement should be considered in the context of the redesigned INSPIRE Geoportal based on GeoNetwork, in our joint effort to make it evolve.

**Comment by jescriu** [comment]
Dear @bfrichet3 - I confirmed with our IT Geoportal team that some of the transversal corrections we made to the INSPIRE Geoportal code have more than probably solved this issue.
Therefore, I proceed to close this issue. Please reopen it if the issue appears again.
