### ISSUE TITLE
Problem harvesting from SE

### ISSUE THREAD

**Issue by Privatmijoha** [INSPIRE-MIF/helpdesk-geoportal#71]
Big problems in Inspire Geoportal harvesting routines?
The harvesting does not work as it should. Please help!
The published result from SE November 8 is ok. (243,194, 216) 
November 19 we got a poor result ( 241,134, 213) = specially bad result for downloading even though the download feeds/services works fine in the published result from November 8 available in Inspire Geoportal. (also they work fine in the portal in Sweden, and the feeds/services we lost  in the harvest November 19 has been okay in the "control system" in the Inspire Geoportal for more than a year!) 

Today, november 26 we tried a new harvest and got an extremely poor result (154,39,68).

https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-adae82ae-5364-11e8-bd03-52540023a883_20211126-100802/services/1/PullResults/ 

Still everything works fine in the portal in Sweden.  

Please let us know if we have to correct anything, and how.

Kind regards,
Mikael

**Comment by jescriu** [comment]
@Privatmijoha - Thank for posting the Sweden issue using this dedicated thread.
This problem is correlated with other Geoportal issues already spotted by other European catalogues nodes, in which our IT Geoportal team is already working hard to fix them.
We will keep you posted on any progress using this thread.

**Comment by Privatmijoha** [comment]
Great! Thank you @jescriu.

**Comment by MatAlps** [comment]
Same issue for Luxembourg regarding the download links checking.
For records/downloadable/viewable:
* harvest 11/10 : 306 / 267 / 257
* today 27/11 : 308 / 51 / 273

(We were expecting the improvement in viewable service)

**Comment by Privatmijoha** [comment]
@jescriu: Looks like harvesting Sweden works fine again. 
Thank you!

**Comment by jescriu** [comment]
Dear @Privatmijoha (and @MatAlps),
As you noticed, our Geoportal IT team already implemented a fix for this bug. We were just testing the fix with other endpoints before contacting you on it.
I proceed to close this issue. Please feel free to comment / open again if needed.
Thank you for your patience.
