### ISSUE TITLE
CZ: Harvesting not finished after 3 days 

### ISSUE THREAD

**Issue by madlenkk** [INSPIRE-MIF/helpdesk-geoportal#72]
Dear Geoportal team,
I would like to ask you to restart the harvest of CZ discovery service - it is stucked for three days.

![image](https://user-images.githubusercontent.com/8487830/144204833-35909ab8-2167-4f4a-a24b-e3787072b3db.png)

It seems it is similar problem as #65 and #63.

Thank you so much,
Magdalena

**Comment by jescriu** [comment]
Dear @madlenkk,
Just to let you know that out IT Geoportal team is working on it - We restarted the INSPIRE Geoportal services this morning but we are still managing some improvements and related testing. 
We will manually execute the harvesting from the CZ endpoint once these are ready.
Please wait till we have done this process. We will keep you posted.

**Comment by madlenkk** [comment]
Dear @jescriu ,
thank you very much for the quick response!
Magdalena

**Comment by madlenkk** [comment]
Dear @jescriu ,
please let me know, if I may run the harvest of CZ catalog already.
Thanks,
Magdalena

**Comment by jescriu** [comment]
Dear @madlenkk,
Our IT Geoportal team put in production some enhancements to the INSPIRE Geoportal code, and already scheduled a new harvest of your endpoint just afterwards. It finished earlier this morning (so no need for you to start a new harvest).
Please have a look at the results in the harvest console and let us know.

**Comment by jescriu** [comment]
By the way @madlenkk, while analysing the issue our team identified that, from a total of 44 ATOM services reported, 4 of them were seriously slowing down the performance of the INSPIRE Geoportal: 2 of them with 6257 entries, and 2 of them with 13075 entries - with the following metadata fileIdentifiers:

1. "CZ-00025712-CUZK_ATOM-MD_CPX" - ATOM Service: "https://atom.cuzk.cz/CPX/CPX.xml".
2. "CZ-00025712-CUZK_ATOM-MD_AU" - ATOM Service: "https://atom.cuzk.cz/AU/AU.xml".
3. "CZ-00025712-CUZK_ATOM-MD_BU" - ATOM Service: "https://atom.cuzk.cz/BU/BU.xml".
4. "CZ-00025712-CUZK_ATOM-MD_CP" - ATOM Service: "https://atom.cuzk.cz/CP/CP.xml".

It would be more useful in terms of usability of such services to rethink the predefined units in which you serve the data.

**Comment by madlenkk** [comment]
Dear @jescriu,
Thank you very much for the harvest and the analysis - I will forward the message to the relevant provider asap.
Magdalena
