### ISSUE TITLE
Linkage not estabilished between the Atom and 'Ruimtelijke plannen' Data Set 

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-geoportal#75]
When validating the dataset 'Ruimtelijke plannen' using the Inspire linkage checker, this results in not being able to succesfully link the dowload service to the dataset.

The following steps on the result page don't have a succesful result:
- Linkage has been estabilished between the Download Service and Data Set
- A Download link has been determined

![image](https://user-images.githubusercontent.com/22592588/144850718-24ead582-7b22-4584-8daf-379d45c5b5c1.png)

The validator is started with the following metadata references:
- dataset MD: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/xml.metadata.get?uuid=17716ed7-ce0d-4bfd-8868-a398e5578a36
- view service MD: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/xml.metadata.get?uuid=6c62e0a5-c215-4e47-94b0-a239e264417d
- download service MD: https://www.nationaalgeoregister.nl/geonetwork/srv/dut/xml.metadata.get?uuid=dc9fbc85-1263-4a1b-b001-7be701a6039e

The linkage checker result for validating the above metadata and services can be analysed in this evaluation report: https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-5f2b1bdb-5691-11ec-9bed-0050563f01ec_20211206-133810/

The dataset and download service metadata has been succesfully validated using the reference validator.
The linkage has been manualy checked using the workflow below:
![image](https://user-images.githubusercontent.com/22592588/144851511-77852c4e-a7f1-42f0-b27d-bd5f4595caa2.png)

According to the above, a linkage between the dataset and the download service should be possible to be determined, but the linkage checker was not able to do this.
Can we please get some insight into why the linkage could not be determined, because the evaluation report does not give a clear insight into any possible causes.

**Comment by idevisser** [comment]
When I look in the service feed I see the following link to dataset metadata;

https://www.nationaalgeoregister.nl/geonetwork/srv/dut/csw?service=CSW&amp;version=2.0.2&amp;request=GetRecordById&amp;outputschema=http://www.isotc211.org/2005/gmd&amp;elementsetname=full&amp;id=17716ed7-ce0d-4bfd-8868-a398e5578a36

When I look in the metadata of the service, I see the following in the operatesOn element;

<srv:operatesOn uuidref="e2318c58-b1e6-4621-9c77-33b8a1fd0e76" xlink:href=https://www.nationaalgeoregister.nl/geonetwork/srv/dut/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=17716ed7-ce0d-4bfd-8868-a398e5578a36#MD_DataIdentification/>

The metadata record is  not exactly the same way referenced

**Comment by mwjsanders** [comment]
Thanks @idevisser, for taking the time to analyse this ticket.

We have aligned the dataset metadata references in the service feed and in the service metadata, so that they are exactly the same. 
The SpatialDatasetIdentifier namespace in the service metadata is also set to the value used in the dataset metadata (http://kadaster).
We waited till this namespace update in the service feed was also updated in the [openSearch Description](https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/dc9fbc85-1263-4a1b-b001-7be701a6039e/OpenSearchDescription.xml) (which is rebuild every night) and ran the linkage checker again for this dataset.
Unfortunately we get the [same result](https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-4962eb35-58bf-11ec-9bed-0050563f01ec_20211209-081153/) in that the following steps were not succesfull:

- Linkage has been estabilished between the Download Service and Data Set
- A Download link has been determined

**Comment by idevisser** [comment]
@mwjsanders, please use the instructions and check also if the metadata URL is exactly the same

**Comment by JLSchaap** [comment]
@idevisser  We followed the instructions. Can you elaborate on the errors in the evaluation report of the following service
https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/dc9fbc85-1263-4a1b-b001-7be701a6039e 

![validation](https://user-images.githubusercontent.com/23397617/145378806-29a8aedf-d2c5-4be1-88c5-08d2c17688ab.png)

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

Therefore, open issues affecting the current INSPIRE Linkage Checker (being part of the infrastructure tools associated to the current INSPIRE Geoportal backend) will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
