### ISSUE TITLE
Harvesting status page in Geoportal: no data available

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-geoportal#77]
Hi.

[harvesting status page](https://inspire-geoportal.ec.europa.eu/harvesting_status.html) doesn't show which catalogue has been harvested and when:
![image](https://user-images.githubusercontent.com/38787131/145539051-359dbe20-8270-4587-ab16-539b2ebaa0a0.png)

Could you please take a look at it?

Thanks!

**Comment by jescriu** [comment]
Dear @DeordD,
Thanks for spotting. We will look at it as soon as possible.

**Comment by jescriu** [comment]
Dear @DeordD - The issue is solved now.
Thanks for spotting.
