### ISSUE TITLE
Problem with harvesting (LUX): availability through view services randomly reported missing although "Resource linkages checker tool" shows that it is available

### ISSUE THREAD

**Issue by MatAlps** [INSPIRE-MIF/helpdesk-geoportal#79]
* In our last harvest (Tue Dec 14 2021 18:09:02 GMT+0100), we have a dozen dataset where view availability is reported missing while the "Resource linkages checker tool" shows it works. One example of concerned dataset: https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/c8c7847a-4856-4c8d-948d-6055b5067b56.

* Over the few last harvests in recent days the problem has not always happened while nothing has changed on our side (Most of the time it does not happen)

* We believe it could be linked to the fact that this dozen datasets are available through the same view service (https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/06ce754e-4240-4753-8095-36159b4dd227). Could it be that the harvest linkage checker overwhelmes the view service by checking the linkage of the datasets in parallel, in alphabetical order?

**Comment by MatAlps** [comment]
Hi,

Could you have a look at this?

We still have the problem. 

In our last harvest the following record https://catalog.inspire.geoportail.lu/geonetwork/srv/eng/catalog.search#/metadata/2a18c162-b9fd-4097-b367-e47de238f4f5 is found without download & view link:
![image](https://user-images.githubusercontent.com/53038426/159919954-63567a39-0fda-4781-8965-80ad0861fa93.png)

But performing the test manually with the link checker https://inspire-geoportal.ec.europa.eu/linkagechecker.html shows no issue:
![image](https://user-images.githubusercontent.com/53038426/159920183-2e2c2195-5041-4987-8ae1-bbb9d22b5594.png)
With 
* dataset MD : https://catalog.inspire.geoportail.lu/geonetwork/srv/api/records/2a18c162-b9fd-4097-b367-e47de238f4f5/formatters/xml?approved=true
* download service MD : https://catalog.inspire.geoportail.lu/geonetwork/srv/api/records/1751bce0-bc2f-42d2-8652-9e0e8d719c9f/formatters/xml?approved=true
* view service MD : https://catalog.inspire.geoportail.lu/geonetwork/srv/api/records/c5edca0f-4074-4c00-963e-b607fc93e67b/formatters/xml?approved=true

Could you:
- Confirm that there are no issues in the way I make my test with the linkage checker
- Add a cache to the harvest console? If my hypothesis that the root cause is the overwhelming of our view/download services by the harvest console then it should solve the issue.

Thx!

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the reported drop in the number of viewable datasets for your endpoint. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by MatAlps** [comment]
Hi,

Thanks a lot for your answer.
We are checking our logs and found indeed a lot of timeouts, NGINX status 499 "Client closed connection".
Also that the calls from the validator are most of the time unique (very good).

Those 499 happen when the client (=validator in this case) close the connection.
We cannot at the moment have the request time on our side - we are working on it.
In the meanwhile, it would help us a lot if you could tell us what timeout value in ms the validator uses before closing the connection. Would you have this information readily available for us?

Thx in advance

Mathieu

**Comment by jescriu** [comment]
Dear @MatAlps,
We will analyse your request and we will come back to you as soon as possible.
Best,
Jordi

**Comment by MatAlps** [comment]
Dear @jescriu ,

Thx for your answer.

In the meanwhile we have measured 5 seconds timeout for GetMap, and 10 seconds for GetCapabilities.
We are working to improve our side to be able to provide response times below those values during a harvest.

Worth noting: we observed that during a harvest, our geoserver, that is distributing allmost all the INSPIRE layers for LUX, receives more than 500 requests in a few minutes. One could argue that this generates unusual conditions of use, while the 5 and 10 seconds timeouts are expected for normal conditions of use. So it is arguable that for centralized INSPIRE infrastructures, the harvester excessively overloads the visualisation service to be able to fairly assess its accessibility.

While we are investing to meet the current requirements, we would like to know your opinion on the topic. Do you agree? Have you received similar feedback from other countries?

Best regards,

Mathieu

**Comment by jescriu** [comment]
Dear @MatAlps,
Regarding your post+question quoted below:

> We are checking our logs and found indeed a lot of timeouts, NGINX status 499 "Client closed connection".
> Also that the calls from the validator are most of the time unique (very good).
> 
> Those 499 happen when the client (=validator in this case) close the connection.
> We cannot at the moment have the request time on our side - we are working on it.
> In the meanwhile, it would help us a lot if you could tell us what timeout value in ms the validator uses before closing the connection. Would you have this information readily available for us?

Just to double-check with you that you are referring to the INSPIRE Reference Validator, and not to the INSPIRE Geoportal - Could you confirm? Not sure if we are mixing 2 different topics here.

Regarding you last post quoted below:

> In the meanwhile we have measured 5 seconds timeout for GetMap, and 10 seconds for GetCapabilities.
> We are working to improve our side to be able to provide response times below those values during a harvest.
> 
> Worth noting: we observed that during a harvest, our geoserver, that is distributing allmost all the INSPIRE layers for LUX, receives more than 500 requests in a few minutes. One could argue that this generates unusual conditions of use, while the 5 and 10 seconds timeouts are expected for normal conditions of use. So it is arguable that for centralized INSPIRE infrastructures, the harvester excessively overloads the visualisation service to be able to fairly assess its accessibility.
> 
> While we are investing to meet the current requirements, we would like to know your opinion on the topic. Do you agree? Have you received similar feedback from other countries?

I agree that this worths a discussion, since it not the aim of the INSPIRE Geoportal to diminish the performance of data providers' services. I will bring this topic for internal discussion as soon as possible, also taking into account the established quality requirements for INSPIRE services.

At the moment, we have not received similar feedback from other MS, but it worths investigating if these timeouts could be causing a decrease in the downloadable and viewable datasets indicators.

Could you share with us the logs of your services?

Best,
Jordi

**Comment by MatAlps** [comment]
Hi Jordi,

Thx for your answer and the intention of bringing this topic for internal discussion.

I am talking about what happens when we launch an harvest from the [harvest console](https://inspire-geoportal.ec.europa.eu/harvestconsole/) of the luxembourg INSPIRE catalog. I recognize that I did not make that clear.

Please find the logs we have for an harvest done on 21/04 : [79 logs 21-04-2022 harvest LUX.xlsx](https://github.com/INSPIRE-MIF/helpdesk-geoportal/files/8564963/79.logs.21-04-2022.harvest.LUX.xlsx)

Best regards,

Mathieu

**Comment by jescriu** [comment]
Dear @MatAlps,
Thank you for the clarification. Therefore, you only refer to the INSPIRE Geoportal harvesting process.
I will share the logs with our INSPIRE Geoportal IT team, for evaluation.
All the best.

**Comment by jescriu** [comment]
Dear @MatAlps,

Thank you for your patience.

Our INSPIRE Geoportal IT team made (quite recently) some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries through the harvest console.

A new harvest of the Luxembourg discovery service endpoint was executed on 5th May, providing better results - See below:
![image](https://user-images.githubusercontent.com/22743378/168693406-08cd2993-e50d-48f7-9945-1332b7d7d279.png)

As part of the analysis made for the improvements highlighted above, we considered if the current processes of the INSPIRE Geoportal to check viewability and downloadability of datasets could be hindering the availability of the own services being checked. Finally, this seemed to be not the issue this time.

However, thanks to you valuable analysis, we identified aspects of improvement for the mentioned processes. We will for sure take them into account in the future, as part of the improvement of the new INSPIRE Geoportal backend based on GeoNetwork, which will be made available soon.

All the best.
