### ISSUE TITLE
INSPIRE metadata catalogue: CSW Filter doesn't work as expected

### ISSUE THREAD

**Issue by DeordD** [INSPIRE-MIF/helpdesk-geoportal#8]
Hi all,

I'm trying to request a specific MD record using title and property name (FID is not working because of the fact, that the fileIdentifier is changed in INSPIRE catalogue).

I'm using a POST-request on CSW-Endpoint https://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGCCSW202/DE

POST:

```
<?xml version="1.0" encoding="UTF-8"?>

<csw:GetRecords service="CSW" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" xmlns:gml="http://www.opengis.net/gml" maxRecords="10" startPosition="1" outputSchema="http://www.isotc211.org/2005/gmd" resultType="results">
            <csw:Query typeNames="csw:Record">
                        <csw:ElementSetName>full</csw:ElementSetName>
                        <csw:Constraint version="1.1.0">
                                    <ogc:Filter>
                                               <ogc:And>
                                               <ogc:PropertyIsEqualTo>
                                                           <ogc:PropertyName>Title</ogc:PropertyName>
                                                           <ogc:Literal>DLM50</ogc:Literal>
                                               </ogc:PropertyIsEqualTo>
                                               <ogc:PropertyIsEqualTo>
                                                           <ogc:PropertyName>OrganisationName</ogc:PropertyName>
                                                           <ogc:Literal>LGL Baden-Württemberg</ogc:Literal>
                                               </ogc:PropertyIsEqualTo>
                                               </ogc:And>
                                   </ogc:Filter>
                        </csw:Constraint>
            </csw:Query>
</csw:GetRecords>
```

The result from CSW-catalog contains 10 results with the following title:

INSPIRE BW Verkehrsnetze ATKIS DLM50
INSPIRE BW Hydro - Netzwerk ATKIS DLM50
INSPIRE BW Hydro - Physische Gewässer ATKIS DLM50
INSPIRE-WFS BW Geografische Bezeichnungen ATKIS DLM50
INSPIRE-WFS BW Verkehrsnetze ATKIS DLM50
INSPIRE-WMS BW Verwaltungseinheiten ATKIS DLM50
INSPIRE-WFS BW Hydro - Netzwerk ATKIS DLM50
INSPIRE-WFS BW Geografische Bezeichnungen ATKIS DLM50
INSPIRE-WMS BW Hydro - Physische Gewässer ATKIS DLM50
INSPIRE-WFS BW Hydro - Physische Gewässer ATKIS DLM50

I expected only results with the exact title "DLM50" but it seems that there are also results with title LIKE *DLM50*.

P.S.
Further discussion on this can be found in INSPIRE Community Forum:
https://inspire.ec.europa.eu/forum/discussion/view/264843/inspire-catalog-csw-filter-not-correct#elgg-object-270071

**Comment by dartasensi** [comment]
Dear @DeordD ,

the OGC Filter support of the INSPIRE Geoportal CSW implementation is minimal, therefore we can't offer full support to the "complex" logic you expressed within your filter expression.

Kind regards,
Davide
