### ISSUE TITLE
Linkage Checker improvements: show requests

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#80]
Dear Linkage Checker Team,
sometimes we have problems to find out what the problems are, when checking the linkages between services and data. In our case it was the linkage between WFS and Data. We had to monitor our system to find out which requests were made during a linkage check.

It would make sense to show the requests actually sent by the linkage checker to the queried systems, as this would make checking a lot easier for the operator. It also would be enough to only show the failed requests. With the existing outputs from the "Resource linkages checker tool" it's not easy to find the exact problem.

Thanks, Manuel

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will be available soon.

Therefore, open issues affecting the current INSPIRE Linkage Checker (being part of the infrastructure tools associated to the current INSPIRE Geoportal backend) will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
