### ISSUE TITLE
RO: Certificate issue 

### ISSUE THREAD

**Issue by magearu** [INSPIRE-MIF/helpdesk-geoportal#81]
Dear all,
We have  a problem with the displaying services on the INSPIRE Geoportal.
This refers to the  SSL certificate error. - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 ![img1](https://user-images.githubusercontent.com/96180749/146183376-f08e7a5d-a795-409f-856d-1a0204ffde1a.png)

So, we verify the SSL certificate – and this ok.
![img2](https://user-images.githubusercontent.com/96180749/146183383-6ad0ae42-6946-4052-8611-5aadc3cac808.png)

One of the cases we refer to is the following:
- dataset metadata link: geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f34ca5c46f2649c898a56040b268f59c/xml
- link metadata view service: geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/5f38f61faeaa463b8a826ea7c2e0ba52/xml
- metadata download service link: geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f5b2b3dc387140a095a95095a0984c45/xml

We are waiting for your answer to this problem, because we have many services in this situation, which have a valid SSL certificate, but for which we receive this error when validating with linkage checker or after performing a harvesting process.

Best regards,
Gabriela Magearu,
Romanian technical point of contact

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.
Therefore, open issues affecting the current INSPIRE Geoportal backend will not be addressed unless cases of justified need are identified. 

Once the revamped Geoportal is ready, we will revisit this issue to check if the problems with the certificate remain.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
