### ISSUE TITLE
RO: Infrastructure problems - interruptions in services response

### ISSUE THREAD

**Issue by magearu** [INSPIRE-MIF/helpdesk-geoportal#83]
Dear JRC INSPIRE team,

Sorry for the delay, this is to inform you that we have some technical issues with the infrastructure, in the sense that it has interruptions in the response of the download and viewing services.
Romania's IT team is trying to solve this problems and we will let you know as soon as possible

Thank you in advance,
G. Magearu

**Comment by magearu** [comment]
Dear JRC INSPIRE team,

Please, be informed that the issue described above has been resolved by our IT team

All the best regards,
G. Magearu

**Comment by jescriu** [comment]
Dear @magearu ,
Thanks for letting the INSPIRE Geoportal team know.
I proceed to close the issue.
