### ISSUE TITLE
Will the reported variability of availability through view & download services affect the monitoring results?

### ISSUE THREAD

**Issue by MatAlps** [INSPIRE-MIF/helpdesk-geoportal#84]
Hi helpdesk,

First, thank you for your work, we know that you are really busy at the end of the year and still manage to follow the tickets here.

In the last two weeks variations of the view/download availability results between subsequent harvests of the same unchanged catalog have been reported for Luxembourg (that I represent), slovenia and austria at least (https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/65#issuecomment-990972113, https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/79).

Concretely, we launched harvests just a few hours appart and got different measurements of the number of datasets available through view & download services, while nothing had changed on our side. Immediate testing of failing datasets with the linkage checker tool showed no problems of availability.

We are worried that indicators will be produced that do not reflect the actual state of our catalog & related services.
Can you reassure us and confirm that the monitoring results won't be affected by the variations observed on the harvest console?

Thx.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Particularly, any improvement in the Monitoring and Reporting exercise shall be focused on the new INSPIRE Geoportal system.

Excuses for any inconvenience caused.
