### ISSUE TITLE
login required to access documentation in https://inspire-geoportal.ec.europa.eu/mr2020.html 

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/helpdesk-geoportal#85]
In the https://inspire-geoportal.ec.europa.eu/mr2020.html page, login is required to access the following documents: 
•	[Guidance document for the calculation of indicators](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/356262712/%5BDOC6%5D_MIG10_IndicatorsGuide.pdf?version=1&modificationDate=1560513159335&api=v2)
•	[Indicators calculation](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/403577978/PRES-1.1%20Indicators%20%28JRC%29.pptx?version=1&modificationDate=1571810944755&api=v2)

Could you please update the page making latest versions of these documents directly available?
This issue was originally opened in the INSPIRE Helpdesk, see https://github.com/INSPIRE-MIF/helpdesk/issues/74  .

Thank you

**Comment by MarcoMinghini** [comment]
Dear @sMorrone,
please see [my reply in the original issue](https://github.com/INSPIRE-MIF/helpdesk/issues/74#issuecomment-1004810934). If this is satisfactory, feel free to close this issue.

**Comment by sMorrone** [comment]
Thank you @MarcoMinghini,
the reply is satisfactory and I am closing this issue.
