### ISSUE TITLE
FI: NS4.* indicators, eg. discovery service

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#87]
A question related to the calculation of the NS4.* indicators with an example of the NS4.1 indicator (conformity of discovery services), where the INSPIRE Geoportal plays a role, but the indicators are based on "self-declaration".

The [metadata](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/6f77b9f1-aa4f-4688-ab32-2e721bcfefd9/formatters/xml?approved=true) of the Finnish discovery service passes the metadata validation test for Network services, but indicator NS4.1 is 0%.

What else is the Geoportal/Monitoring checking in the calculation of the NS4.* indicators? How can we check these indicators in advance before the 2022 December deadline?

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
Thank you for spotting this issue.

In principle, NS4.* indicators are based on self-declaration of conformity (of services).
Taking the specific example you provided based on your [discovery service](https://www.paikkatietohakemisto.fi/geonetwork/srv/en/csw?SERVICE=CSW&VERSION=2.0.2&request=GetCapabilities), if you declare in the [service metadata](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/6f77b9f1-aa4f-4688-ab32-2e721bcfefd9/formatters/xml?approved=true) that the service is conformant the INSPIRE Geoportal should maintain the value that you self-declared.

I will check with our IT Team if the INSPIRE Geoportal is performing any additional validation on top of the discovery service (guess not), and if this not the case we will analyse if there is any issue in reading the value of the self-declared conformity.
Therefore, I will come back to you on this.

Having this said, I took the chance to: 

- Validate your [discovery service metadata](https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/6f77b9f1-aa4f-4688-ab32-2e721bcfefd9/formatters/xml?approved=true): with positive result - i.e. metadata is compliant according to the INSPIRE Reference Validator, as you can (temporarily) see in this [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID69b0fdaf-a0a0-411c-b5c5-1bbc753487c0).
- Validate your [discovery service](https://www.paikkatietohakemisto.fi/geonetwork/srv/en/csw?SERVICE=CSW&VERSION=2.0.2&request=GetCapabilities): with negative result - i.e. the service is not compliant according to the INSPIRE Reference Validator, as you can (temporarily) see in this [validation report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDdf40ae60-4d32-4f70-be55-0a286c16e8a5).

Bearing in mind these results, let me clarify that self-declaration of conformity shall be based on the result obtained from the applicable tests in the INSPIRE Reference Validator (which is the reference tool to be utilised when facing this task), which in this case refers to the discovery service, not to its metadata record.

**Comment by jrc-inspire** [comment]
This issue is closed since no more information was provided after the previous message posted on 23 February 2022.
