### ISSUE TITLE
RO: Differences between results with linkage checker and the result of the harvesting process

### ISSUE THREAD

**Issue by magearu** [INSPIRE-MIF/helpdesk-geoportal#90]
Following the harvesting processes, the last one on 15.02.2022, we noticed that a series of data sets do not have visible services https://inspire-geoportal.ec.europa.eu/sandbox/
We  checked  with the linkage checker tool this particular cases and the result regarding resource linkage aspect was completed and at missing resource linkage aspect nothing was identified.
Here are some examples:

1.	Case  https://inspire-geoportal.ec.europa.eu/sandbox/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-7edbed58-ddbc-11e4-b469-52540004b857_20220215-142702%2Fservices%2F1%2FPullResults%2F121-140%2Fdatasets%2F7&expandedSection=metadata

-	Link dataset metadata: [geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/a4c4da0a66074b82bcae46b5b8295102/xml](http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/a4c4da0a66074b82bcae46b5b8295102/xml)
-	link view services metadata [geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/c7fd68305d6642c08a81e367e68fa316/xml](http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/c7fd68305d6642c08a81e367e68fa316/xml)
-	link download services metadata
http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/7d233a5f05944aa59adf39e230ea27d2/xml
- Linkage checker result :
https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-36b611cc-8e67-11ec-8798-0050563f01ec_20220215-145729/

2. Case https://inspire-geoportal.ec.europa.eu/sandbox/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-7edbed58-ddbc-11e4-b469-52540004b857_20220215-142702%2Fservices%2F1%2FPullResults%2F81-100%2Fdatasets%2F18&expandedSection=metadata
-	Link dataset metadata:
[geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f307c3ce88f54191b4d8ba8d8f1a0083/xml](http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f307c3ce88f54191b4d8ba8d8f1a0083/xml)
-	Link view services metadata
[geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f0addae1f72f47e9a0cceba8b71627de/xml](http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/f0addae1f72f47e9a0cceba8b71627de/xml)
-	Link download metadata
http://geoportal.gov.ro/metadata_manager_v2/rest/metadata/item/6254ea50d18043fd8be7054a7a41d8de/xml
- Linkage checker result link
https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-b664c45d-8e69-11ec-8798-0050563f01ec_20220215-151522/

Please help us to identify the cause of this issue.

All the best regards,
G. Magearu

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the reported drop in the number of viewable datasets in the Geoportal. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
