### ISSUE TITLE
SK Missing MD record on EC GP

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#91]
Dear EC INSPIRE GP Team.

When checking the harvested MD from [SK national discovery service](https://inspire-geoportal.ec.europa.eu/results.html?country=sk&view=details&theme=none) (Same with recent harvest results), we have spotted missing MD record https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/37870475/27a79164-5217-46da-832a-e58d3301cd2f

As we can not find it in the harvested records  and record shall meet filter requirement, could you please help us to find out, why the record was not harvested?

Thanks in advance, 

Best regards, 

Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

Thank you for spotting this issue. I have tried to search for this record (by title) in the INSPIRE Geoportal and I can neither find it.

> (Same with recent harvest results)

Do you mean that you already missed this specific record in previous harvest? - Please, let us know in order to orientate our checks.

BTW - I validated the metadata record using the INSPIRE Reference Validator and it is OK.

Best,
Jordi

**Comment by MartinTuchyna** [comment]
Dear Jordi @jescriu ,

for sure, this MD record was already harvested on EC GP, but I don't remember, when I last time saw it there.

Thank you, m

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

As reported in [Missing significant amount of SK download services MD without clear reason](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/92#), the INSPIRE Geoportal Team managed to make some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries.

As a result of it, the harvests have improved and, specifically in the case of SK, you already published the successful results. 

Please, have a look again at the missing dataset you spotted through this post and feel free to come back to us (and open again the present issue) in case it is still missing in the INSPIRE Geoportal after the last harvest.

All the best.
