### ISSUE TITLE
Missing significant amount of SK download services MD without clear reason

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#92]
Dear INSPIRE EC GP  Team,

could you please, check, why Slovakia has lost significant amount of download services after recent harvests 
from 134 in December 2021
to 9 (observed during recent harvests - from January to March) ?

We are not aware about changes on the download services and by random testing these seems to be available and passing lingage checker tests. View services remains stable, even with some increase.

![obrázok](https://user-images.githubusercontent.com/6195936/156471671-456e1a64-94e6-43ee-93d4-f968b3c68f85.png)

![obrázok](https://user-images.githubusercontent.com/6195936/156471532-6243c4bd-9e5a-4f7a-b913-22ef9dc0ef09.png)

![obrázok](https://user-images.githubusercontent.com/6195936/156471628-c8bf44eb-aac5-4347-a762-a3eb3b0b77e1.png)

Thanks in advance,

best regards, Martin T.

**Comment by madlenkk** [comment]
Dear Geoportal team, dear Martin,
It seems that we have similar problem with czech download services - lot of our WFS services which where available whole last year (and also for Monitoring 2021) are now missing in Geoportal. Although we didn´t make any changes and the linkages between resources are correct. 

I would therefore like to know if it is a temporary bug on Geopotal site, or if you have made any permanent changes in Geoportal and we have to modify our download services.

Thanks and best regards,
Magdalena

**Comment by jrc-inspire** [comment]
Dear @MartinTuchyna , @madlenkk,

The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Therefore, open issues affecting the current INSPIRE Geoportal backend will not be addressed unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jrc-inspire** [comment]
Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the reported drop in the number of downloadable datasets for your endpoint. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

Thank you for the bilateral meeting we (INSPIRE Team) had with your SK Team after the last MIG-T Meeting (on 1st April). It was really helpful for us.

As communicated to you through email recently, our INSPIRE Geoportal IT team made some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries.

On 4th May we scheduled a new harvest of the SK discovery service endpoint through the INSPIRE Geoportal harvest console, the results of which you kindly revised and published.
Given the positive feedback you already provided to us by email, we proceed to close this issue.

@madlenkk - On 5th May we also ran a harvest of the CZ discovery service endpoint, the results of which are also available through the harvest console for you check and possibly publish. Please have a look and provide any feedback if needed.

All the best.
