### ISSUE TITLE
Issues encountered when filtering in the INSPIRE Geoportal

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#93]
I encountered issues with filtering according to "Regional" and "Other" spatial scope today. My colleague reproduced the problem, the INSPIRE Geoportal is "Loading data", but not giving a result. The rest of the filtering options works fine.

URL tested: https://inspire-geoportal.ec.europa.eu/results.html?country=fi&view=details&theme=none

My colleague also tested filtering the information of other countries and the same problem occurred there.

We used Chrome version 99.0.4844.51.

**Comment by hallinpihlatie** [comment]
Any news or time table on this?
We have a summer trainee that I was planning to ask to use this functionality in order to do some metadata quality checks.

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Particularly for this issue, once the revamped Geoportal has been rolled-out, the renewed user interface will be appropriately tested to check if the issue has been solved in the migration.

Excuses for any inconvenience caused.

**Comment by jescriu** [comment]
Dear @hallinpihlatie,
This issue was related to the Classic INSPIRE Geoportal, which was dismissed on 24 November 2023, replacing it by the revamped GeoNetwork-based geoportal.
I have cheched the National / Regional filter for FI and it seems to work fine, either in Chrome and Firefox. Therefore, I proceed to close the issue.
Feel free to repen it in case you experience it again.
