### ISSUE TITLE
The Inspire validator result is not correct

### ISSUE THREAD

**Issue by AFCONSULTOLD** [INSPIRE-MIF/helpdesk-geoportal#94]
I am trying to make an Inspire compatible WMS accessible from the Inspire Geoportal. The test result I get when using the Inspire validator against the GetCapabilities XML contains many errors including that the XML is invalid. 

When I validate the xml myself against the schema It is also invalid but if I change the relative path to common.xsd in https://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd to its URL https://inspire.ec.europa.eu/schemas/common/1.0/common.xsd the xml validates.  Most of the other errors we get seems to be related to common.xsd also.

The GetCapabilities I am validating:
https://geodata.socialstyrelsen.se/cgi/mapserv.exe?map=/ms4w/maps/sos-ska-wms.map&service=wms&request=GetCapabilities

**Comment by jescriu** [comment]
Dear @AFCONSULTOL,
I suggest that you are opening a an issue in the generic [INSPIRE helpdesk](https://github.com/INSPIRE-MIF/helpdesk), since your post is not related to the INSPIRE Geoportal, but a generic question on schemas and their validation. 
Therefore, I proceed to close this issue.
